<?php echo $this->doctype(); date_default_timezone_set('Asia/Shanghai');?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('cosmetic') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/jquery-ui.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css'))
                        ;?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/jquery-ui.js'))
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath('js/jquery.min.js')); ?>
    </head>
    <body>
    <!-- 内容页 -->
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
               
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
 
    </body>
</html>