<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('customer') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                       
                        ->prependStylesheet($this->basePath('css/jquery-ui.css'))
                        ->prependStylesheet($this->basePath('css/animate.min.css'))
                        ->prependStylesheet($this->basePath('css/swiper-3.4.2.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css'))
                        ;?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/jquery-ui.js'))
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath('js/swiper-3.4.2.jquery.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js')); ?>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=32f38c9491f2da9eb61106aaab1e9739"></script>
<style type="text/css">
.btnshadow {
-webkit-border-radius: 20px;
-moz-border-radius: 20px;
border-radius: 20px;
box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
}
.radius-circle {
-webkit-border-radius: 20px;
-moz-border-radius: 20px;
border-radius: 20px;
}
label{
	color:#708090;
}
</style>
<script>
$(document).ready(function(){
	  $geolocation = new BMap.Geolocation();  
      $geolocation.getCurrentPosition(function($r) {  
          if (this.getStatus() == BMAP_STATUS_SUCCESS) {  
          
              $myGeo = new BMap.Geocoder();  
            
              $myGeo.getLocation(new BMap.Point($r.point.lng, $r.point.lat),           
                      function($rs) {  
                          $addComp = $rs.addressComponents;  
                          $cusaddress=$addComp.province + $addComp.city  
                          + $addComp.district + $addComp.street  
                          + $addComp.streetNumber;
                          $.post("<?php echo $this->url('customerajax', array('action'=>'cusbrowsingajax'));?>",{
                    			requesturl:"<?php echo $_SERVER['REQUEST_URI'];?>",
                    			cusaddress:$cusaddress
                    		},
                    		function(data,status){
                    			//alert("数据: \n" + data + "\n状态: " + status);
                    		});
                      });  

          } 
      }); 
});
</script>
<script>
function change(file,text) {
var x="0123456789qwertyuioplkjhgfdsazxcvbnm";
var tmp="";
var timestamp = new Date().getTime();
for(var i=0;i< 10;i++) {
tmp += x.charAt(Math.ceil(Math.random()*100000000)%x.length);}
var random=timestamp+tmp;
var obj = document.getElementById(file);
var len = obj.files.length;
for (var i = 0; i < len; i++) {
var temp = obj.files[i].name;}
var fileExt=(/[.]/.exec(temp)) ? /[^.]+$/.exec(temp.toLowerCase()) : '';
var randomname=random+"."+fileExt;
var obj2 = document.getElementById(text);
obj2.value=randomname;
}
</script>
    </head>
    <body style="overflow-y:auto;position: relative;" data-spy="scroll" id="body">
        <div class="container">
            <?php echo $this->content; ?>
            <footer>
               
            </footer>
        </div> <!-- /container -->

    </body>
</html>
