<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('decorate') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/my.css'))
                        ->prependStylesheet($this->basePath('css/swiper.css'))
                        ->prependStylesheet($this->basePath('css/jquery-ui.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css'))
                        ;?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/mydecorate.js'))
            ->prependFile($this->basePath('js/swiper.js'))
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath('js/jquery-ui.js'))
            ->prependFile($this->basePath('js/jquery.min.js')); ?>
    
<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->

<!-- 新 Bootstrap 核心 CSS 文件 -->
    </head>
    <body>
      
            <?php echo $this->content; ?>
        
    </body>
</html>
