<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
        <?php echo $this->headTitle('salonboss') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/bootstrapValidator.css'))
                        ->prependStylesheet($this->basePath('css/jquery-ui.css'))
                        ->prependStylesheet($this->basePath('css/animate.min.css'))
                        ->prependStylesheet($this->basePath('css/swiper-3.4.2.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css'))
                        ->prependStylesheet($this->basePath('css/button1.css'))
                        ;?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrapValidator.js'))
            ->prependFile($this->basePath('js/jquery-ui.js'))
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath('js/swiper-3.4.2.jquery.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js')); ?>
            
<style type="text/css">
.well{
	box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
}
label{
	color:#708090;
}
</style>
    </head>
    <body style="overflow-y:auto;position: relative;" data-spy="scroll" id="body">
        <div class="">
            <?php echo $this->content; ?>
            <footer>
               
            </footer>
        </div> <!-- /container -->

    </body>
</html>
