<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cosmetic\Module'                        => __DIR__ . '/Module.php',
    'Cosmetic\Controller\CosController' => __DIR__ . '/src/Cosmetic/Controller/CosController.php',
    'CosmeticTest\Framework\TestCase'        => __DIR__ . '/tests/Cosmetic/Framework/TestCase.php',
    'CosmeticTest\SampleTest'                => __DIR__ . '/tests/Cosmetic/SampleTest.php',
);
