<?php //TODO 登陆后，在app中存入用户id?>
<script>
	var u = navigator.userAgent;
	var isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1; //android终端
	var isiOS = !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/); //ios终端
    if(isAndroid){
        //加引号就是字符串
    	window.android.cosidsave(<?php echo $cosid;?>);
        }else{
        webkit.messageHandlers.ioscosidsave.postMessage(<?php echo $cosid;?>);
            }
</script>

<?php //TODO 判断是否正在苹果审核?>
<?php if ($account->getIoscheck()=="yes"):?>
<script>
	var u = navigator.userAgent;
	var isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1; //android终端
	var isiOS = !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/); //ios终端
    if(isAndroid){
        //审核中android不变
    	//window.location.href="/cosmetologist/customerlistchatcheck";
        }
    if(isiOS){
        //审核中ios跳转
    	window.location.href="/cosmetologist/customerlistchatcheck";
            }
</script>
<?php endif;?>


<style>
.menubottom{
	z-index:100;
	position:fixed;
	bottom:0px;
	background-color:<?php echo $homepage->getPagecolor();?>;
	}
.bottom-btn{
	border-right:0.1px solid rgba(0, 0, 0, 0.0980392);
	border-top:0.1px solid rgba(0, 0, 0, 0.0980392);
}
.bottom-btn-me{
	border-top:0.1px solid rgba(0, 0, 0, 0.0980392);
}
</style>

<div class="well"><span class="glyphicon glyphicon-list-alt" style="color:red;" aria-hidden="true"></span>&nbsp;&nbsp;订单</div>

<form action="<?php echo $this->url('cosmetologist', array('action'=>'customerlist','sub'=>$id));?>" method="get">
 <div class="input-group input-group-sm" style="padding: 5px;" id="searchcolumn">
      <input type="text" name="searching" class="form-control pageheadbtn"  placeholder="Search for...">
      <span class="input-group-btn">
     <input type="submit" value="搜" class="btn btn-default pageheadbtn">
      </span>
 </div>
</form>
 
<?php
$cars=array();
foreach ($customers as $customer):
if(preg_match("^".$_GET['searching']."^", $customer->getCusname())){
array_push($cars,array(
    "cusid"=>$customer->getCusid(),
    "cusname"=>$customer->getCusname(),
    "cusphone"=>$customer->getCusphone(),
    "cusphoto"=>$customer->getCusphoto()
));?>
<?php } endforeach;?>
 <?php
foreach ($cars as $key => $row) {
$x[$key] = $row['cusid'];
$y[$key] = $row['cusphone'];}
array_multisort($x, SORT_ASC, $y, SORT_ASC, $cars);
?>

<table class="table">
	<caption>客户</caption>
   <thead>
      <tr>
         <th>&nbsp;</th>
         <th>姓名</th>
         <th>电话</th>
      </tr>
   </thead>
    <tbody>
<?php foreach ($cars as $car): if ($car['cusid']!==null){?>
      <tr onclick="location='<?php echo $this->url('cosmetologist', array('action'=>'treatment','sub'=>$car['cusid']));?>'">
         <td><img alt="" style="height:23px;width:23px;" src="/portrait/<?php echo $car['cusphoto'];?>"></td>
         <td><?php echo $car['cusname'];?></td>
         <td><?php echo $car['cusphone'];?></td>
      </tr>
<?php } endforeach;?>
</tbody>
</table>

<?php //TODO 底部菜单栏  用于站位?>
<div class="btn-group btn-group-justified" role="group" style="visibility:hidden">
  <div class="btn-group" role="group" style="text-align:center;" >
  <span class="glyphicon glyphicon-home" style="font-size:25px;color:red;" aria-hidden="true"></span>
  <div style="color:red;">首页</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-time" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>预约</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-edit" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>咨询</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-user" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>我</div>
  </div>
</div>

<?php //TODO 底部菜单栏?>
<div class="btn-group btn-group-justified menubottom" role="group" >
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('cosmetologist', array('action'=>'customerlist','sub'=>$id));?>';">
  <span class="glyphicon glyphicon-list-alt" style="font-size:25px;color:red;" aria-hidden="true"></span>
  <div style="color:red;">订单</div>
  </div>
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('cosmetologist', array('action'=>'appointmentcos'));?>';">
  <span class="glyphicon glyphicon-time" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>预约</div>
  </div>
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('cosmetologist', array('action'=>'customerlistchat'));?>';">
  <span class="glyphicon glyphicon-comment" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>客户
  <?php if($unreadsum){?>
  <span  class="badge" style="background-color:red;"><?php echo $unreadsum;?></span>
  <?php }?>
  </div>
  </div>
  <div class="btn-group bottom-btn-me" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('cosmetologist', array('action'=>'me'));?>';">
  <span class="glyphicon glyphicon-user" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>我</div>
  </div>
</div>

