<div class="well" style="text-align:center">oushelun</div>

<div style="text-align:center">
<img src="/img/mylogo.png" style="height:100px;width:120px;">
</div>


<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cosmetologist', array(
    'action' => 'login'
)));
$form->get('submit')->setAttribute('value', '登陆');
$form->get('submit')->setAttribute('class', 'button blue bigrounded');
$form->prepare();
echo $this->form()->openTag($form);?>
<fieldset style="text-align: center;">
    <legend>账号登陆</legend>
     <label for="name" style="color:red;"><?php echo $result;?></label>
	<div class="form-group">
    <?php echo $this->formRow($form->get('cosphone'));?>
    </div>
    <div class="form-group">
    <?php echo $this->formRow($form->get('cospassword'));?>
    </div>
    <div class="form-group" style="text-align:center">
    <?php echo $this->formInput($form->get('submit')); ?>
    </div>
</fieldset>
<?php echo $this->form()->closeTag($form);?>
