<style>
.menubottom{
	z-index:100;
	position:fixed;
	bottom:0px;
	background-color:<?php echo $homepage->getPagecolor();?>;
	}
#mehead {
       background-color:<?php echo $homepage->getPagecolor();?>;	
/*     background: -webkit-linear-gradient(white, green); /* Safari 5.1 - 6.0 */ */
/*     background: -o-linear-gradient(yellow, green); /* Opera 11.1 - 12.0 */ */
/*     background: -moz-linear-gradient(yellow, green); /* Firefox 3.6 - 15 */ */
/*     background: linear-gradient(yellow, green); /* 标准的语法（必须放在最后） */ */
}
.bottom-btn{
	border-right:0.1px solid rgba(0, 0, 0, 0.0980392);
	border-top:0.1px solid rgba(0, 0, 0, 0.0980392);
}
.bottom-btn-me{
	border-top:0.1px solid rgba(0, 0, 0, 0.0980392);
}
.glyphicon-star{
color:#FFD700;
}
</style>


<div style="text-align:center" id="mehead">
<img src="<?php echo $cosmetologist->getCosphoto();;?>" class="img-circle" style="width:100px;height:100px;">

<button type="button" class="btn btn-default btn-lg "onclick="location='<?php echo $this->url('cosmetologist',
             array('action'=>'login', 'sub'=>$id));?>'">重新登陆</button>
</div> 



<table class="table">
  <caption>对我的评价</caption>
  <thead>
    <tr>
      <th>时间</th>
      <th>星级</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($feedbacks as $feedback):?>
    <tr>
      <td><?php echo $feedback->getFbdate();?></td>
      <td>
<?php switch ($feedback->getFbcosmetologist()):?>
<?php case 1:?>
<span class="glyphicon glyphicon-star"></span>
<?php break;?>
<?php case 2:?>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<?php break;?>
<?php case 3:?>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<?php break;?>
<?php case 4:?>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<?php break;?>
<?php case 5:?>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<?php break;?>
<?php endswitch;?> 
      </td>
    </tr>
    <?php endforeach;?>
  </tbody>
</table>

<?php //TODO 底部菜单栏  用于站位?>
<div class="btn-group btn-group-justified" role="group" style="visibility:hidden">
  <div class="btn-group" role="group" style="text-align:center;" >
  <span class="glyphicon glyphicon-home" style="font-size:25px;color:red;" aria-hidden="true"></span>
  <div style="color:red;">首页</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-time" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>预约</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-edit" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>咨询</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-user" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>我</div>
  </div>
</div>

<?php //TODO 底部菜单栏?>
<div class="btn-group btn-group-justified menubottom" role="group" >
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('cosmetologist', array('action'=>'customerlist','sub'=>$id));?>';">
  <span class="glyphicon glyphicon-list-alt" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>订单</div>
  </div>
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('cosmetologist', array('action'=>'appointmentcos'));?>';">
  <span class="glyphicon glyphicon-time" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>预约</div>
  </div>
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('cosmetologist', array('action'=>'customerlistchat'));?>';">
  <span class="glyphicon glyphicon-comment" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>客户
  <?php if($unreadsum){?>
  <span  class="badge" style="background-color:red;"><?php echo $unreadsum;?></span>
  <?php }?>
  </div>
  </div>
  <div class="btn-group bottom-btn-me" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('cosmetologist', array('action'=>'me'));?>';">
  <span class="glyphicon glyphicon-user" style="font-size:25px;color:red;" aria-hidden="true"></span>
  <div style="color:red;">我</div>
  </div>
</div>
