<style>
.menubottom{
	z-index:100;
	position:fixed;
	bottom:0px;
	background-color:<?php echo $homepage->getPagecolor();?>;
	}
#mehead {
      /* background-color:;	*/
     background: -webkit-linear-gradient(<?php echo $homepage->getPagecolor();?>, white); /* Safari 5.1 - 6.0 */ 
     background: -o-linear-gradient(<?php echo $homepage->getPagecolor();?>, white); /* Opera 11.1 - 12.0 */ 
     background: -moz-linear-gradient(<?php echo $homepage->getPagecolor();?>, white); /* Firefox 3.6 - 15 */ 
     background: linear-gradient(<?php echo $homepage->getPagecolor();?>,white); /* 标准的语法（必须放在最后） */ 
}
.bottom-btn{
	border-right:0.1px solid rgba(0, 0, 0, 0.0980392);
	border-top:0.1px solid rgba(0, 0, 0, 0.0980392);
}
.bottom-btn-me{
	border-top:0.1px solid rgba(0, 0, 0, 0.0980392);
}
.glyphicon-star{
color:#FFD700;
}
</style>


<div style="text-align:center" id="mehead">
<img src="<?php echo $cosmetologist->getCosphoto();;?>" class="img-circle" style="width:110px;height:120px;padding-top:10px;padding-bottom:10px;">

<button type="button" class="button black bigrounded"onclick="location='<?php echo $this->url('cosmetologist',
             array('action'=>'login', 'sub'=>$id));?>'">重新登陆</button>
</div> 

<hr>
<div class="row">
      <div class="col-xs-6 col-sm-6">
     <button type="button" class="btn btn-default btn-lg" onclick="location='<?php echo $this->url('cosmetologist',
             array('action'=>'myfeedbacks'));?>';" style="width: 100%;"><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>&nbsp;&nbsp;我的评价</button>
      </div>
      <div class="col-xs-6 col-sm-6">
     <button type="button" class="btn btn-default btn-lg" onclick="location='<?php echo $this->url('cosmetologist',
             array('action'=>'mytiplist'));?>';" style="width: 100%;"><span class="glyphicon glyphicon-yen" aria-hidden="true"></span>&nbsp;&nbsp;我的打赏</button>
      </div>      
 </div>


<?php //TODO 底部菜单栏  用于站位?>
<div class="btn-group btn-group-justified" role="group" style="visibility:hidden">
  <div class="btn-group" role="group" style="text-align:center;" >
  <span class="glyphicon glyphicon-home" style="font-size:25px;color:red;" aria-hidden="true"></span>
  <div style="color:red;">首页</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-time" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>预约</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-edit" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>咨询</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-user" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>我</div>
  </div>
</div>

<?php //TODO 底部菜单栏?>
<div class="btn-group btn-group-justified menubottom" role="group" >
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('cosmetologist', array('action'=>'customerlist','sub'=>$id));?>';">
  <span class="glyphicon glyphicon-list-alt" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>订单</div>
  </div>
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('cosmetologist', array('action'=>'appointmentcos'));?>';">
  <span class="glyphicon glyphicon-time" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>预约</div>
  </div>
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('cosmetologist', array('action'=>'customerlistchat'));?>';">
  <span class="glyphicon glyphicon-comment" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>客户
  <?php if($unreadsum){?>
  <span  class="badge" style="background-color:red;"><?php echo $unreadsum;?></span>
  <?php }?>
  </div>
  </div>
  <div class="btn-group bottom-btn-me" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('cosmetologist', array('action'=>'me'));?>';">
  <span class="glyphicon glyphicon-user" style="font-size:25px;color:red;" aria-hidden="true"></span>
  <div style="color:red;">我</div>
  </div>
</div>
