<table class="table">
  <caption>我的星</caption>
  <thead>
    <tr>
      <th>日期</th>
      <th>星级</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($services as $service):?>
    <tr>
      <td><?php echo $service->getFbdate();?></td>
      <td><?php echo $service->getFbcosmetologist();?>&nbsp;<span class="glyphicon glyphicon-star-empty"></span></td>
    </tr>
    <?php endforeach;?>
  </tbody>
</table>
