<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Decorate\Module'                        => __DIR__ . '/Module.php',
    'Decorate\Controller\DecController' => __DIR__ . '/src/Decorate/Controller/DecController.php',
    'DecorateTest\Framework\TestCase'        => __DIR__ . '/tests/Decorate/Framework/TestCase.php',
    'DecorateTest\SampleTest'                => __DIR__ . '/tests/Decorate/SampleTest.php',
);
