<style>

.img1 {
	width: 100%;
	max-height: 400px;
	min-height: 200px;
}

.img2 {
	width: 100%;
	max-height: 200px;
	min-height:100px;
}
.pageheadbtn{
	opacity:0.5;
}
.btn-default{
	color:<?php echo $page->getPagecolor();?>;
}

a,span {
	 color:<?php echo $page->getPagecolor();?>;
}
.ui-widget-content a {
	color:<?php echo $page->getPagecolor();?>;
}	
.swiper-slide  {
        font-size: 18px;
        color:<?php echo $page->getPagecolor();?>;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
    }
    .parallax-bg {
        position: absolute;
        left: 0;
        top: 0;
        width: 130%;
        height: 100%;
        -webkit-background-size: 100% 100%;;
        background-size: 100% 100%;;
        background-position: center;
    }
    .swiper-slide .title {
        font-size: 20px;
        font-weight: 300;
    }
    .swiper-slide .text {
        font-size: 7px;
    }
.intro{
	background:<?php echo $page->getPagecolor();?>;
    padding:<?php echo $page->getPagepaddingtop();?>px <?php echo $page->getPagepaddinglr();?>px <?php echo $page->getPagepaddingbottom();?>px;
}
ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
}
</style>



<div class="well input-group input-group-sm" style="text-align:center;">
<?php //判断返回键是活动还是动态
if($page->getPagetype()=="活动"):?>
<span class="input-group-btn" onclick="location='<?php echo $this->url('customer', array('action'=>'homepage','sub'=>$id,'third'=>'activity'));?>'">
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
</span>
<?php elseif ($page->getPagetype()=="动态"):?>
<span class="input-group-btn" onclick="location='<?php echo $this->url('customer', array('action'=>'homepage','sub'=>$id,'third'=>'dynamic'));?>'">
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
</span>
<?php endif;?>
<span><?php echo $page->getPagename();?></span>
</div>
<div class="nav_wrap homepagenav" id="homepagenav1" >
   <ul id="sortable" class="nav_ul">
<?php //TODO 组件输出模块 
include_once 'public/php/templateforui.phtml';?>
	</ul>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$('#signupsubmit').click(function(){
	
		$.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'signup'));?>",dataType:"text",data:{pageid:'<?php echo $page->getPageid();?>',pagename:'<?php echo $page->getPagename();?>',pageexpiration:'<?php echo $page->getPageexpiration();?>',pageheaddata1:'<?php echo $page->getPageheaddata1();?>',pageheaddata2:'<?php echo $page->getPageheaddata2();?>'},type:"POST",success:function(result){
			if($('#signupsubmit').html()=="报名"){
				$('#signupsubmit').html("已报名(再次点击可取消)");
				$('#signupsubmit').removeClass("btn-danger");
				$('#signupsubmit').addClass("btn-success");
				}else{
					$('#signupsubmit').html("报名");
					$('#signupsubmit').removeClass("btn-success");
					$('#signupsubmit').addClass("btn-danger");
					}	
		}});
		})
})
</script>
<?php //占位
if($page->getPagetype()=="活动"):?>
<button type="button" class="btn btn-danger btn-lg btn-block" style="display:none;">报名</button>
<?php if($page->getPageexpiration()<date("Y-m-d")):?>
<button type="button" id="signupsubmit" class="btn btn-warning btn-lg btn-block" style="position: fixed;bottom:0px;" disabled>活动已结束</button>
<?php elseif ($signupstate=="no"):?>
<button type="button" id="signupsubmit" class="btn btn-danger btn-lg btn-block" style="position: fixed;bottom:0px;">报名</button>
<?php else :?>
<button type="button" id="signupsubmit" class="btn btn-success btn-lg btn-block" style="position: fixed;bottom:0px;">已报名(再次点击可取消)</button>
<?php endif;?>
<?php endif;?>