<?php //已作废，详情见2017/11/9 小米便签?>
<li>
<div class="panel panel-success" onclick="location='<?php echo "/customer/activityitem/".$page->getPageid();?>';">
	<div class="panel-heading">
		<h3 class="panel-title"><?php echo $page->getPagename();?></h3>
	</div>
	<div class="panel-body">
<?php foreach ($template as $template):?>
		
<?php switch ($template->getTemplatetype()): ?>
<?php case "singlerow": ?>
                        <div class="row">
							<div class="col">
								<div class="col-demo">
									<img alt="" src="<?php echo $template->getTemplatedata2();?>" style="width:100%;height:150px;">
								</div>
							</div>
						</div>
<?php break;?>
<?php case "doublerow": ?>
                        <div class="row">
							<div class="col">
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<img alt="" src="<?php echo $template->getTemplatedata2();?>" style="width:100%;height:150px;">
								</div>
							</div>
							<div class="col">
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<img alt="" src="<?php echo $template->getTemplatedata4();?>" style="width:100%;height:150px;">
								</div>
							</div>
						</div>
<?php break;?>
<?php case "videorow": ?>
                      <div class="row">
							<div class="col">
								<div class="col-demo">
									<div class="embed-responsive embed-responsive-16by9">
                                     <video width="320"  controls class="videosrc embed-responsive-item" src="<?php echo $template->getTemplatedata1()?>">
                                    </video> 
                                    </div>
								</div>
							</div>
						</div>
<?php break;?>
<?php endswitch ?>


		<?php endforeach;?>
	</div>
	<div class="panel-footer"><?php echo $page->getModificationtime();?></div>
</div>
</li>