<style>

.img1 {
	width: 100%;
	max-height: 400px;
	min-height: 200px;
}

.img2 {
	width: 100%;
	max-height: 200px;
	min-height:100px;
}
.pageheadbtn{
	opacity:0.5;
}
.btn-default{
	color:<?php echo $page->getPagecolor();?>;
}

a,span {
	 color:<?php echo $page->getPagecolor();?>;
}
.ui-widget-content a {
	color:<?php echo $page->getPagecolor();?>;
}	
.swiper-slide  {
        font-size: 18px;
        color:<?php echo $page->getPagecolor();?>;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
    }
    .parallax-bg {
        position: absolute;
        left: 0;
        top: 0;
        width: 130%;
        height: 100%;
        -webkit-background-size: 100% 100%;;
        background-size: 100% 100%;;
        background-position: center;
    }
    .swiper-slide .title {
        font-size: 20px;
        font-weight: 300;
    }
    .swiper-slide .text {
        font-size: 7px;
    }
.intro{
	background:<?php echo $page->getPagecolor();?>;
    padding:<?php echo $page->getPagepaddingtop();?>px <?php echo $page->getPagepaddinglr();?>px <?php echo $page->getPagepaddingbottom();?>px;
}
ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
}
</style>



<div class="well input-group input-group-sm" style="text-align:center;">
<?php //判断返回键是活动还是动态
if($page->getPagetype()=="活动"):?>
<span class="input-group-btn" onclick="location='<?php echo $this->url('customer', array('action'=>'homepage','sub'=>$id,'third'=>'activity'));?>'">
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
</span>
<?php elseif ($page->getPagetype()=="动态"):?>
<span class="input-group-btn" onclick="location='<?php echo $this->url('customer', array('action'=>'homepage','sub'=>$id,'third'=>'dynamic'));?>'">
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
</span>
<?php endif;?>
<span><?php echo $page->getPagename();?></span>
</div>
<div class="nav_wrap homepagenav" id="homepagenav1" >
<ul id="sortable" class="nav_ul">
<?php foreach ($templateitem as $item) :?>
<?php switch ($item->getTemplatetype()): ?>
<?php case "singlerow": ?>
<li  data-type="singlerow" class="ui-state-highlight intro">
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<a  href="<?php echo $item->getTemplatedata1()?>" class="singlea"> <img alt=""
										src="<?php echo $item->getTemplatedata2()?>" class="img1 singleimg">
									</a>
								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "doublerow": ?>
<li  data-type="doublerow" class="ui-state-highlight intro">
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<a  href="<?php echo  $item->getTemplatedata1()?>" class="doublea1"> <img alt=""
										src="<?php echo  $item->getTemplatedata2()?>" class="img2 doubleimg1">
									</a>
								</div>
							</div>
							<div class="col">
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<a  href="<?php echo  $item->getTemplatedata3()?>" class="doublea2"> <img alt=""
										src="<?php echo $item->getTemplatedata4()?>" class="img2 doubleimg2">
									</a>
								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "swiperrow": ?>
<li id="draggable23" data-type="swiperrow" class="ui-state-highlight intro">
		    <!-- Swiper -->
    <div class="swiper-container swiperswiper" style="height:200px">
        <div class="swiper-wrapper">
        <?php if($item->getTemplatedata2()!="/img/123.jpg"):?>
            <div class="swiper-slide"><a  href="<?php echo  $item->getTemplatedata1()?>" class="swipera1"> <img alt=""
										src="<?php echo  $item->getTemplatedata2()?>" class="img1 swiperimg1" style="width: 100%">
									</a></div><?php endif;?>
	    <?php if($item->getTemplatedata4()!="/img/123.jpg"):?>
            <div class="swiper-slide"><a  href="<?php echo  $item->getTemplatedata3()?>" class="swipera2"> <img alt=""
										src="<?php echo  $item->getTemplatedata4()?>" class="img1 swiperimg2" style="width: 100%">
									</a></div><?php endif;?>
	   <?php if($item->getTemplatedata6()!="/img/123.jpg"):?>
            <div class="swiper-slide"><a  href="<?php echo  $item->getTemplatedata5()?>" class="swipera3"> <img alt=""
										src="<?php echo  $item->getTemplatedata6()?>" class="img1 swiperimg3" style="width: 100%">
									</a></div><?php endif;?>
       <?php if($item->getTemplatedata8()!="/img/123.jpg"):?>
            <div class="swiper-slide"><a  href="<?php echo  $item->getTemplatedata7()?>" class="swipera4"> <img alt=""
										src="<?php echo  $item->getTemplatedata8()?>" class="img1 swiperimg4" style="width: 100%">
									</a></div><?php endif;?>
	   <?php if($item->getTemplatedata10()!="/img/123.jpg"):?>
            <div class="swiper-slide"><a  href="<?php echo  $item->getTemplatedata9()?>" class="swipera5"> <img alt=""
										src="<?php echo  $item->getTemplatedata10()?>" class="img1 swiperimg5" style="width: 100%">
									</a></div><?php endif;?>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination swiperpagination"></div>
        </div>
</li>
<?php break;?>
<?php case "headlinerow": ?>
				<li  data-type="headlinerow" class="ui-state-highlight intro">
					<div class="content">
						<div class="row" >
							<div class="col">
							<div class="col-demo">
							<div class="well">
							<a  href="<?php echo $item->getTemplatedata1()?>" class="headlinea">
							<span class="headlinetext"><?php echo $item->getTemplatedata2()?></span>
							<span class="ui-icon ui-icon-triangle-1-e" style="float: right"></span>
							</a>
							</div>
						    </div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "textrow": ?>
<li id="draggable32" data-type="textrow" class="ui-state-highlight intro">
					<div class="content">
						<div class="row" >
							<div class="col">
							<div class="col-demo">
							<div class="well">
							<span class="texttext"><?php echo $item->getTemplatedata1()?> </span>
							</div>
						    </div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "imgtextrow": ?>
<li id="draggable33" data-type="imgtextrow" class="ui-state-highlight intro">
					<!-- Swiper图文 -->
    <div class="swiper-container imgtextswiper" style="height:200px">
        <div class="parallax-bg imgtextimg" data-backgroundimage="<?php echo $item->getTemplatedata1()?>" style="background-image:url(<?php echo $item->getTemplatedata1()?>)" data-swiper-parallax="-23%"></div>
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <div class="title" data-swiper-parallax="-100"><a href="<?php echo $item->getTemplatedata2()?>" class="imgtexttitle1 imgtexta1" ><?php echo $item->getTemplatedata3()?></a></div>
                <div class="text" data-swiper-parallax="-300">
                    <p class="imgtexttext1"><?php echo $item->getTemplatedata4()?></p>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="title" data-swiper-parallax="-100"><a href="<?php echo $item->getTemplatedata5()?>" class="imgtexttitle2 imgtexta2"><?php echo $item->getTemplatedata6()?></a></div>
              
                <div class="text" data-swiper-parallax="-300">
                    <p class="imgtexttext2"><?php echo $item->getTemplatedata7()?></p>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="title" data-swiper-parallax="-100"><a href="<?php echo $item->getTemplatedata8()?>" class="imgtexttitle3 imgtexta3" ><?php echo $item->getTemplatedata9()?></a></div>
              
                <div class="text" data-swiper-parallax="-300">
                    <p class="imgtexttext3"><?php echo $item->getTemplatedata10()?></p>
                </div>
            </div>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination imgtextpagination swiper-pagination-white"></div>
    </div>
</li>
<?php break;?>
<?php case "videorow": ?>
				<li  data-type="videorow" class="ui-state-highlight intro">
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<div class="embed-responsive embed-responsive-16by9">
                                     
                                    <video width="100%"  controls class="videosrc embed-responsive-item" poster="/meicon/corporatelogo2.png">
                                      <source src="<?php echo $item->getTemplatedata1()?>#t=0.1" type="video/mp4">
                                    </video> 
                                    </div>
								
								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php endswitch; ?>
<?php endforeach;?>
	</ul>
</div>

<script type="text/javascript">
$(document).ready(function(){
	$('#signupsubmit').click(function(){
	
		$.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'signup'));?>",dataType:"text",data:{pageid:'<?php echo $page->getPageid();?>',pagename:'<?php echo $page->getPagename();?>',pageexpiration:'<?php echo $page->getPageexpiration();?>',pageheaddata1:'<?php echo $page->getPageheaddata1();?>',pageheaddata2:'<?php echo $page->getPageheaddata2();?>'},type:"POST",success:function(result){
			if($('#signupsubmit').html()=="报名"){
				$('#signupsubmit').html("已报名(再次点击可取消)");
				$('#signupsubmit').removeClass("btn-danger");
				$('#signupsubmit').addClass("btn-success");
				}else{
					$('#signupsubmit').html("报名");
					$('#signupsubmit').removeClass("btn-success");
					$('#signupsubmit').addClass("btn-danger");
					}	
		}});
		})
})
</script>
<?php //占位
if($page->getPagetype()=="活动"):?>
<button type="button" class="btn btn-danger btn-lg btn-block" style="display:none;">报名</button>
<?php if($page->getPageexpiration()<date("Y-m-d")):?>
<button type="button" id="signupsubmit" class="btn btn-warning btn-lg btn-block" style="position: fixed;bottom:0px;" disabled>活动已结束</button>
<?php elseif ($signupstate=="no"):?>
<button type="button" id="signupsubmit" class="btn btn-danger btn-lg btn-block" style="position: fixed;bottom:0px;">报名</button>
<?php else :?>
<button type="button" id="signupsubmit" class="btn btn-success btn-lg btn-block" style="position: fixed;bottom:0px;">已报名(再次点击可取消)</button>
<?php endif;?>
<?php endif;?>