<?php //测试提交github
require_once 'public/alipaysign/AopSdk.php';
$aop = new AopClient;
$aop->alipayrsaPublicKey = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAonUNWUL8oPXgbRtCoEYdaJG1jOFOlotM4AGXAOu+bNgtnqPIGrtFFqGyiCRqHGplHtd4mW2vkrdpmgwabNtp/WZsseLLoDSAizuWWdsetOmQcTcnJWscjq7ukhddAvyr/Id8O3f+AtRP28wkPhaoNqP2LVxVvljH6YrbOtCS2BlCZrtnM0VH2/z97KpJ0ghs+Vs4Z/IeMrK+d2rCsSksCOWmDH93up+XK5OOkQuXqXsfylE8iwd5uL1FkYtaluzwjQhrJFWz8E00Q6HP6pwlrw6zkpem0uiIlEHzRftuydokqDmFSmdzwf1Kk9+fXriMJwQsalzOOQy0dBXfP7C8TwIDAQAB';
$flag = $aop->rsaCheckV1($_POST, NULL, "RSA2");


if ($flag){
    if(!empty($_POST)){
        if($treatment){
           if ($_POST['app_id']=='2018022402261840'&&$_POST['trade_status']=='TRADE_SUCCESS'){
               $timestamp = strtotime($_POST['gmt_payment']);//时间换为时间戳
               $gmtclose = date('YmdHis', $timestamp);//时间戳换为时间
               
               
               $dbms='mysql';     //数据库类型
               $host='47.96.173.116:3306'; //数据库主机名
               $dbName='company';    //使用的数据库
               $user='root';      //数据库连接用户名
               $pass='j12321456';          //对应的密码
               $dsn="$dbms:host=$host;dbname=$dbName";
               
               
               try {
                   $dbh = new PDO($dsn, $user, $pass); //初始化一个PDO对象
                   /*你还可以进行一次搜索操作
                    foreach ($dbh->query('SELECT * from treatment') as $row) {
                    print_r($row); //你可以用 echo($GLOBAL); 来看到这些值
                    }*/
                   $sql = 'UPDATE treatment
        SET trestate="paid",gmtclose="'.$gmtclose.'",paymothed="alipay",payid="'.$_POST['trade_no'].'"
        WHERE orderid="'.$_POST['out_trade_no'].'"';
                   $dbh->query($sql);
                   $dbh = null;
               } catch (PDOException $e) {
                   //die ("Error!: " . $e->getMessage() . "<br/>");
               }
               
               echo "success";
           } 
        }
    }
}
?>

