<?php //test
require_once 'public/alipaysign/AopSdk.php';
$aop = new AopClient;
$aop->alipayrsaPublicKey = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAonUNWUL8oPXgbRtCoEYdaJG1jOFOlotM4AGXAOu+bNgtnqPIGrtFFqGyiCRqHGplHtd4mW2vkrdpmgwabNtp/WZsseLLoDSAizuWWdsetOmQcTcnJWscjq7ukhddAvyr/Id8O3f+AtRP28wkPhaoNqP2LVxVvljH6YrbOtCS2BlCZrtnM0VH2/z97KpJ0ghs+Vs4Z/IeMrK+d2rCsSksCOWmDH93up+XK5OOkQuXqXsfylE8iwd5uL1FkYtaluzwjQhrJFWz8E00Q6HP6pwlrw6zkpem0uiIlEHzRftuydokqDmFSmdzwf1Kk9+fXriMJwQsalzOOQy0dBXfP7C8TwIDAQAB';
$flag = $aop->rsaCheckV1($_POST, NULL, "RSA2");


if ($flag){
    if(!empty($_POST)){
        
           if ($_POST['app_id']=='2018022402261840'&&$_POST['trade_status']=='TRADE_SUCCESS'){
               $timestamp = strtotime($_POST['gmt_payment']);//时间换为时间戳
               $gmtclose = date('YmdHis', $timestamp);//时间戳换为时间
               
               
               $dbms='mysql';     //数据库类型
               $host='localhost'; //数据库主机名
               $dbName='company';    //使用的数据库
               $user='root';      //数据库连接用户名
               $pass='j12321456';          //对应的密码
               $dsn="$dbms:host=$host;dbname=$dbName";
               
               
               
               //取出salnumber,cusid,prodid,productquantity
               preg_match_all("/([^，]+)，/u",
                   $_POST['body'],
                   $out, PREG_PATTERN_ORDER);
               //购买产品
               $salnumber=$out[1][0];
               $cusid=$out[1][1];
               $prodid=$out[1][2];
               $productquantity=$out[1][3];
               //打赏
               $cosid=$out[1][2];
               $tippay=$out[1][3];
               //echo $out[1][0] . "| " . $out[1][1] . "| " .$out[1][2]."| " .$out[1][3]."\n";
               /*你还可以进行一次搜索操作
                foreach ($dbh->query('SELECT * from treatment') as $row) {
                print_r($row); //你可以用 echo($GLOBAL); 来看到这些值
                }*/
               $payid=$_POST['trade_no'];
               $orderid=$_POST['out_trade_no'];
               $paymoney=$_POST['total_amount'];
               
               
               if ($tippay=='tippay')
               {
                   
                   try {
                       $dbh = new PDO($dsn, $user, $pass); //初始化一个PDO对象
                       
                       //打赏改为已支付
                       $sql = 'UPDATE tippay
        SET tipstate="paid",gmtclose="'.$gmtclose.'",paymethod="alipay",payid="'.$payid.'"
        WHERE orderid="'.$orderid.'"';
                       $dbh->query($sql);
                       
                       //用户积分的增加
                       $cuspointsselect='SELECT cuspoints
        FROM cusleveltype
        WHERE cusid="'.$cusid.'"';
                       foreach ($dbh->query($cuspointsselect) as $row) {
                           $cuspoints=$row['cuspoints']+($paymoney*10);
                       }
                       $cuspointsupdate = 'UPDATE cusleveltype
        SET cuspoints="'.$cuspoints.'"
        WHERE cusid="'.$cusid.'"';
                       $dbh->query($cuspointsupdate);
                       
                       //用户打赏金额与打赏次数增加
                       $custipselect='SELECT tipsum,tiptimes
        FROM customer
        WHERE cusid="'.$cusid.'"';
                       foreach ($dbh->query($custipselect) as $row) {
                           $custipsum=$row['tipsum']+$paymoney;
                           $custiptimes=$row['tiptimes']+1;
                       }
                       $custipupdate = 'UPDATE customer
        SET tipsum="'.$custipsum.'",tiptimes="'.$custiptimes.'"
        WHERE cusid="'.$cusid.'"';
                       $dbh->query($custipupdate);
                       
                       //美容师打赏金额与打赏次数增加
                       $costipselect='SELECT tipsum,tiptimes
        FROM cosmetologist
        WHERE cosid="'.$cosid.'"';
                       foreach ($dbh->query($costipselect) as $row) {
                           $costipsum=$row['tipsum']+$paymoney;
                           $costiptimes=$row['tiptimes']+1;
                       }
                       $costipupdate = 'UPDATE cosmetologist
        SET tipsum="'.$costipsum.'",tiptimes="'.$costiptimes.'"
        WHERE cosid="'.$cosid.'"';
                       $dbh->query($costipupdate);
                       
                       
                       //美容院打赏金额与打赏次数增加
                       $salontipselect='SELECT tipsum,tiptimes
        FROM account
        WHERE salnumber="'.$salnumber.'"';
                       foreach ($dbh->query($salontipselect) as $row) {
                           $salontipsum=$row['tipsum']+$paymoney;
                           $salontiptimes=$row['tiptimes']+1;
                       }
                       $salontipupdate = 'UPDATE account
        SET tipsum="'.$salontipsum.'",tiptimes="'.$salontiptimes.'"
        WHERE salnumber="'.$salnumber.'"';
                       $dbh->query($salontipupdate);
                       
                       //欧奢伦的总打赏金额与打赏次数增加
                       $ousheluntipselect='SELECT tipsum,tiptimes
        FROM account
        WHERE salnumber="1"';
                       foreach ($dbh->query($ousheluntipselect) as $row) {
                           $ousheluntipsum=$row['tipsum']+$paymoney;
                           $ousheluntiptimes=$row['tiptimes']+1;
                       }
                       $ousheluntipupdate = 'UPDATE account
        SET tipsum="'.$ousheluntipsum.'",tiptimes="'.$ousheluntiptimes.'"
        WHERE salnumber="1"';
                       $dbh->query($ousheluntipupdate);
                       
                       
                       $dbh = null;
                   } catch (PDOException $e) {
                   }
                   
               }else{
               try {
                   $dbh = new PDO($dsn, $user, $pass); //初始化一个PDO对象
                   
                   //订单改为已支付
                   $sql = 'UPDATE treatment
        SET trestate="paid",gmtclose="'.$gmtclose.'",paymethod="alipay",payid="'.$payid.'"
        WHERE orderid="'.$orderid.'"';
                   $dbh->query($sql);
                   
                   //用户消费金额的增加
                   $cusnumberselect='SELECT cusnumber
        FROM customer
        WHERE cusid="'.$cusid.'"';
                   foreach ($dbh->query($cusnumberselect) as $row) {
                       $cusnumber=$row['cusnumber']+$paymoney;
                   }
                   $cusnumberupdate = 'UPDATE customer
        SET cusnumber="'.$cusnumber.'"
        WHERE cusid="'.$cusid.'"';
                   $dbh->query($cusnumberupdate);
                   
                   //用户积分的增加
                   $cuspointsselect='SELECT cuspoints
        FROM cusleveltype
        WHERE cusid="'.$cusid.'"';
                   foreach ($dbh->query($cuspointsselect) as $row) {
                       $cuspoints=$row['cuspoints']+$paymoney;
                   }
                   $cuspointsupdate = 'UPDATE cusleveltype
        SET cuspoints="'.$cuspoints.'"
        WHERE cusid="'.$cusid.'"';
                   $dbh->query($cuspointsupdate);
                   
                   //产品销量增加
                   $prodsalesselect='SELECT prodsales
        FROM product
        WHERE prodid="'.$prodid.'"';
                   foreach ($dbh->query($prodsalesselect) as $row) {
                       $prodsales=$row['prodsales']+$productquantity;
                   }
                   $prodsalesupdate = 'UPDATE product
        SET prodsales="'.$prodsales.'"
        WHERE prodid="'.$prodid.'"';
                   $dbh->query($prodsalesupdate);
                   
                   //美容院销售金额与销售次数增加
                   $salonprodselect='SELECT prodsum,prodtimes
        FROM account
        WHERE salnumber="'.$salnumber.'"';
                   foreach ($dbh->query($salonprodselect) as $row) {
                       $salonprodsum=$row['prodsum']+$paymoney;
                       $salonprodtimes=$row['prodtimes']+$productquantity;
                   }
                   $salonprodupdate = 'UPDATE account
        SET prodsum="'.$salonprodsum.'",prodtimes="'.$salonprodtimes.'"
        WHERE salnumber="'.$salnumber.'"';
                   $dbh->query($salonprodupdate);
                   
                   //欧奢伦的总销售金额与销售次数增加
                   $oushelunprodselect='SELECT prodsum,prodtimes
        FROM account
        WHERE salnumber="1"';
                   foreach ($dbh->query($oushelunprodselect) as $row) {
                       $oushelunprodsum=$row['prodsum']+$paymoney;
                       $oushelunprodtimes=$row['prodtimes']+$productquantity;
                   }
                   $oushelunprodupdate = 'UPDATE account
        SET prodsum="'.$oushelunprodsum.'",prodtimes="'.$oushelunprodtimes.'"
        WHERE salnumber="1"';
                   $dbh->query($oushelunprodupdate);
                   
                   
                   //ios给院长的通知
                   //取出devicetoken
                   $salonbosstoken='SELECT saltoken
        FROM account
        WHERE salnumber="'.$salnumber.'"';
                   foreach ($dbh->query($salonbosstoken) as $row) {
                       
                       // 这里是我们上面得到的deviceToken，直接复制过来（记得去掉空格）
                       $deviceToken=$row['saltoken'];
                       
                       // Put your private key's passphrase here:
                       $passphrase='j12321456';
                       
                       
                       
                       $message="新的".$paymoney."元订单已支付";
                       
                       
                       ////////////////////////////////////////////////////////////////////////////////
                       
                       $ctx = stream_context_create();
                       stream_context_set_option($ctx, 'ssl', 'allow_self_signed', true);
                       stream_context_set_option($ctx, 'ssl', 'verify_peer', false);
                       stream_context_set_option($ctx, 'ssl', 'local_cert', 'public/pushcertificate/123/salonbossios.pem');
                       stream_context_set_option($ctx, 'ssl', 'passphrase', $passphrase);
                       
                       // Open a connection to the APNS server
                       //这个为正是的发布地址
                        $fp = stream_socket_client('ssl://gateway.push.apple.com:2195', $err, $errstr, 60, STREAM_CLIENT_CONNECT, $ctx);
                       //这个是沙盒测试地址，发布到appstore后记得修改哦
                       //$fp = stream_socket_client('ssl://gateway.sandbox.push.apple.com:2195', $err,$errstr, 60, STREAM_CLIENT_CONNECT|STREAM_CLIENT_PERSISTENT, $ctx);
                       
                       
                       // Create the payload body
                       $body['aps'] = array(
                           'alert' => $message,
                           'sound' => 'default',
                           "badge" => 1
                       );
                       
                       // Encode the payload as JSON
                       $payload = json_encode($body);
                       
                       // Build the binary notification
                       $msg = chr(0) . pack('n', 32) . pack('H*', $deviceToken) . pack('n', strlen($payload)) . $payload;
                       
                       // Send it to the server
                       $result = fwrite($fp, $msg, strlen($msg));
                       
                       fclose($fp);
                   }
                   
                   $dbh = null;
                   
               } catch (PDOException $e) {
                   //die ("Error!: " . $e->getMessage() . "<br/>");
               }
               
                   
              }
               
               
               echo "success";
           } 
        
    }
}
?>

