<?php //test
require_once 'public/alipaysign/AopSdk.php';
$aop = new AopClient;
$aop->alipayrsaPublicKey = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAonUNWUL8oPXgbRtCoEYdaJG1jOFOlotM4AGXAOu+bNgtnqPIGrtFFqGyiCRqHGplHtd4mW2vkrdpmgwabNtp/WZsseLLoDSAizuWWdsetOmQcTcnJWscjq7ukhddAvyr/Id8O3f+AtRP28wkPhaoNqP2LVxVvljH6YrbOtCS2BlCZrtnM0VH2/z97KpJ0ghs+Vs4Z/IeMrK+d2rCsSksCOWmDH93up+XK5OOkQuXqXsfylE8iwd5uL1FkYtaluzwjQhrJFWz8E00Q6HP6pwlrw6zkpem0uiIlEHzRftuydokqDmFSmdzwf1Kk9+fXriMJwQsalzOOQy0dBXfP7C8TwIDAQAB';
$flag = $aop->rsaCheckV1($_POST, NULL, "RSA2");


if ($flag){
    if(!empty($_POST)){
        
           if ($_POST['app_id']=='2018022402261840'&&$_POST['trade_status']=='TRADE_SUCCESS'){
               $timestamp = strtotime($_POST['gmt_payment']);//时间换为时间戳
               $gmtclose = date('YmdHis', $timestamp);//时间戳换为时间
               
               
               $dbms='mysql';     //数据库类型
               $host='47.96.173.116:3306'; //数据库主机名
               $dbName='company';    //使用的数据库
               $user='root';      //数据库连接用户名
               $pass='j12321456';          //对应的密码
               $dsn="$dbms:host=$host;dbname=$dbName";
               
               
               if ($_POST['body']=='tippay')
               {
                   
                   try {
                       $dbh = new PDO($dsn, $user, $pass); //初始化一个PDO对象
                       //打赏改为已支付
                       $sql = 'UPDATE tippay
        SET tipstate="paid",gmtclose="'.$gmtclose.'",paymethod="alipay",payid="'.$_POST['trade_no'].'"
        WHERE orderid="'.$_POST['out_trade_no'].'"';
                       $dbh->query($sql);
                       
                       $dbh = null;
                   } catch (PDOException $e) {
                   }
                   
               }else{
               try {
                   $dbh = new PDO($dsn, $user, $pass); //初始化一个PDO对象
                   
                   //取出cusid,prodid,productquantity
                   preg_match_all("/([^，]+)，/u",
                       $_POST['body'],
                       $out, PREG_PATTERN_ORDER);
                   $cusid=$out[1][0];
                   $prodid=$out[1][1];
                   $productquantity=$out[1][2];
                   //echo $out[1][0] . "| " . $out[1][1] . "| " .$out[1][2]."| " .$out[1][3]."\n";
                   /*你还可以进行一次搜索操作
                    foreach ($dbh->query('SELECT * from treatment') as $row) {
                    print_r($row); //你可以用 echo($GLOBAL); 来看到这些值
                    }*/
                   //订单改为已支付
                   $sql = 'UPDATE treatment
        SET trestate="paid",gmtclose="'.$gmtclose.'",paymethod="alipay",payid="'.$_POST['trade_no'].'"
        WHERE orderid="'.$_POST['out_trade_no'].'"';
                   $dbh->query($sql);
                   
                   //用户消费金额的增加
                   $cusnumberselect='SELECT cusnumber
        FROM customer
        WHERE cusid="'.$cusid.'"';
                   foreach ($dbh->query($cusnumberselect) as $row) {
                       $cusnumber=$row['cusnumber']+$_POST['total_amount'];
                   }
                   $cusnumberupdate = 'UPDATE customer
        SET cusnumber="'.$cusnumber.'"
        WHERE cusid="'.$cusid.'"';
                   $dbh->query($cusnumberupdate);
                   
                   //用户积分的增加
                   $cuspointsselect='SELECT cuspoints
        FROM cusleveltype
        WHERE cusid="'.$cusid.'"';
                   foreach ($dbh->query($cuspointsselect) as $row) {
                       $cuspoints=$row['cuspoints']+$_POST['total_amount'];
                   }
                   $cuspointsupdate = 'UPDATE cusleveltype
        SET cuspoints="'.$cuspoints.'"
        WHERE cusid="'.$cusid.'"';
                   $dbh->query($cuspointsupdate);
                   
                   //产品销量增加
                   $prodsalesselect='SELECT prodsales
        FROM product
        WHERE prodid="'.$prodid.'"';
                   foreach ($dbh->query($prodsalesselect) as $row) {
                       $prodsales=$row['prodsales']+$productquantity;
                   }
                   $prodsalesupdate = 'UPDATE product
        SET prodsales="'.$prodsales.'"
        WHERE prodid="'.$prodid.'"';
                   $dbh->query($prodsalesupdate);
                   
                   
                   $dbh = null;
               } catch (PDOException $e) {
                   //die ("Error!: " . $e->getMessage() . "<br/>");
               }
               }
               
               echo "success";
           } 
        
    }
}
?>

