<div id="cosmetologisttSelect">
<table class="table">
<caption><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;美容师选择</caption>
   <thead>
      <tr>

      </tr>
   </thead>
   <tbody>
   <?php foreach ($cosmetologists as $cosmetologist):?>
      <tr>
         <td><input checked="checked" type="radio" name="cosmetologistName" data-cosid="<?php echo $cosmetologist->getCosid();?>" data-cosname="<?php echo $cosmetologist->getCosname();?>" checked></td>
         <td><?php echo $cosmetologist->getCosname();?></td>
         <td><img alt="" src="<?php echo $cosmetologist->getCosphoto();?>" style="width: 50px;height:30px"></td>
      </tr>
      <?php endforeach;?>
   </tbody>
</table>

</div>