<style>
body{background-color:#EBEBEB;}
.sendborder{border-radius: 15px;padding:5px;font-weight: bold;
    background: -webkit-gradient(linear, left top, left bottom, from(#F5FFFF), to(#fff));
    background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, from(rgb(245, 255, 255)), to(rgb(255, 255, 255)));
    background-position-x: initial;
    background-position-y: initial;
    background-size: initial;
    background-repeat-x: initial;
    background-repeat-y: initial;
    background-attachment: initial;
    background-origin: initial;
    background-clip: initial;
    background-color: initial;
}
.receiveborder{border-radius: 15px;padding:5px;font-weight: bold;
	background: -webkit-gradient(linear, left top, left bottom, from(#9CD852), to(#92D852));
    background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, from(rgb(156, 216, 82)), to(rgb(146, 216, 82)));
    background-position-x: initial;
    background-position-y: initial;
    background-size: initial;
    background-repeat-x: initial;
    background-repeat-y: initial;
    background-attachment: initial;
    background-origin: initial;
    background-clip: initial;
    background-color: initial;
}
</style>
<?php
//表情转换方法
include_once 'public/php/emotionreplace.php';?>

<?php //内容不为空时，输出，且到底
if($chatmodule):?>
<?php
$cars=array();
foreach ($chatmodule as $chat){
array_push($cars,array("id"=>$chat->getId(),
                       "sendid"=>$chat->getSendid(),
                       "receiveid"=>$chat->getReceiveid(),
                       "chatword"=>$chat->getChatword(),
                       "chatpicture"=>$chat->getChatpicture(),
                       "chatdate"=>$chat->getChatdate(),
                       "chatstate"=>$chat->getChatstate()
));
};?>
 <?php
foreach ($cars as $key => $row) {
$x[$key] = $row['id'];
}
if($x){
array_multisort($x, SORT_ASC, $cars);}
?>

<div id="chatfield">
<div class="container">
<?php foreach ($cars as $car): ?>
<?php if($car['sendid']!=='cus'.$cusid){?>
   <div class="row" style="margin:10px">
      <div class="col-xs-2 col-sm-2" style="padding: 5px">
        <img alt="" src="<?php echo $cosmetologist->getCosphoto();?>" style="width:100%">
      </div>
      <div class="col-xs-8 col-sm-8 sendborder">
      <p><?php echo $car['chatdate'];?></p>
      <?php echo ubbReplace($car['chatword']);?>
      <?php if($car['chatpicture']!==null){?>
      <img class="chatpicture" style="width: 100%;height:100%;" src="/chatpicture/<?php echo $car['chatpicture'];?>">
      <?php }?>
      </div>
      <div class="col-xs-2 col-sm-2" style="padding: 5px">
      </div>
   </div>
<?php }else{?>
<div class="row" style="margin:10px">
      <div class="col-xs-2 col-sm-2" style="padding: 5px">
      </div>
      <div class="col-xs-8 col-sm-8 receiveborder">
      <p><?php echo $car['chatdate'];?></p>
      <?php echo ubbReplace($car['chatword']);?>
      <?php if($car['chatpicture']!==null){?>
      <img class="chatpicture" style="width:100%;height:100%;" src="/chatpicture/<?php echo $car['chatpicture'];?>">
      <?php }?>
      </div>
      <div class="col-xs-2 col-sm-2" style="padding: 5px">
     <img alt="" src="/portrait/<?php echo $customer->getCusphoto();?>" style="width:100%">
      </div>
   </div>

<?php }?>
<?php endforeach;?>
</div>
</div>






<script type="text/javascript">
//自动到底
$(document).ready(function(){
	  $h = $(document).height()-$(window).height();
	  $(document).scrollTop($h);
	  $('img').load(function(){
		  $h = $(document).height()-$(window).height();
		  $(document).scrollTop($h); 
		});
});
</script>
<?php endif;?>

<script type="text/javascript">
//图片点击放大
	$('.chatpicture').zoomify();
</script>