<style>
body{background-color:#EBEBEB;}
.sendborder{border-radius: 15px;padding:5px;font-weight: bold;
    background: -webkit-gradient(linear, left top, left bottom, from(#F5FFFF), to(#fff));
    background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, from(rgb(245, 255, 255)), to(rgb(255, 255, 255)));
    background-position-x: initial;
    background-position-y: initial;
    background-size: initial;
    background-repeat-x: initial;
    background-repeat-y: initial;
    background-attachment: initial;
    background-origin: initial;
    background-clip: initial;
    background-color: initial;
}
.receiveborder{border-radius: 15px;padding:5px;font-weight: bold;
	background: -webkit-gradient(linear, left top, left bottom, from(#9CD852), to(#92D852));
    background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, from(rgb(156, 216, 82)), to(rgb(146, 216, 82)));
    background-position-x: initial;
    background-position-y: initial;
    background-size: initial;
    background-repeat-x: initial;
    background-repeat-y: initial;
    background-attachment: initial;
    background-origin: initial;
    background-clip: initial;
    background-color: initial;
}
</style>
<?php
//表情转换方法
include_once 'public/php/emotionreplace.php';?>

<?php //内容不为空时，输出，且到底
if($chatmodule):?>
<?php
$cars=array();
foreach ($chatmodule as $chat){
array_push($cars,array("id"=>$chat->getId(),
                       "sendid"=>$chat->getSendid(),
                       "receiveid"=>$chat->getReceiveid(),
                       "chatword"=>$chat->getChatword(),
                       "chatpicture"=>$chat->getChatpicture(),
                       "chatdate"=>$chat->getChatdate(),
                       "chatstate"=>$chat->getChatstate()
));
};?>
 <?php
foreach ($cars as $key => $row) {
$x[$key] = $row['id'];
}
if($x){
array_multisort($x, SORT_ASC, $cars);}
?>

<div id="chatfield">
<div class="container">
<?php foreach ($cars as $car): ?>
<?php if($car['sendid']!=='cus'.$cusid){?>
   <div class="row" style="margin:10px">
      <div class="col-xs-2 col-sm-2" style="padding: 5px">
        <img alt="" src="<?php echo $cosmetologist->getCosphoto();?>" style="width:100%">
      </div>
      <div class="col-xs-8 col-sm-8 sendborder">
      <p><?php echo $car['chatdate'];?></p>
      <?php echo ubbReplace($car['chatword']);?>
      <?php if($car['chatpicture']!==null){?>
      <img class="chatpicture" style="width: 100%;height:100%;" src="/chatpicture/<?php echo $car['chatpicture'];?>">
      <?php }?>
      </div>
      <div class="col-xs-2 col-sm-2" style="padding: 5px">
      </div>
   </div>
<?php }else{?>
<div class="row" style="margin:10px">
      <div class="col-xs-2 col-sm-2" style="padding: 5px">
      </div>
      <div class="col-xs-8 col-sm-8 receiveborder">
      <p><?php echo $car['chatdate'];?></p>
      <?php echo ubbReplace($car['chatword']);?>
      <?php if($car['chatpicture']!==null){?>
      <img class="chatpicture" style="width:100%;height:100%;" src="/chatpicture/<?php echo $car['chatpicture'];?>">
      <?php }?>
      </div>
      <div class="col-xs-2 col-sm-2" style="padding: 5px">
     <img alt="" src="/portrait/<?php echo $customer->getCusphoto();?>" style="width:100%">
      </div>
   </div>

<?php }?>
<?php endforeach;?>
</div>
</div>






<script type="text/javascript">
//自动到底
$(document).ready(function(){
	  $h = $(document).height()-$(window).height();
	  $(document).scrollTop($h);
	  $('img').load(function(){
		  $h = $(document).height()-$(window).height();
		  $(document).scrollTop($h); 
		});
});
</script>
<?php endif;?>

<script type="text/javascript">
//图片点击放大
	$('.chatpicture').zoomify();
</script>


<?php //ios远程通知
if($_POST['chatword']!=="[refresh]"){ //不是刷新则链接apns
// 这里是我们上面得到的deviceToken，直接复制过来（记得去掉空格）
$deviceToken=$cosmetologist->getCostoken();

// Put your private key's passphrase here:
$passphrase='j12321456';


// Put your alert message here:
$y = $request->getFiles()->toArray();
if ($y['chatpicture']['name'] !== null) {
    $message=$cosmetologist->getCosname()."：[图片]";
}else
if($_POST['chatword']!==""){
    $message=$cosmetologist->getCosname()."：".$_POST['chatword'];
}

////////////////////////////////////////////////////////////////////////////////

$ctx = stream_context_create();
stream_context_set_option($ctx, 'ssl', 'allow_self_signed', true);
stream_context_set_option($ctx, 'ssl', 'verify_peer', false);
stream_context_set_option($ctx, 'ssl', 'local_cert', 'public/pushcertificate/oushelun/cosmetologistios.pem');
stream_context_set_option($ctx, 'ssl', 'passphrase', $passphrase);

// Open a connection to the APNS server
//这个为正是的发布地址
// $fp = stream_socket_client('ssl://gateway.push.apple.com:2195', $err, $errstr, 60, STREAM_CLIENT_CONNECT, $ctx);
//这个是沙盒测试地址，发布到appstore后记得修改哦
$fp = stream_socket_client('ssl://gateway.sandbox.push.apple.com:2195', $err,$errstr, 60, STREAM_CLIENT_CONNECT|STREAM_CLIENT_PERSISTENT, $ctx);

    
    // Create the payload body
    $body['aps'] = array(
    'alert' => $message,
    'sound' => 'default',
    "badge" => $sendunread->getNumber()+1
    );
    
    // Encode the payload as JSON
    $payload = json_encode($body);
    
    // Build the binary notification
    $msg = chr(0) . pack('n', 32) . pack('H*', $deviceToken) . pack('n', strlen($payload)) . $payload;
    
    // Send it to the server
    $result = fwrite($fp, $msg, strlen($msg));
    
    fclose($fp);
    
}
?>
