<link rel="stylesheet" href="/css/zoomify.css">
<script src="/js/zoomify.js"></script>


<?php
//表情转换方法
include_once 'public/php/emotionreplace.php';?>
<style>
.comment { width: 680px; margin: 20px auto; position: relative; background: #fff; padding: 20px 50px 50px; border: 1px solid #DDD; border-radius: 5px; }
.comment h3 { height: 28px; line-height: 28px }
.com_form { width: 100%; position: relative }
.input { width: 99%; height: 60px; border: 1px solid #ccc }
.com_form p { height: 28px; line-height: 28px; position: relative; margin-top: 10px; }
span.emotion { width: 42px; height: 20px; padding-left: 20px; cursor: pointer }
span.emotion:hover { background-position: 2px -28px }
.qqFace { margin-top: 4px; background: #fff; padding: 2px; border: 1px #dfe6f6 solid; }
.qqFace table td { padding: 0px; }
.qqFace table td img { cursor: pointer; border: 1px #fff solid; }
.qqFace table td img:hover { border: 1px #0066cc solid; }
#show { width: 770px; margin: 20px auto; background: #fff; padding: 5px; border: 1px solid #DDD; vertical-align: top; }
.sub_btn { position: absolute; right: 0px; top: 0; display: inline-block; zoom: 1; /* zoom and *display = ie7 hack for display:inline-block */  *display: inline;
vertical-align: baseline; margin: 0 2px; outline: none; cursor: pointer; text-align: center; font: 14px/100% Arial, Helvetica, sans-serif; padding: .5em 2em .55em; text-shadow: 0 1px 1px rgba(0,0,0,.6); -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.2); -moz-box-shadow: 0 1px 2px rgba(0,0,0,.2); box-shadow: 0 1px 2px rgba(0,0,0,.2); color: #e8f0de; border: solid 1px #538312; background: #64991e; background: -webkit-gradient(linear, left top, left bottom, from(#7db72f), to(#4e7d0e)); background: -moz-linear-gradient(top, #7db72f, #4e7d0e);  filter:  progid:DXImageTransform.Microsoft.gradient(startColorstr='#7db72f', endColorstr='#4e7d0e');
}
.sub_btn:hover { background: #538018; background: -webkit-gradient(linear, left top, left bottom, from(#6b9d28), to(#436b0c)); background: -moz-linear-gradient(top, #6b9d28, #436b0c);  filter:  progid:DXImageTransform.Microsoft.gradient(startColorstr='#6b9d28', endColorstr='#436b0c');
}
</style>

<script type="text/javascript" src="/js/jquery.qqFace.js">
//qq表情插件
</script>

<script type="text/javascript" src="/js/ajaxfileupload.js">
//加载ajax上传文件插件
</script>
 
 <div class="input-group input-group-sm" style="background-color:white;padding: 5px;z-index:10;position:fixed;text-align:center;" id="searchcolumn">
      <span class="input-group-btn" onclick="window.history.go(-1);">
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
      <span>
      <?php echo $cosmetologist->getCosname();?>
      </span>
      <span>
      <button type="button" class="btn btn-info" onclick="location='<?php echo $this->url('customer', array('action'=>'chathistory','sub'=>$sub));?>';">聊天历史</button>
      </span>
 </div>
<!-- 没有作用，只为平衡高度 -->
<div class="input-group input-group-sm" style="visibility:hidden;padding: 5px;" >
      <span class="input-group-btn" >
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
      <span>
      <button type="button" class="btn btn-info" onclick="location='<?php echo $this->url('customer', array('action'=>'chathistory','sub'=>$sub));?>';">聊天历史</button>
      </span>
 </div>
<?php
$cars=array();
if($chatmodule){
foreach ($chatmodule as $chat){
array_push($cars,array("id"=>$chat->getId(),
                       "sendid"=>$chat->getSendid(),
                       "receiveid"=>$chat->getReceiveid(),
                       "chatword"=>$chat->getChatword(),
                       "chatpicture"=>$chat->getChatpicture(),
                       "chatdate"=>$chat->getChatdate(),
                       "chatstate"=>$chat->getChatstate()
));
};}?>
 <?php
foreach ($cars as $key => $row) {
$x[$key] = $row['id'];
}
if($x){
array_multisort($x, SORT_ASC, $cars);}
?>

<div id="chatfield">
<div class="container">
<?php foreach ($cars as $car): ?>
<?php if($car['sendid']!=='cus'.$cusid){?>
   <div class="row" style="margin:10px">
      <div class="col-xs-2 col-sm-2" style="padding: 5px">
        <img alt="" src="<?php echo $cosmetologist->getCosphoto();?>" style="width:100%">
      </div>
      <div class="col-xs-8 col-sm-8" style="border:1px solid black;padding:2px;background-image: url(.gif);">
      <p><?php echo $car['chatdate'];?></p>
      <?php echo ubbReplace($car['chatword']);?>
      <?php if($car['chatpicture']!==null){?>
      <img class="chatpicture" style="width: 100%;height:100%;" src="/chatpicture/<?php echo $car['chatpicture'];?>">
      <?php }?>
      </div>
      <div class="col-xs-2 col-sm-2" style="padding: 5px">
      </div>
   </div>
<?php }else{?>
<div class="row" style="margin:10px;">
      <div class="col-xs-2 col-sm-2" style="padding: 5px">
      </div>
      <div class="col-xs-8 col-sm-8" style="border:1px solid black;padding:2px;background-color:rgb(150,220,70);">
      <p><?php echo $car['chatdate'];?></p>
      <?php echo ubbReplace($car['chatword']);?>
      <?php if($car['chatpicture']!==null){?>
      <img class="chatpicture" style="width:100%;height:100%;" src="/chatpicture/<?php echo $car['chatpicture'];?>">
      <?php }?>
      </div>
      <div class="col-xs-2 col-sm-2" style="padding: 5px">
     <img  alt="" src="/portrait/<?php echo $customer->getCusphoto();?>" style="width:100%">
      </div>
   </div>

<?php }?>
<?php endforeach;?>
</div>
</div>
<a href="#tobottom" id="abottom"></a>
<a id="tobottom"></a>
<script type="text/javascript">
//ajax,发送文字
$(document).ready(function(){
    $("#wordsub").click(function(){
    	$.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'chatajax','sub'=>$sub));?>",dataType:"text",data:"chatword="+$("#chatword").val(),type:"POST",success:function(result){
    		$("#chatfield").append(result);
		}});
		$("#chatword").val("");
        });
})
</script>


<script type="text/javascript">
//定时刷新加载
$(function(){
	function show(){
		$.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'chatajax','sub'=>$sub));?>",dataType:"text",data:"chatword=[refresh]",type:"POST",success:function(result){
			$("#chatfield").append(result);
			}});
		}
	setInterval(show,5000);// 注意函数名没有引号和括弧！ 
	// 使用setInterval("show()",3000);会报“缺少对象” 
	});
</script>
<script type="text/javascript">
//影藏图片form
$(document).ready(function(){
    $("#pictureform").hide();
})
</script>
<script type="text/javascript">
//文字发送
$(document).ready(function(){
    $("#wordsubmit").hide();
})
</script>
<script type="text/javascript">
//点击图片按钮即点击上传图片
function uploadpicture(){
	$.ajaxFileUpload({
	    url: "<?php echo $this->url('customerajax', array('action'=>'chatajax','sub'=>$sub));?>", //用于文件上传的服务器端请求地址
	    type: "post",
	    secureuri: false, //一般设置为false
	    fileElementId: "chatpicture", //文件上传空间的id属性
	    dataType: "text", //返回值类型 一般设置为json
	    success:function (result) { //服务器成功响应处理函数
	    	$("#chatfield").append(result);
	    },
	    error : function(data, status, e)//服务器响应失败处理函数 
	    { 
	    alert(e); 
	    } 
	   });
}
</script>


<!-- 没有作用，只为平衡高度 -->
<div class="container" style="width:100%;visibility:hidden;" >
   <div class="row">
      <div class="col-xs-2 col-sm-2">
      <button  style="width:100%">图片</button>
      </div>
      <div class="col-xs-8 col-sm-8">
      <input type="text" class="form-control" id="name" style="width:100%" placeholder="请输入">
      </div>
      <div class="col-xs-2 col-xs-2">
      <button class="btn btn-default" style="width:100%">发送</button>
      </div>
   </div>
</div>

<div class="container" style="position:fixed;bottom:0px;width:100%;" >
   <div class="row">    
      <div class="col-xs-1 col-sm-1">
      <img alt="" src="/img/pictureicon.png" style="width: 100%;height:100%;" id="btnpicture" onclick="$('#chatpicture').click()">
       </div>
      <div class="col-xs-1 col-sm-1">
       <img alt="" src="/img/emotionicon.png" style="width: 100%;height:100%;" class="emotion">
       </div>
      <div class="col-xs-8 col-sm-8">
      <input type="text" id="chatword" class="form-control" id="name" style="width:100%" placeholder="请输入">
      </div>
      <div class="col-xs-2 col-xs-2">
      <button class="btn btn-default radius-circle" id="wordsub" style="width:100%">发送</button>
      </div>
   </div>
</div>


<div id="pictureform" style="display:none;">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('customer', array(
    'action' => 'chat','sub'=>$sub
)));
$form->get('submit')->setAttribute('value', 'Add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formrow($form->get('chatpicture'));
?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);?>
</div>
<script type="text/javascript">
//自动到底
$(document).ready(function(){
	  $h = $(document).height()-$(window).height();
	  $(document).scrollTop($h);
	  $('img').load(function(){
		  $h = $(document).height()-$(window).height();
		  $(document).scrollTop($h); 
		});
});
</script>

<script type="text/javascript">

$(function(){

	$('.emotion').qqFace({

		id : 'facebox', 

		assign:'chatword', 

		path:'/arclist/'	//表情存放的路径

	});

});


</script>


<script type="text/javascript">
//图片点击放大
	$('.chatpicture').zoomify();
</script>