<?php
//表情转换方法
include_once 'public/php/emotionreplace.php';?>


<link rel="stylesheet" href="/css/zoomify.css">
<script src="/js/zoomify.js"></script>

<style>
.fbpicture3 {
	padding:2px;
    width: 100%;
}
.glyphicon-star{
color:#FFD700;
}
#mehead {
     background: -webkit-linear-gradient(<?php echo $homepage->getPagecolor();?>, white); /* Safari 5.1 - 6.0 */ 
     background: -o-linear-gradient(<?php echo $homepage->getPagecolor();?>, white); /* Opera 11.1 - 12.0 */ 
     background: -moz-linear-gradient(<?php echo $homepage->getPagecolor();?>, white); /* Firefox 3.6 - 15 */ 
     background: linear-gradient(<?php echo $homepage->getPagecolor();?>,white); /* 标准的语法（必须放在最后） */
}
	span{color: #708090;font-size:120%}
</style>
<style>

.img1 {
	width: 100%;
	max-height: 400px;
	min-height: 200px;
}

.img2 {
	width: 100%;
	max-height: 200px;
	min-height:100px;
}
.pageheadbtn{
	opacity:0.5;
}
.btn-default{
	color:<?php echo $homepage->getPagecolor();?>;
}


.ui-widget-content a {
	color:<?php echo $homepage->getPagecolor();?>;
}	
.swiper-slide  {
        font-size: 18px;
        color:<?php echo $homepage->getPagecolor();?>;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
    }
    .parallax-bg {
        position: absolute;
        left: 0;
        top: 0;
        width: 130%;
        height: 100%;
        -webkit-background-size: 100% 100%;;
        background-size: 100% 100%;;
        background-position: center;
    }
    .swiper-slide .title {
        font-size: 20px;
        font-weight: 300;
    }
    .swiper-slide .text {
        font-size: 7px;
    }

ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
}
</style>


<?php //TODO 页头?>
<script type="text/javascript">
//上滑消失，下滑显示
$(document).ready(function(){
	$("#fixedstandard").css({"height":$("#headanchor").height()});
	$x= $("#fixedstandard").offset().top - $(window).scrollTop();//变化中参考div距离屏幕高度
	$(document).scroll(function(){
		if($x>$("#fixedstandard").offset().top - $(window).scrollTop()){
              $("#headanchor").slideUp("slow");
              $x= $("#fixedstandard").offset().top - $(window).scrollTop();
			}else{
				$("#headanchor").slideDown("slow");
	            $x= $("#fixedstandard").offset().top - $(window).scrollTop();
			}
		});
})
</script>
<!-- 页头 -->

<div class="input-group input-group-sm"
	style="position: fixed; z-index: 2; background: white;" id="headanchor">
	<span class="input-group-btn" onclick="window.history.back();"> 
	<span class="glyphicon glyphicon-chevron-left btn"></span>
	</span> <span class="input-group-btn"> <a href="#mehead" class="btn">基本信息</a>
	</span> <span class="input-group-btn"> <a href="#homepagenav1"
		class="btn">详情</a>
	</span>
    <span class="input-group-btn"> <a href="#feedbacks" class="btn">评价</a></span>
</div>
<div id="fixedstandard"></div>

<div style="text-align:center" id="mehead" class="container">
   <div class="row">
      <div class="col-xs-5 col-sm-5">
      <img src="<?php echo $cosmetologist->getCosphoto();?>" class="img-circle" style="width:110px;height:120px;padding-top:10px;padding-bottom:10px;">
      </div>
      <div class="col-xs-7 col-sm-7*">
      <div class="row" style="padding-top:10px;">
      <span><?php echo $cosmetologist->getCosname();?></span>
      </div>
      
      <div class="row" style="padding-top:10px;">
      <span>专长:</span>
      <span><?php echo $cosmetologist->getCosspeciality();?></span>
      </div>
      
      
      <div class="row" style="padding-top:10px;">
       <span>从业时长:</span>
      <span><?php echo $cosmetologist->getCosyears();?></span>
      </div>
      
      </div>
   </div>
</div> 



<div class="nav_wrap homepagenav" id="homepagenav1" >
   <ul id="sortable" class="nav_ul">
<?php //TODO 组件输出模块 
include_once 'public/php/templateforui.phtml';?>
	</ul>
</div>

<div id="feedbacks">

<div class="panel panel-default" id="svn">
	<div class="panel-heading" id="feedbacks"><span class="title">评价</span></div>
	<div class="panel-body">
	  <div class="container">
	  <?php foreach ($feedbacks as $feedback):?>
         <div class="row">
           <div class="col-xs-6 col-sm-6">
           <img alt="" style="width:20px;height:20px;" src="/portrait/<?php echo $feedback->getCusphoto();?>">
           <span class="thirdtitle"><?php echo $feedback->getCusname();?></span></div>
           <div class="col-xs-6 col-sm-6"><?php echo $feedback->getFbdate();?></div>      
          </div>
          <br>
          <div class="row">
           <div class="col-xs-12 col-sm-12"><span class="subtitle"><?php echo ubbReplace($feedback->getFbadvise2());?></span></div>    
          </div>
          <br>
          <div class="row">
          <?php 
          preg_match_all("/([^;]+);/u",
              $feedback->getSmallpicturegroup3(),
              $original, PREG_PATTERN_ORDER);
          preg_match_all("/([^;]+);/u",
              $feedback->getOriginalpicturegroup3(),
              $zoomed, PREG_PATTERN_ORDER);
          for ($i=0;$i<count($original[1]);$i++):
          ?>
           <div class="col-xs-3 col-sm-3"><img data-zoomed="/fbpicture/<?php echo $zoomed[1][$i];?>" class="fbpicture3" alt=""  data-original="/fbpicture/<?php echo $original[1][$i];?>"></div>
          <?php endfor;?>
          </div>
           <div class="row">
           <div class="col-xs-12 col-sm-12">
           评星：
<?php switch ($feedback->getFbcosmetologist()):?>
<?php case 1:?>
<span class="glyphicon glyphicon-star"></span>
<?php break;?>
<?php case 2:?>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<?php break;?>
<?php case 3:?>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<?php break;?>
<?php case 4:?>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<?php break;?>
<?php case 5:?>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<span class="glyphicon glyphicon-star"></span>
<?php break;?>
<?php endswitch;?>
           </div>    
          </div>
           <?php if ($feedback->getSalcomment2()):?>
          <div class="row">
           <div class="col-xs-12 col-sm-12" style='background-color: #D3D3D3;border-radius: 8px;'>
           <span class="subtitle" style="">店家回复：<?php echo ubbReplace($feedback->getSalcomment3());?></span>
           </div>    
          </div>
          <?php endif;?>
          <hr>
        <?php endforeach;?>
       </div>
	
	</div>
</div>

</div>


<script type="text/javascript">
//图片点击放大
	$('.fbpicture3').zoomify();
</script>
<script type="text/javascript">
//图片点击放大
$(document).ready(function(){
	$('.fbpicture3').click(function(){
		setTimeout('$("body").scrollTop($("body").scrollTop()+1)',1)
		
		});
})
</script>