<style>
.stamp {  display: inline-block; padding: 10px; background: white; position: relative; -webkit-filter: drop-shadow(0px 0px 10px rgba(0,0,0,0.5)); /*The stamp cutout will be created using crisp radial gradients*/
background: radial-gradient(  transparent 0px,  transparent 4px,  white 4px,  white  ); /*reducing the gradient size*/
background-size: 20px 20px; /*Offset to move the holes to the edge*/
background-position: -10px -10px; }
.stamp:after { content: ''; position: absolute; /*We can shrink the pseudo element here to hide the shadow edges*/
left: 5px; top: 5px; right: 5px; bottom: 5px; /*Shadow - doesn't look good because of the stamp cutout. We can still move this into another pseudo element behind the .stamp main element*/
    
  /*box-shadow: 0 0 20px 1px rgba(0, 0, 0, 0.5);*/
    /*pushing it back*/
z-index: -1; }
/*Some text*/
.stamp:before { content: '劵'; position: absolute; bottom: 0; left: 0; font: bold 24px arial; color: white; opacity: 0.75; line-height: 100%; padding: 20px; }
</style>
<?php //TODO 优惠券?>
<script>
//优惠券
$(function() {
	$("#successAlert").hide();
})
</script>


<div class="input-group input-group-sm"
	style="position: fixed; z-index: 2; background: white;" id="headanchor">
	<span class="input-group-btn" onclick="window.history.back();"> 
	<span class="glyphicon glyphicon-chevron-left btn"></span>
	</span> <span class="input-group-btn"> <a href="#ios" class="btn" id="x">优惠券</a></span>
</div>
<div id="fixedstandard" style="visibility:hidden;">
<span class="input-group-btn" onclick="window.history.back();"> 
	<span class="glyphicon glyphicon-chevron-left btn"></span>
	</span> <span class="input-group-btn"> <a href="#ios" class="btn" id="x">优惠券</a></span>
</div>

<div style="text-align:center;">  
<?php
// 通过ajax领取优惠券，并返回领取的结果
foreach ($saloncouponissues as $saloncouponissue) :
if (strtotime($saloncouponissue->getSciavailable()) > time()&&$saloncouponissue->getScitimes()>0) {
    
    ?>  
<div class="container stamp" style="margin:10px;">
		<div class="row"
			style="background-color: rgb(255, 241, 241); border-radius: 15px;">
			<div class="col-xs-8 col-sm-8" style="padding: 10px;">
				<p style="font-size: large;color:red;">¥<?php echo $saloncouponissue->getScimoney();?></p>
				<p>满<?php echo $saloncouponissue->getScirestriction();?>使用</p>
				<p>截止日期：<?php echo $saloncouponissue->getSciavailable();?></p>
			</div>
			<div class="col-xs-4 col-sm-4"
				style="text-align: center; padding-top: 40px;"
				onclick='$.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'saloncoupongetajax'));?>",dataType:"text",
data:{sciid:<?php echo $saloncouponissue->getSciid();?>,scimoney:<?php echo $saloncouponissue->getScimoney();?>,
scirestriction:<?php echo $saloncouponissue->getScirestriction();?>,comparedate:<?php echo $saloncouponissue->getComparedate();?>},
type:"POST",success:function(result){$("#successAlert").show();$("#successAlert").html(result);setTimeout(function(){$("#successAlert").hide()},1000);}});'>
				<p style="font-size: large;color:pink;">点击领取</p>
				<p>限领次数：<?php echo $saloncouponissue->getScitimes();?></p>
			</div>
		</div>
</div>
<?php }endforeach;?>
</div> 
<div class="alert alert-success" style="position: fixed; bottom: 100px;width:100%;z-index：120;display:none;z-index:1000;" id="successAlert" align="center"></div>