<?php //文件上传?>
<link href="/css/fileinput.min.css" media="screen" rel="stylesheet" type="text/css">
<script src="/js/fileinput.min.js"></script>
<script src="/js/fileinput.zh.js"></script>

<?php //星星评级?>
<link href="/raty/labs.css" media="screen" rel="stylesheet" type="text/css">
<script src="/raty/labs.js"></script>
<link href="/lib/jquery.raty.css" media="screen" rel="stylesheet" type="text/css">
<script src="/lib/jquery.raty.js"></script>


<script> 
$(document).ready(function(){
  $("#loadingimg").hide();//加载图隐藏
  $("#flip1").click(function(){
    $("#panel1").slideToggle("slow");
    $("#menudown1").toggle();
    $("#menuup1").toggle();
  });
  $("#flip2").click(function(){
	    $("#panel2").slideToggle("slow");
	    $("#menudown2").toggle();
	    $("#menuup2").toggle();
	  });
  $("#flip3").click(function(){
	    $("#panel3").slideToggle("slow");
	    $("#menudown3").toggle();
	    $("#menuup3").toggle();
	  });
});
</script>

<style>
.addBorder{
	border:2px solid #FFDAB9;
	margin:2px;
}
#panel1 {display:none;}
#panel2 {display:none;}
#panel3 {display:none;}
#menuup1 {display:none;}
#menuup2 {display:none;}
#menuup3 {display:none;}
</style>

<div class="input-group input-group-sm"
	style="position: fixed; z-index: 20; background: white;" id="headanchor">
	
	<span class="input-group-btn"> <a style="font-size:15px;font-weight:bold;" href="<?php echo $this->url('customer', array('action'=>'homepage','sub'=>$id));?>" class="btn">
	<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;&nbsp;
	评价与建议</a>
	</span> 
</div>
<div class="input-group input-group-sm"
	style="background: white;" >
	
	<span class="input-group-btn"> <a href="<?php echo $this->url('customer', array('action'=>'homepage','sub'=>$id));?>" class="btn">评价与建议</a>
	</span> 
</div>



<?php //加载图?>
<img id="loadingimg" src="/img/loading.gif" style="width:100%;position:fixed;z-index:10;">

<?php
$form = $this->form;
$form->setAttribute('action',$this->url('customer', array('action' => 'feedbacks','sub'=>$treatment->getTreid(),'third'=>$cosid)));

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formhidden($form->get('treid'));
echo $this->formhidden($form->get('salbranch'));
echo $this->formhidden($form->get('cosid'));
echo $this->formhidden($form->get('fbsurrounding'));
echo $this->formhidden($form->get('fbproduct'));
echo $this->formhidden($form->get('fbcosmetologist'));?>
<div class="container">

<div class="addBorder">
<div class="row well" id="flip1" style="color: #696969;font-weight:bold">
<span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;环境评星与评价
<span id="menudown1" class="glyphicon glyphicon-chevron-down" aria-hidden="true" style="float:right;"></span>
<span id="menuup1" class="glyphicon glyphicon-chevron-up" aria-hidden="true" style="float:right;"></span></div>
   <div id="panel1">
   <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>&nbsp;评星</label>
     <div class="row">
      <div class="col-sm-6 col-xs-6">
      <img src="<?php echo $salonbranch->getSalphoto1();?>" style="height:100px;width:120px;">
      </div>
      <div class="col-sm-6 col-xs-6">
      <div class="row"><span style="font-weight:bold;">美容院：</span><?php echo $salonbranch->getSalname();?></div>
      <div class="row" id="div1" data-score="1"></div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-font" aria-hidden="true"></span>&nbsp;评价</label>
     <?php echo $this->formRow($form->get('fbadvise'));?>
  </div>
  <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp;图片</label>
    <?php echo $this->formhidden($form->get('fbpicture1'));?>
    <?php echo $this->formRow($form->get('fbpicture1f'));?>
  </div>
  </div>
</div>
<br> <br> 
<div class="addBorder">
<div class="row well" id="flip2" style="color: #696969;font-weight:bold">
<span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>&nbsp;产品评星与评价
<span id="menudown2" class="glyphicon glyphicon-chevron-down" aria-hidden="true" style="float:right;"></span>
<span id="menuup2" class="glyphicon glyphicon-chevron-up" aria-hidden="true" style="float:right;"></span></div>
 <div id="panel2">
 <div class="form-group">
  <label for="name"><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>&nbsp;评星</label>
   <div class="row">
    <div class="col-sm-6 col-xs-6">
      <img src="<?php echo $treatment->getProductcombinationpicture();?>" style="height:100px;width:120px;">
      </div>
      <div class="col-sm-6 col-xs-6">
      <div class="row"><span style="font-weight:bold;">产品：</span>
      <span><?php echo $treatment->getProductcombinationname();?></span>
      <p style="font-size: 130%;"><?php echo $treatment->getProdtitle();?><p></div>
      <div id="div2" data-score="1"></div>
      </div>
   </div>
 </div>
 <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-font" aria-hidden="true"></span>&nbsp;评价</label>     
      <?php echo $this->formRow($form->get('fbadvise1'));?>
 </div>
 <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp;图片</label>
    <?php echo $this->formhidden($form->get('fbpicture2'));?>
    <?php echo $this->formRow($form->get('fbpicture2f'));?>
  </div>
  </div>
</div>
  <br> <br>  
<div class="addBorder">   
<div class="row well" id="flip3" style="color: #696969;font-weight:bold">
<span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;服务评星与评价
<span id="menudown3" class="glyphicon glyphicon-chevron-down" aria-hidden="true" style="float:right;"></span>
<span id="menuup3" class="glyphicon glyphicon-chevron-up" aria-hidden="true" style="float:right;"></span></div>   
 <div id="panel3">
 <div class="form-group">
  <label for="name"><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>&nbsp;评星</label>  
   <div class="row">
    <div class="col-sm-6 col-xs-6">
      <img src="<?php echo $cosmetologist->getCosphoto();?>" style="height:100px;width:120px;">
      </div>
      <div class="col-sm-6 col-xs-6">
      <div class="row"><span style="font-weight:bold;">美容师：</span><?php echo $cosmetologist->getCosname();?></div>
      <div id="div3" data-score="1"></div>
      </div>
   </div>
 </div>
 <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-font" aria-hidden="true"></span>&nbsp;评价</label>          
      <?php echo $this->formRow($form->get('fbadvise2'));?> 
 </div>
 <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp;图片</label>
    <?php echo $this->formhidden($form->get('fbpicture3'));?>
    <?php echo $this->formRow($form->get('fbpicture3f'));?>
  </div>
  </div>
</div>
<div class="row well" ><?php echo $this->formInput($form->get('submit')); ?></div> 






 
 </div>
<?php
echo $this->form()->closeTag($form);?>   
   
   



<script>
$('#fbsurrounding').val(3);
$('#fbproduct').val(3);
$('#fbcosmetologist').val(3);
$('#div1').raty({
	score:3,
	  click: function(score, evt) {
		  $('#fbsurrounding').val(score);
	  }
	});
</script>

<script>
$('#div2').raty({
	score:3,
	  click: function(score, evt) {
		  $('#fbproduct').val(score);
	  }
	});
</script>

<script>
$('#div3').raty({
	score:3,
	  click: function(score, evt) {
		  $('#fbcosmetologist').val(score);
	  }
	});
</script>

<script>
$(document).on('ready', function() {
    $("#fbpicture1f").fileinput({
    	language: 'zh', //设置语言
     allowedFileExtensions: ['jpg', 'gif', 'png','jpeg'],
    });
});
</script>
<script>
$(document).on('ready', function() {
    $("#fbpicture2f").fileinput({
    	language: 'zh', //设置语言
     allowedFileExtensions: ['jpg', 'gif', 'png','jpeg'],
    });
});
</script>
<script>
$(document).on('ready', function() {
    $("#fbpicture3f").fileinput({
    	language: 'zh', //设置语言
     allowedFileExtensions: ['jpg', 'gif', 'png','jpeg'],
    });
});
</script>

<script type="text/javascript">
//填入treid和cosid
$(document).ready(function(){
	 $("#treid").val('<?php echo $treid;?>');
     $("#cosid").val('<?php echo $cosid;?>');
     $("#salbranch").val('<?php echo $salonbranch->getSalbranch();?>');
});
</script>

                
<script>
$(document).ready(function() {
	//提交时显示加载图
	$("#fbsubmit").click(function(){
        $("#loadingimg").show();
		})
});
</script>