<?php
use Apple\ApnPush\Certificate\Certificate;
use Apple\ApnPush\Protocol\Http\Authenticator\CertificateAuthenticator;
use Apple\ApnPush\Sender\Builder\Http20Builder;
use Apple\ApnPush\Sender\Sender;
use Apple\ApnPush\Model\Notification;
use Apple\ApnPush\Model\DeviceToken;
use Apple\ApnPush\Model\Receiver;

// Create certificate and authenticator
$certificate = new Certificate('public/pushcertificate/123/customerios.pem', 'j12321456');
$authenticator = new CertificateAuthenticator($certificate);

// Build sender
$builder = new Http20Builder($authenticator);

$sender = $builder->build();

// some actions/send push notifications
$notification = Notification::createWithBody('Hello ;)');
$receiver = new Receiver(new DeviceToken('8eda91a44c7347096b59096dd9f09ce64c7afb0ad95612001df83f93271f83c4'), 'oushelun.Cosmetologistios');

$sender->send($receiver, $notification);



// some actions