<?php //改动： 排序由按钮触发ajax完成
$homepage2cars=array();
foreach ($products as $product){
array_push($homepage2cars,array("prodid"=>$product->getProdid(),"prodsales"=>$product->getProdsales(),
    "prodtitle"=>$product->getProdtitle(),"prodpicture1"=>$product->getProdpicture1(),
    "prodprice"=>$product->getProdprice(),"prodoriginal"=>$product->getProdoriginal(),
    "prodregdate"=>$product->getProdregdate(),
    "proddiscount"=>$product->getProddiscount()));
}?>
<?php  //风格1
if ($prodstyle=="1"):?>
<?php  //存在则输出， 不存在则为空
if ($homepage2cars):?>
<?php foreach ($homepage2cars as $car): ?>
<div class="row productdisplay"  onclick="location='<?php echo $this->url('customer', array('action'=>'productitem','sub'=>$car["prodid"]));?>';">
  <div class="col-xs-4"><img alt="" src="<?php echo $car["prodpicture1"];?>" style="height:124px;width:100%"></div>
  <div class="col-xs-8" style="padding: 2px">
  <p class="producttitle"><?php echo $car["prodtitle"];?></p>
  <!-- <p>销量<?php echo $car["prodsales"];?></p> -->
  <p>原价：<span style="text-decoration:line-through;color:gray;"><?php echo $car["prodoriginal"];?></span></p>
  <p>
  <span style="color:red;font-size:large;">¥ <?php echo $car["prodprice"];?></span>
  <span style="float:right;color:gray;">销量：<?php echo $car["prodsales"];?></span>
  </p>
  </div>
</div>
<?php endforeach;?>
<?php if (count($homepage2cars)<10):?>
<div  class="" style="text-align:center;color:#696969;">
已加载全部。。。
</div>
<?php else:?>
<div  class="prodloading" style="text-align:center;color:#696969;">
加载中。。。
</div>
<?php endif;?>
<?php endif;?>
<?php   //风格2
elseif ($prodstyle=="2"):?>
<?php  //存在则输出， 不存在则为空
if ($homepage2cars):?>
<?php foreach ($homepage2cars as $car): ?>
  <div class="col-xs-6 productdisplay" onclick="location='<?php echo $this->url('customer', array('action'=>'productitem','sub'=>$car["prodid"]));?>';">
  <img alt="" src="<?php echo $car["prodpicture1"];?>" style="height:150px;width:100%">
  <div style="padding: 3px;">
  <p class="producttitle"><?php echo $car["prodtitle"];?></p>
  <p>原价：<span style="text-decoration:line-through;color:gray;font-size:small;"><?php echo $car["prodoriginal"];?></span></p>
  <p>
  <span style="color:red;font-size:large;">¥ <?php echo $car["prodprice"];?></span>
  <span style="float:right;color:gray;">销量：<?php echo $car["prodsales"];?></span>
  </p>
  </div>
  </div>
<?php endforeach;?>
<?php if (count($homepage2cars)<10):?>
<div  class="" style="text-align:center;color:#696969;">
已加载全部。。。
</div>
<?php else:?>
<div  class="prodloading" style="text-align:center;color:#696969;">
加载中。。。
</div>
<?php endif;?>
<?php endif;?>
<?php endif;?>