<script>
$(document).ready(function(){
	$.ajax({url:"<?php echo $this->url('customer', array('action'=>'foo'));?>",dataType:"text",
		data:{prodid:'123'}
	,type:"POST",
		success:function(result){
			$("#div1").html(result);
			//location="<?php //echo $this->url('customer', array('action'=>'foo'));?>";
			//setTimeout(function () { 延迟跳转用户多次点击提交订单会生成多个订单
				// location="<?php // echo $this->url('customer', array('action'=>'me'));?>";
				 //}, 3000);
			
	}});
})
</script>
<div id="div1"></div>
