<style>
#angleimgtopright{
	transform:rotate(90deg);
-ms-transform:rotate(90deg); /* Internet Explorer */
-moz-transform:rotate(90deg); /* Firefox */
-webkit-transform:rotate(90deg); /* Safari 和 Chrome */
-o-transform:rotate(90deg); /* Opera */
}
#angleimgbottomright{
	transform:rotate(180deg);
-ms-transform:rotate(180deg); /* Internet Explorer */
-moz-transform:rotate(180deg); /* Firefox */
-webkit-transform:rotate(180deg); /* Safari 和 Chrome */
-o-transform:rotate(180deg); /* Opera */
}
#angleimgbottomleft{
	transform:rotate(270deg);
-ms-transform:rotate(270deg); /* Internet Explorer */
-moz-transform:rotate(270deg); /* Firefox */
-webkit-transform:rotate(270deg); /* Safari 和 Chrome */
-o-transform:rotate(270deg); /* Opera */
}
</style>


<img class="angleimg" style="float: left;width:50px;" src="/decorativeimg/angleimg2.png">  <img class="angleimg" id="angleimgtopright" style="float: right;width:50px;" src="/decorativeimg/angleimg2.png"> 
<table class="table table-striped">
  <caption>条纹表格布局</caption>
  <thead>
    <tr>
      <th>名称</th>
      <th>城市</th>
      <th>邮编</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Tanmay</td>
      <td>Bangalore</td>
      <td>560001</td>
    </tr>
    <tr>
      <td>Sachin</td>
      <td>Mumbai</td>
      <td>400003</td>
    </tr>
    <tr>
      <td>Uma</td>
      <td>Pune</td>
      <td>411027</td>
    </tr>
  </tbody>
</table>
<img class="angleimg" id="angleimgbottomleft" style="float: left;width:50px;" src="/decorativeimg/angleimg1.png">  <img class="angleimg" id="angleimgbottomright" style="float: right;width:50px;" src="/decorativeimg/angleimg1.png"> 