 <div class="input-group input-group-sm" style="background-color:white;padding: 5px;z-index:10;position:absolute;text-align:center;" id="searchcolumn">
      <div class="input-group-btn"  onclick="location='<?php echo $this->url('customer', array('action'=>'cosmetologist'));?>';">
       <a href="#" class="button white mediumbutton"><span class="glyphicon glyphicon-chevron-left"></span></a>
      </div>
      <div style="float: right;"  onclick="location='<?php echo $this->url('customer', array('action'=>'chathistory','sub'=>$sub));?>';">
      <a href="#" class="button green mediumbutton"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span></a>
      </div>
 </div>






<style>
#angleimgtopright{
	transform:rotate(90deg);
-ms-transform:rotate(90deg); /* Internet Explorer */
-moz-transform:rotate(90deg); /* Firefox */
-webkit-transform:rotate(90deg); /* Safari 和 Chrome */
-o-transform:rotate(90deg); /* Opera */
}
#angleimgbottomright{
	transform:rotate(180deg);
-ms-transform:rotate(180deg); /* Internet Explorer */
-moz-transform:rotate(180deg); /* Firefox */
-webkit-transform:rotate(180deg); /* Safari 和 Chrome */
-o-transform:rotate(180deg); /* Opera */
}
#angleimgbottomleft{
	transform:rotate(270deg);
-ms-transform:rotate(270deg); /* Internet Explorer */
-moz-transform:rotate(270deg); /* Firefox */
-webkit-transform:rotate(270deg); /* Safari 和 Chrome */
-o-transform:rotate(270deg); /* Opera */
}
</style>


<img class="angleimg" style="float: left;width:50px;" src="/decorativeimg/angleimg2.png">  <img class="angleimg" id="angleimgtopright" style="float: right;width:50px;" src="/decorativeimg/angleimg2.png"> 
<table class="table table-striped">
  <caption>条纹表格布局</caption>
  <thead>
    <tr>
      <th>名称</th>
      <th>城市</th>
      <th>邮编</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Tanmay</td>
      <td>Bangalore</td>
      <td>560001</td>
    </tr>
    <tr>
      <td>Sachin</td>
      <td>Mumbai</td>
      <td>400003</td>
    </tr>
    <tr>
      <td>Uma</td>
      <td>Pune</td>
      <td>411027</td>
    </tr>
  </tbody>
</table>
<img class="angleimg" id="angleimgbottomleft" style="float: left;width:50px;" src="/decorativeimg/angleimg1.png">  <img class="angleimg" id="angleimgbottomright" style="float: right;width:50px;" src="/decorativeimg/angleimg1.png"> 