<div class="well" style="text-align:center"><?php echo $homepage->getPageheaddata2();?></div>

<div style="text-align:center">
<img src="<?php echo $homepage->getPageheaddata1();?>" style="height:100px;width:120px;">
</div>


<?php
$form = $this->form;
$form->setAttribute('action', $this->url('customer', array(
    'action' => 'login','sub'=>$sub
)));
$form->get('submit')->setAttribute('value', '登陆');
$form->prepare();
echo $this->form()->openTag($form);?>
<fieldset>
    <legend>账号登陆</legend>
    <label for="name" style="color:red;"><?php echo $result;?></label>
	<div class="form-group">
    <label for="name">手机号</label>
    <?php echo $this->formRow($form->get('cusphone'));?>
    </div>
    <div class="form-group">
    <label for="name">密码</label>
    <?php echo $this->formRow($form->get('cuspassword'));?>
    </div>
    <div class="form-group" style="text-align:center">
    <?php echo $this->formInput($form->get('submit')); ?>
    </div>
</fieldset>
<?php echo $this->form()->closeTag($form);?>
<button type="button" class="btn btn-default btn-lg btn-block" onclick="location='<?php echo $this->url('customer', array('action'=>'register','sub'=>$sub));?>'">注册</button>
