<link rel="stylesheet" href="/css/zoomify.css">
<script src="/js/zoomify.js"></script>

 <style>
.angleimg{width:50px;z-index:100;}
#angleimgtopright{
	transform:rotate(90deg);
-ms-transform:rotate(90deg); /* Internet Explorer */
-moz-transform:rotate(90deg); /* Firefox */
-webkit-transform:rotate(90deg); /* Safari 和 Chrome */
-o-transform:rotate(90deg); /* Opera */
}
#angleimgbottomright{
	transform:rotate(180deg);
-ms-transform:rotate(180deg); /* Internet Explorer */
-moz-transform:rotate(180deg); /* Firefox */
-webkit-transform:rotate(180deg); /* Safari 和 Chrome */
-o-transform:rotate(180deg); /* Opera */
}
#angleimgbottomleft{
	transform:rotate(270deg);
-ms-transform:rotate(270deg); /* Internet Explorer */
-moz-transform:rotate(270deg); /* Firefox */
-webkit-transform:rotate(270deg); /* Safari 和 Chrome */
-o-transform:rotate(270deg); /* Opera */
}
</style>


 <div class="input-group input-group-sm" style="background-color:white;padding: 5px;z-index:10;position:fixed;text-align:center;" id="searchcolumn">
      <span class="input-group-btn" onclick="window.history.back();">
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
      <span>
      <img alt="" style="height:20px;" src="/meicon/myprize.png">&nbsp;&nbsp;我的奖品
      </span>
 </div>
<!-- 没有作用，只为平衡高度 -->
<div class="input-group input-group-sm" style="visibility:hidden;padding: 5px;" >
      <span class="input-group-btn" >
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
      <span onclick="window.history.back();">
      </span>
 </div>


<div style="text-align: center;">
<img class="angleimg" style="float: left;" src="/decorativeimg/angleimg1.png">  
<img class="angleimg" id="angleimgtopright" style="float: right;" src="/decorativeimg/angleimg1.png"> 
  <div>实物奖品请在到店领取后点击确认领取</div>
</div>



<table class="table table-striped">
  <thead>
    <tr>
    <th>&nbsp;</th>
      <th>时间</th>
      <th>奖品</th>
      <th>状态</th></tr>
  </thead>
  <tbody>
  <?php foreach ($lotteryhistory as $lotteyprize):?>
  <?php if ($lotteyprize->getPrizepicture()!=="/img/thanksforyou.jpg"):?>
    <tr>
    <td><img alt="" src="/decorativeimg/prizeicon.png" style="height:30px;"></td>
      <td><?php echo date("Y-m-d H:i:s",$lotteyprize->getWinningtime());?></td>
      <td><img class="lotterypicture" alt="奖品" src="<?php echo $lotteyprize->getPrizepicture();?>" style="height:50px;width:50px;"></td>
    <?php if ($lotteyprize->getReceivestate()):?>
    <td><button type="button" class="btn btn-default" disabled="disabled">已经领取</button></td>
    <?php else :?>
     <td><button onclick='$.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'lotterygetajax'));?>",dataType:"text",data:"lotteryid=<?php echo $lotteyprize->getId();?>",type:"POST",success:function(result){}});
         $(this).html("已经领取");$(this).attr("disabled","disabled");$(this).removeClass("btn btn-success");$(this).addClass("btn btn-default");' type="button" class="btn btn-success">确认领取</button></td>
     <?php endif;?>
      </tr>
      <?php endif;?>
      <?php endforeach;?>
  </tbody>
</table>

<script type="text/javascript">
//图片点击放大
	$('.lotterypicture').zoomify();
</script>