<style>
.menubottom{
	z-index:100;
	position:fixed;
	bottom:0px;
	background-color:<?php echo $homepage->getPagecolor();?>;
	}
#mehead {
     background: -webkit-linear-gradient(<?php echo $homepage->getPagecolor();?>, white); /* Safari 5.1 - 6.0 */ 
     background: -o-linear-gradient(<?php echo $homepage->getPagecolor();?>, white); /* Opera 11.1 - 12.0 */ 
     background: -moz-linear-gradient(<?php echo $homepage->getPagecolor();?>, white); /* Firefox 3.6 - 15 */ 
     background: linear-gradient(<?php echo $homepage->getPagecolor();?>,white); /* 标准的语法（必须放在最后） */
}
.bottom-btn{
	border-right:0.1px solid rgba(0, 0, 0, 0.0980392);
	border-top:0.1px solid rgba(0, 0, 0, 0.0980392);
}
.bottom-btn-me{
	border-top:0.1px solid rgba(0, 0, 0, 0.0980392);
}
</style>


<div style="text-align:center" id="mehead">
<img src="/portrait/<?php echo $customer->getCusphoto();?>" class="img-circle" style="width:110px;height:120px;padding-top:10px;padding-bottom:10px;">


&nbsp;&nbsp;&nbsp;
<button style="border-radius: 25px;" type="button" class="button black bigrounded"onclick="location='<?php echo $this->url('customer',
             array('action'=>'login', 'sub'=>$id));?>'"><span class="glyphicon glyphicon-repeat" aria-hidden="true"></span>&nbsp;&nbsp;登陆</button>
<button style="border-radius: 25px;" type="button" class="button black bigrounded"onclick="location='<?php echo $this->url('customer',
             array('action'=>'cusdetail'));?>'"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span>&nbsp;&nbsp;设置</button>
</div>          
   
   
   
<div class="well" style="font-size: 20px;"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp;&nbsp;我的订单</div>
 <div class="row">
      <div class="col-xs-6 col-sm-6" onclick="location='<?php echo $this->url('customer', array('action'=>'myorders','sub'=>'paid'));?>';">
      <button type="button" class="button gray btnshadow" style="width: 100%;"><img alt="" style="height:20px;" src="/meicon/meicon1.png">&nbsp;&nbsp;已付款</button>
      </div>
      <div class="col-xs-6 col-sm-6" onclick="location='<?php echo $this->url('customer', array('action'=>'myorders','sub'=>'unpaid'));?>';">
      <button type="button" class="button gray btnshadow" style="width: 100%;"><img alt="" style="height:20px;" src="/meicon/meicon2.png">&nbsp;&nbsp;未付款</button>
      </div>      
 </div>



<div class="well" style="font-size: 20px;"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>&nbsp;&nbsp;我的预约</div>
 <div class="row">
      <div class="col-xs-6 col-sm-6" onclick="location='<?php echo $this->url('customer', array('action'=>'myappointments','sub'=>'unexpired'));?>';">
      <button type="button" class="button gray btnshadow" style="width: 100%;"><img alt="" style="height:20px;" src="/meicon/meicon3.png">&nbsp;&nbsp;未到期</button>
      </div>
      <div class="col-xs-6 col-sm-6" onclick="location='<?php echo $this->url('customer', array('action'=>'myappointments','sub'=>'expired'));?>';">
      <button type="button" class="button gray btnshadow" style="width: 100%;"><img alt="" style="height:20px;" src="/meicon/meicon4.png">&nbsp;&nbsp;已过期</button>
      </div>
 </div>



<div class="well" style="font-size: 20px;"><span class="glyphicon glyphicon-gift" aria-hidden="true"></span>&nbsp;&nbsp;我的活动</div>
 <div class="row">
      <div class="col-xs-6 col-sm-6" onclick="location='<?php echo $this->url('customer', array('action'=>'myactivities','sub'=>'registered'));?>';">
      <button type="button" class="button gray btnshadow" style="width: 100%;"><img alt="" style="height:20px;" src="/meicon/meicon5.png">&nbsp;&nbsp;已参加</button>
      </div>
      <div class="col-xs-6 col-sm-6" onclick="location='<?php echo $this->url('customer', array('action'=>'myactivities','sub'=>'unregistered'));?>';">
      <button type="button" class="button gray btnshadow" style="width: 100%;"><img alt="" style="height:20px;" src="/meicon/meicon6.png">&nbsp;&nbsp;未参加</button>
      </div>      
 </div>



<hr>
<div class="row">
      <div class="col-xs-6 col-sm-6">
     <button type="button" class="button white btnshadow" onclick="location='<?php echo $this->url('customer',
             array('action'=>'trolley'));?>';" style="width: 100%;"><img alt="" style="height:20px;" src="/meicon/mytrolley.png">&nbsp;&nbsp;购物车</button>
      </div>
      <div class="col-xs-6 col-sm-6">
           <button type="button" class="button white btnshadow" onclick="location='<?php echo $this->url('customer',
             array('action'=>'mycoupon'));?>';" style="width: 100%;"><img alt="" style="height:20px;" src="/meicon/mycoupon.png">&nbsp;&nbsp;优惠券</button>
      </div>      
 </div>

<br>
<div class="row">
      <div class="col-xs-6 col-sm-6">
     <button type="button" class="button white btnshadow" onclick="location='<?php echo $this->url('customer',
             array('action'=>'lotteryprize'));?>';" style="width: 100%;"><img alt="" style="height:20px;" src="/meicon/myprize.png">&nbsp;&nbsp;我的奖品</button>
      </div>
      <div class="col-xs-6 col-sm-6">
     <button type="button" class="button white btnshadow" onclick="location='<?php echo $this->url('customer',
             array('action'=>'mytiplist'));?>';" style="width: 100%;"><img alt="" style="height:20px;" src="/meicon/mytip.png">&nbsp;&nbsp;我的打赏</button>
      </div>      
 </div>

<hr>
<div class="row" style="text-align: center;">
<a href="#" onclick="shareapp()">
             <span class="glyphicon glyphicon-share" aria-hidden="true"></span>&nbsp;分享应用</a>
             &nbsp;&nbsp;&nbsp;<a href="<?php echo $this->url('customer',
             array('action'=>'suggestioncus'));?>">
             <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;意见与建议</a>
</div>
<div class="row" style="text-align: center;">
Copyright @2018-2022
</div>

<script>
function shareapp(){
	var u = navigator.userAgent;
	var isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1; //android终端
	var isiOS = !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/); //ios终端
    if(isAndroid){
        //加引号就是字符串
    	window.android.shareapp("<?php echo $account->getSalname();?>线上app下载地址：https://www.oushelun.cn/cosmeticlogin/appdownload/<?php echo $id;?>/androidcustomer");
        }
    if(isiOS){
        window.webkit.messageHandlers.iosshareapp.postMessage("<?php echo $account->getSalname();?>线上app下载地址：https://www.oushelun.cn/cosmeticlogin/appdownload/<?php echo $id;?>/ioscustomer");
            }
}
</script>              
<?php //TODO 底部菜单栏  用于站位?>
<div class="btn-group btn-group-justified" role="group" style="visibility:hidden">
  <div class="btn-group" role="group" style="text-align:center;" >
  <span class="glyphicon glyphicon-home" style="font-size:25px;color:red;" aria-hidden="true"></span>
  <div style="color:red;">首页</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-time" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>预约</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-edit" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>咨询</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-user" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>我</div>
  </div>
</div>

<?php //TODO 底部菜单栏?>
<div class="btn-group btn-group-justified menubottom" role="group" >
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" onclick="location='<?php echo $this->url('customer', array('action'=>'homepage','sub'=>$id));?>';">
  <span class="glyphicon glyphicon-home" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>首页</div>
  </div>
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" onclick="location='<?php echo $this->url('customer', array('action'=>'appointment'));?>';">
  <span class="glyphicon glyphicon-time" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>预约</div>
  </div>
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" onclick="location='<?php echo $this->url('customer', array('action'=>'cosmetologist'));?>';">
  <span class="glyphicon glyphicon-comment" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>咨询&nbsp;
  <?php if($unreadsum){?>
  <span  class="badge" style="background-color:red;"><?php echo $unreadsum;?></span>
  <?php }?>
  </div>
  </div>
  <div class="btn-group bottom-btn-me" role="group" style="text-align:center;" onclick="location='<?php echo $this->url('customer', array('action'=>'me'));?>';">
  <span class="glyphicon glyphicon-user" style="font-size:25px;color:red;" aria-hidden="true"></span>
  <div style="color:red;">我</div>
  </div>
</div>

