 <style>
.angleimg{width:50px;z-index:100;}
#angleimgtopright{
	transform:rotate(90deg);
-ms-transform:rotate(90deg); /* Internet Explorer */
-moz-transform:rotate(90deg); /* Firefox */
-webkit-transform:rotate(90deg); /* Safari 和 Chrome */
-o-transform:rotate(90deg); /* Opera */
}
#angleimgbottomright{
	transform:rotate(180deg);
-ms-transform:rotate(180deg); /* Internet Explorer */
-moz-transform:rotate(180deg); /* Firefox */
-webkit-transform:rotate(180deg); /* Safari 和 Chrome */
-o-transform:rotate(180deg); /* Opera */
}
#angleimgbottomleft{
	transform:rotate(270deg);
-ms-transform:rotate(270deg); /* Internet Explorer */
-moz-transform:rotate(270deg); /* Firefox */
-webkit-transform:rotate(270deg); /* Safari 和 Chrome */
-o-transform:rotate(270deg); /* Opera */
}
</style>
 
 
 <div class="input-group input-group-sm" style="background-color:white;padding: 5px;z-index:10;position:fixed;text-align:center;" id="searchcolumn">
      <span class="input-group-btn" onclick="location='<?php echo $this->url('customer', array('action'=>'me'));?>';">
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
      <span>
     <img alt="" style="height:20px;" src="/meicon/mytip.png">&nbsp;&nbsp;打赏记录
      </span>
 </div>
<!-- 没有作用，只为平衡高度 -->
<div class="input-group input-group-sm" style="visibility:hidden;padding: 5px;" >
      <span class="input-group-btn" >
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
      <span>
      打赏记录
      </span>
 </div>

<div style="text-align: center;">
<img class="angleimg" style="float: left;" src="/decorativeimg/angleimg1.png">  
<img class="angleimg" id="angleimgtopright" style="float: right;" src="/decorativeimg/angleimg1.png"> 
  <div>打赏总金额：<span style="color:red;"><?php echo $customer->getTipsum();?>元</span></div>
  <div>打赏总次数：<span style="color:red;"><?php echo $customer->getTiptimes();?>次</span></div>
</div>


<table class="table table-striped">
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>日期</th>
      <th>美容师</th>
      <th>金额</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($tiplist as $tip):?>
    <tr>
    <td><img alt="" src="/decorativeimg/medalicon.png" style="height:30px;"></td>
      <td><?php echo date("Y-m-d H:i:s",strtotime($tip->getGmtclose()))?></td>
      <td><?php echo $tip->getCosname();?></td>
      <td><span style="color:red;"><?php echo $tip->getTipmoney();?>元</span></td>
    </tr>
    <?php endforeach;?>
  </tbody>
</table>
<img class="angleimg" id="angleimgbottomleft" style="float: left;" src="/decorativeimg/angleimg1.png">  <img class="angleimg" id="angleimgbottomright" style="float: right;" src="/decorativeimg/angleimg1.png">