<?php //开关按钮?>
<style>
#switchdiv1{
        width: 65px;
        height: 40px;
        border-radius: 50px;
        position: relative;
    }
    #switchdiv2{
        width: 35px;
        height: 35px;
        border-radius: 48px;
        position: absolute;
        background: white;
        box-shadow: 0px 2px 4px rgba(0,0,0,0.4);
    }
    .open1{
        background: rgba(0,184,0,0.8);
    }
    .open2{
        top: 2px;
        right: 1px;
    }
    .close1{
        background: rgba(255,255,255,0.4);
        border:3px solid rgba(0,0,0,0.15);
        border-left: transparent;
    }
    .close2{
        left: 0px;
        top: 0px;
        border:2px solid rgba(0,0,0,0.1);
    }
    </style>

<?php  //TODO 提交订单?>
<script type="text/javascript">
$(document).ready(function(){
	$('#ordersubmit').click(function(){
		//判断是支付宝还是微信
		if($('input:radio[name="paymethod"]:checked').val()=="alipay"){
		$.ajax({url:"<?php echo $this->url('customer', array('action'=>'payment'));?>",dataType:"text",
			data:{prodid:'<?php echo $_POST['prodid'];?>',productcombinationid:'<?php echo $_POST['productcombinationid'];?>',
				treprice:$("#total").html(),treremark:$("#treremark").val(),
				productquantity:$("#productquantity").val(),couponidused:$('option:checked').attr("data-id"),
				cuspointsused:$("#cuspoints").attr("data-used"),
				productcombinationname:'<?php echo $_POST['productcombinationname'];?>',
				prodtitle:'<?php echo $_POST['prodtitle'];?>',
				prodsalnumber:'<?php echo $_POST['prodsalnumber'];?>',
				productcombinationpicture:'<?php echo $_POST['productcombinationpicture'];?>'}
		,type:"POST",
			success:function(result){
				$("#div1").html(result);
				location="<?php echo $this->url('customer', array('action'=>'me'));?>";
				//setTimeout(function () { 延迟跳转用户多次点击提交订单会生成多个订单
					// location="<?php // echo $this->url('customer', array('action'=>'me'));?>";
					 //}, 3000);
				
		}});
		}
		if($('input:radio[name="paymethod"]:checked').val()=="wechat"){
            alert("微信支付");
			}
		
		})
})
</script>
<div id="div1" style="display: none;"></div>
<?php //确认订单按钮?>
 <div class="input-group input-group-sm" style="padding: 5px; position:fixed" id="searchcolumn">
      <span class="input-group-btn" onclick="history.go(-1)">
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
       &nbsp;&nbsp;&nbsp;&nbsp;
      <span style="font-size:larger;">订单</span>
 </div>
 
 <?php //确认订单按钮，仅占位?>
  <div class="input-group input-group-sm" style="padding: 5px;visibility:hidden;">
      <span class="input-group-btn" onclick="history.go(-1)">
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
      <span>订单</span>
 </div>

<?php //TODO 数量选择器?>
<script type="text/javascript" src="/js/num-alignment.js"></script>
<script type="text/javascript">
$(document).ready(function () {
	$('#productquantity').val("<?php echo $_POST['productquantity'];?>");
});
</script>
<style>
.well {
	margin:5px;
}
</style>

<?php //TODO 总价的改变?>
<script type="text/javascript">
$(document).ready(function(){
	/*直接改变价格，否则支付宝会出现:
	暂时无法获取订单信息，请稍后再试
	的情况，应该是直接传递过去的价格格式问题
	*/
	$("#total").html(<?php echo $_POST['productcombinationprice']*$_POST['productquantity'];?>);//总价默认值
	//默认积分值
	if(<?php echo $cuspointssingle;?>*$("#productquantity").val() > <?php echo $cusleveltype->getCuspoints();?>){
        $("#cuspoints").html(<?php echo $cusleveltype->getCuspoints();?>);
		}else{
		$("#cuspoints").html(<?php echo $cuspointssingle;?>*$("#productquantity").val());
		}
	//积分变化
	  $("#switchdiv2").click(function(){
          $("#switchdiv1").attr("class",($("#switchdiv1").attr("class")=="close1")?"open1":"close1");
          $("#switchdiv2").attr("class",($("#switchdiv2").attr("class")=="close2")?"open2":"close2");
          if($("#switchdiv1").attr("class")=="close1"){
              $("#cuspoints").attr("data-used",0);
        	  $("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val()-$('option:checked').val());
          }else{
        	  $("#cuspoints").attr("data-used",$("#cuspoints").html());
        	  $("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val()-$('option:checked').val()-$("#cuspoints").html());
               }
           })
	//数量改变时
	$("#productquantityl").click(function(){
		if(<?php echo $cuspointssingle;?>*$("#productquantity").val() > <?php echo $cusleveltype->getCuspoints();?>){
            $("#cuspoints").html(<?php echo $cusleveltype->getCuspoints();?>);
			}else{
			$("#cuspoints").html(<?php echo $cuspointssingle;?>*$("#productquantity").val());
			}
	    if($("#switchdiv1").attr("class")=="close1"){
	    	$("#cuspoints").attr("data-used",0);
			$("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val()-$('option:checked').val());
       }else{
    	   $("#cuspoints").attr("data-used",$("#cuspoints").html());
			$("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val()-$('option:checked').val()-$("#cuspoints").html());
            }
    	});
	$("#productquantityr").click(function(){
		if(<?php echo $cuspointssingle;?>*$("#productquantity").val() > <?php echo $cusleveltype->getCuspoints();?>){
            $("#cuspoints").html(<?php echo $cusleveltype->getCuspoints();?>);
			}else{
			$("#cuspoints").html(<?php echo $cuspointssingle;?>*$("#productquantity").val());
			}
	    if($("#switchdiv1").attr("class")=="close1"){
	    	$("#cuspoints").attr("data-used",0);
			$("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val()-$('option:checked').val());
       }else{
    	   $("#cuspoints").attr("data-used",$("#cuspoints").html());
			$("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val()-$('option:checked').val()-$("#cuspoints").html());
            }
	});
	//优惠券改变时
	$('select').change(function(){
		if($("#switchdiv1").attr("class")=="close1"){
			$("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val()-$('option:checked').val());
       }else{
    	   $("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val()-$('option:checked').val()-$("#cuspoints").html());
            }
		});
})
</script>

<div class="container">
<div class="well">
	
		<div class="row">
			<div class="col-xs-4 col-sm-4">
				<img alt="" src="<?php echo $_POST['productcombinationpicture'];?>" style="width:100%">
			</div>
			<div class="col-xs-8 col-sm-8" style="padding:10px">
				<div class="row" style="font-size: large;">
				<?php echo $_POST['prodtitle'];?>
				</div>
				<div class="row" style="font-size: small;">
				<?php echo $_POST['productcombinationname'];?>
				</div>
				<div class="row" style="color:red">
				¥
				<?php echo $_POST['productcombinationprice'];?>
				</div>
				 
			</div>
		</div>
	
</div>

 <div class="row well">
						<div class="col-xs-7 col-sm-7">数量</div>
						<div class="col-xs-5 col-sm-5">
							<input id="productquantity" data_step="1" data_min="1" data_max="99" data_digit="0" value="3"/>
						</div>
</div>
			     
<div class="row well">
<div class="col-xs-7 col-sm-7">优惠券</div>
<div class="col-xs-5 col-sm-5">

<select class="form-control" name="couponmoney">
<?php if ($coupongetarray):?>
<option value="0">
选择优惠券
</option>
<?php else :?>
<option value="0">
没有优惠券
</option>
<?php endif;?>
<?php foreach ($coupongetarray as $couponget):?>
<?php if ($couponget):?>
<option data-id="<?php echo $couponget->getScgid();?>" value="<?php echo $couponget->getScimoney();?>">
立减 &nbsp; &nbsp;<?php echo $couponget->getScimoney();?>元
</option>
<?php endif;?>
<?php endforeach;?>	
</select>
	
</div>
</div>


 <div class="row well">
						<div class="col-xs-7 col-sm-7">
						<div>积分抵用<span id="cuspoints" data-used="0"></span>元</div>
						<div style="font-size:80%;color:#708090;">（拥有<?php echo $cusleveltype->getCuspoints();?>积分）</div>
						</div>
						<div class="col-xs-5 col-sm-5">
							   <div id="switchdiv1" class="close1">
                                  <div id="switchdiv2" class="close2"></div>
                               </div>
						</div>
</div>



<div class="row well">
<div class="col-xs-7 col-sm-7">支付方式</div>
<div class="col-xs-5 col-sm-5">
<div class="radio">
	<label>
		<input type="radio" name="paymethod" checked value="alipay" />
		<img alt="支付宝" style="height: 30px;" src="/img/alipay.png">
	</label>
</div>
<div class="radio">
	<label>
		<input type="radio" name="paymethod"  value="wechat"/>
		<img alt="微信" style="height: 30px;"  src="/img/wechat.png">
	</label>
</div>	
</div>
</div>



<div class="row well">
<div class="col-xs-2 col-sm-2">备注</div>
<div class="col-xs-10 col-sm-10">
<div class="form-group">
    <input type="text" class="form-control" id="treremark" placeholder="给美容院留言">
  </div>	
</div>
</div>





<?php  //TODO 占位用?>
<div class="container" style="width:100%;border:1px solid gray; visibility:hidden;">
 <div class="row">
		<div class="col-xs-8 col-sm-8">
		<div style="float:right;color:red;padding-top:20px;padding-right:20px;font-size:larger;">
		<span>合计：¥&nbsp;&nbsp;</span>
		<span>
		<?php echo $_POST['productcombinationprice']*$_POST['productquantity'];?>
		</span>
		</div>
		</div>
	    <div class="col-xs-4 col-sm-4">
				<button type="button" class="btn btn-default btn-lg btn-block">提交订单</button>
	    </div>
</div>
</div>
</div>



<?php  //TODO 底部总价和提交表单?>
<div class="container" style="position: fixed;bottom:0px;width:100%;border:1px solid gray;background-color:white;">
 <div class="row">
		<div class="col-xs-8 col-sm-8">
		<div style="float:right;color:red;padding-top:20px;padding-right:20px;font-size:larger;">
		<span>合计：¥&nbsp;&nbsp;</span>
		<span id="total">
		<?php echo $_POST['productcombinationprice']*$_POST['productquantity'];?>
		</span>
		</div>
		</div>
	    <div class="col-xs-4 col-sm-4">
				<button type="button" id="ordersubmit" class="btn btn-default btn-lg btn-block">提交订单</button>
	    </div>
</div>
</div>

<script type="text/javascript">
$(".decrease").addClass("btn");
</script>