<?php  //TODO 提交订单?>
<script type="text/javascript">
$(document).ready(function(){
	$('#ordersubmit').click(function(){
		//判断是支付宝还是微信
		if($('input:radio[name="paymethod"]:checked').val()=="alipay"){
		$.ajax({url:"<?php echo $this->url('customer', array('action'=>'payment'));?>",dataType:"text",
			data:{prodid:'<?php echo $_POST['prodid'];?>',productcombinationid:'<?php echo $_POST['productcombinationid'];?>',
				treprice:$("#total").html(),treremark:$("#treremark").val(),
				productquantity:$("#productquantity").val(),couponidused:$('option:checked').attr("data-id"),
				productcombinationname:'<?php echo $_POST['productcombinationname'];?>',
				prodtitle:'<?php echo $_POST['prodtitle'];?>',
				prodsalnumber:'<?php echo $_POST['prodsalnumber'];?>',
				productcombinationpicture:'<?php echo $_POST['productcombinationpicture'];?>'}
		,type:"POST",
			success:function(result){
				$("#div1").html(result);
				location="<?php echo $this->url('customer', array('action'=>'me'));?>";
				//setTimeout(function () { 延迟跳转用户多次点击提交订单会生成多个订单
					// location="<?php // echo $this->url('customer', array('action'=>'me'));?>";
					 //}, 3000);
				
		}});
		}
		if($('input:radio[name="paymethod"]:checked').val()=="wechat"){
            alert("微信支付");
			}
		
		})
})
</script>
<div id="div1" style="display: none;"></div>
<?php //确认订单按钮?>
 <div class="input-group input-group-sm" style="padding: 5px; position:fixed" id="searchcolumn">
      <span class="input-group-btn" onclick="history.go(-1)">
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
       &nbsp;&nbsp;&nbsp;&nbsp;
      <span style="font-size:larger;">订单</span>
 </div>
 
 <?php //确认订单按钮，仅占位?>
  <div class="input-group input-group-sm" style="padding: 5px;visibility:hidden;">
      <span class="input-group-btn" onclick="history.go(-1)">
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
      <span>订单</span>
 </div>

<?php //TODO 数量选择器?>
<script type="text/javascript" src="/spinner/jquery.spinner.js"></script>
<link href="/soinner/jquery.spinner.css" media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript">
$(document).ready(function () {
	$('.spinner').spinner(
			defaults = {value:<?php echo $_POST['productquantity'];?>, min:1}
			); 
});
</script>
<style>
.well {
	margin:5px;
}
</style>

<?php //TODO 总价的改变?>
<script type="text/javascript">
$(document).ready(function(){
	/*直接改变价格，否则支付宝会出现:
	暂时无法获取订单信息，请稍后再试
	的情况，应该是直接传递过去的价格格式问题
	*/
	$("#total").html(<?php echo $_POST['productcombinationprice']*$_POST['productquantity'];?>);
	//数量改变时
	$("#productquantity").change(function(){
		if($('option:checked').val()==null){
          $("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val());
		}else{
			$("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val()-$('option:checked').val());
			}
    	});
	$(".increase").click(function(){
		if($('option:checked').val()==null){
	          $("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val());
			}else{
				$("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val()-$('option:checked').val());
			}
		 });
	$(".decrease").click(function(){
		if($('option:checked').val()==null){
	          $("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val());
			}else{
				$("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val()-$('option:checked').val());
			}
		 });
	//优惠券改变时
	$('select').change(function(){
		$("#total").html(<?php echo $_POST['productcombinationprice'];?>*$("#productquantity").val()-$('option:checked').val());
		});
})
</script>

<div class="container">
<div class="well">
	
		<div class="row">
			<div class="col-xs-4 col-sm-4">
				<img alt="" src="<?php echo $_POST['productcombinationpicture'];?>" style="width:100%">
			</div>
			<div class="col-xs-8 col-sm-8" style="padding:10px">
				<div class="row" style="font-size: large;">
				<?php echo $_POST['prodtitle'];?>
				</div>
				<div class="row" style="font-size: small;">
				<?php echo $_POST['productcombinationname'];?>
				</div>
				<div class="row" style="color:red">
				¥
				<?php echo $_POST['productcombinationprice'];?>
				</div>
				 
			</div>
		</div>
	
</div>

 <div class="row well">
						<div class="col-xs-8 col-sm-8">数量</div>
						<div class="col-xs-4 col-sm-4">
							<input type="text" class="spinner" style="width: 30px" id="productquantity" />
						</div>
</div>
			     
<div class="row well">
<div class="col-xs-8 col-sm-8">优惠券</div>
<div class="col-xs-4 col-sm-4">

<select name="couponmoney">
<?php if ($coupongetarray):?>
<option value="0">
选择优惠券
</option>
<?php else :?>
<option value="0">
没有优惠券
</option>
<?php endif;?>
<?php foreach ($coupongetarray as $couponget):?>
<?php if ($couponget):?>
<option data-id="<?php echo $couponget->getScgid();?>" value="<?php echo $couponget->getScimoney();?>">
立减 &nbsp; &nbsp;<?php echo $couponget->getScimoney();?>元
</option>
<?php endif;?>
<?php endforeach;?>	
</select>
	
</div>
</div>


<div class="row well">
<div class="col-xs-8 col-sm-8">支付方式</div>
<div class="col-xs-4 col-sm-4">
<div class="radio">
	<label>
		<input type="radio" name="paymethod" checked value="alipay" />支付宝
	</label>
</div>
<div class="radio">
	<label>
		<input type="radio" name="paymethod"  value="wechat"/>微信
	</label>
</div>	
</div>
</div>



<div class="row well">
<div class="col-xs-2 col-sm-2">备注</div>
<div class="col-xs-10 col-sm-10">
<div class="form-group">
    <input type="text" class="form-control" id="treremark" placeholder="给美容院留言">
  </div>	
</div>
</div>

<?php  //TODO 占位用?>
<div class="container" style="width:100%;border:1px solid gray; visibility:hidden;">
 <div class="row">
		<div class="col-xs-8 col-sm-8">
		<div style="float:right;color:red;padding-top:20px;padding-right:20px;font-size:larger;">
		<span>合计：¥&nbsp;&nbsp;</span>
		<span>
		<?php echo $_POST['productcombinationprice']*$_POST['productquantity'];?>
		</span>
		</div>
		</div>
	    <div class="col-xs-4 col-sm-4">
				<button type="button" class="btn btn-default btn-lg btn-block">提交订单</button>
	    </div>
</div>
</div>
</div>



<?php  //TODO 底部总价和提交表单?>
<div class="container" style="position: fixed;bottom:0px;width:100%;border:1px solid gray;background-color:white;">
 <div class="row">
		<div class="col-xs-8 col-sm-8">
		<div style="float:right;color:red;padding-top:20px;padding-right:20px;font-size:larger;">
		<span>合计：¥&nbsp;&nbsp;</span>
		<span id="total">
		<?php echo $_POST['productcombinationprice']*$_POST['productquantity'];?>
		</span>
		</div>
		</div>
	    <div class="col-xs-4 col-sm-4">
				<button type="button" id="ordersubmit" class="btn btn-default btn-lg btn-block">提交订单</button>
	    </div>
</div>
</div>

