<style>
.producttitle {
height:46px;
font-size:120%;
text-overflow: -o-ellipsis-lastline;
overflow: hidden;
text-overflow: ellipsis;
display: -webkit-box;
-webkit-line-clamp: 2;
-webkit-box-orient: vertical;
}
.productdisplay{
	padding:5px;
    border:3px groove rgba(0, 0, 0, 0.0980392);
	}
</style>
<script>
//疗程下拉加载更多
$(document).ready(function(){
  $prodoffset=0;
  $prodstyle=2;
  $prodtitle="<?php echo $_GET['searching'];?>";
  $.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'homepagetwo'));?>",dataType:"text",data:{prodoffset:0,prodorder:"prodsynthesis",prodtitle:$prodtitle,prodstyle:$prodstyle},type:"POST",success:function(data,status){
      	   $("#homepagetwocontent").append(data);
	}});
  $("#sortsynthesis").addClass("active");
	$("#sortsynthesis").click(function(){
		$prodoffset=0;
		$("#homepagetwocontent").attr("data-order","prodsynthesis");
		$.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'homepagetwo'));?>",dataType:"text",data:{prodoffset:0,prodorder:"prodsynthesis",prodtitle:$prodtitle,prodstyle:$prodstyle},type:"POST",success:function(data,status){
			   $("#homepagetwocontent").html(data);
			}});
		});
	$("#sortpriceup").click(function(){
		$prodoffset=0;
		$("#sortsynthesis").removeClass("active");
		$("#homepagetwocontent").attr("data-order","prodpriceup");
		$.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'homepagetwo'));?>",dataType:"text",data:{prodoffset:0,prodorder:"prodpriceup",prodtitle:$prodtitle,prodstyle:$prodstyle},type:"POST",success:function(data,status){
			   $("#homepagetwocontent").html(data);

			}});
	    });
	$("#sortpricedown").click(function(){
		$prodoffset=0;
		$("#sortsynthesis").removeClass("active");
		$("#homepagetwocontent").attr("data-order","prodpricedown");
		$.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'homepagetwo'));?>",dataType:"text",data:{prodoffset:0,prodorder:"prodpricedown",prodtitle:$prodtitle,prodstyle:$prodstyle},type:"POST",success:function(data,status){
			   $("#homepagetwocontent").html(data);

			}});
		});
	$("#sortsales").click(function(){
		$prodoffset=0;
		$("#sortsynthesis").removeClass("active");
		$("#homepagetwocontent").attr("data-order","prodsales");
		$.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'homepagetwo'));?>",dataType:"text",data:{prodoffset:0,prodorder:"prodsales",prodtitle:$prodtitle,prodstyle:$prodstyle},type:"POST",success:function(data,status){
			   $("#homepagetwocontent").html(data);

			}});
	    });
	$("#sortregdate").click(function(){
		$prodoffset=0;
		$("#sortsynthesis").removeClass("active");
		$("#homepagetwocontent").attr("data-order","prodregdate");
		$.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'homepagetwo'));?>",dataType:"text",data:{prodoffset:0,prodorder:"prodregdate",prodtitle:$prodtitle,prodstyle:$prodstyle},type:"POST",success:function(data,status){
			   $("#homepagetwocontent").html(data);
			}});
	    });
  $(document).scroll(function(){
   if($(window).scrollTop()+$(window).height()>$("#prodfixedstandard").offset().top-100){
	   //判断激活的按钮
	   $prodorder=$("#homepagetwocontent").attr("data-order");
	   $prodoffset=$prodoffset+1;
	   $.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'homepagetwo'));?>",dataType:"text",data:{prodoffset:$prodoffset,prodorder:$prodorder,prodtitle:$prodtitle,prodstyle:$prodstyle},type:"POST",success:function(data,status){
		   $("#homepagetwocontent").append(data);
		}});
   }
  })
  setInterval(function(){$(".prodloading").remove();}, 1000*3);
});
</script>
<script type="text/javascript">
//上滑消失，下滑显示
$(document).ready(function(){
	$("#fixedstandard").css({"height":$("#searchsort").height()});
	$x= $("#fixedstandard").offset().top - $(window).scrollTop();//变化中参考div距离屏幕高度
	$(document).scroll(function(){
		if($x>$("#fixedstandard").offset().top - $(window).scrollTop()){
              $("#searchsort").slideUp("slow");
              $x= $("#fixedstandard").offset().top - $(window).scrollTop();
			}else{
				$("#searchsort").slideDown("slow");
	            $x= $("#fixedstandard").offset().top - $(window).scrollTop();
			}
		});
})
</script>
<?php //TODO homepage2?>
<div id="pagehead">
 <!-- 搜索栏 -->
 <div id="searchsort" style="z-index: 2;position:fixed;">
 <form action="<?php echo $this->url('customer', array('action'=>'productlist'));?>" method="get">
 <div class="input-group input-group-sm" style="padding: 5px;" id="searchcolumn">
      <span class="input-group-btn" onclick="location='<?php echo $this->url('customer', array('action'=>'classify'));?>'">
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
      <input type="text" name="searching" value="<?php echo $_GET['searching'];?>" class="form-control pageheadbtn"  placeholder="Search for...">
      <span class="input-group-btn">
     <input style="border-width:1px;border-style:solid;border-color:#ccc;" type="submit" value="搜" class="btn btn-default pageheadbtn">
      </span>
 </div>
 </form>
<div class="btn-group btn-group-justified"  role="group" id="productsort">
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default" id="sortsynthesis" ><a href="#pagehead">综合</a></button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default"  id="sortpriceup"><a href="#pagehead">价格↑</a></button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default"  id="sortpricedown"><a href="#pagehead">价格↓</a></button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default" id="sortsales"><a href="#pagehead">销量</a></button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default"  id="sortregdate"><a href="#pagehead">新品</a></button>
  </div>
</div>
</div>
<div id="fixedstandard"></div>

<div id="homepagetwocontent" data-order="prodsynthesis">

</div>
<div id="prodfixedstandard"  style="text-align:center;color:#696969;">
</div>