<style>
.producttitle {
height:46px;
font-size:120%;
text-overflow: -o-ellipsis-lastline;
overflow: hidden;
text-overflow: ellipsis;
display: -webkit-box;
-webkit-line-clamp: 2;
-webkit-box-orient: vertical;
}
.productdisplay{
	padding:5px;
    border:3px groove rgba(0, 0, 0, 0.0980392);
	}
</style>
<script>
//排序按钮
$(document).ready(function(){
	$('#prodpriceup').hide();$('#prodpricedown').hide();$('#prodsales').hide();$('#prodregdate').hide();
	$("#sortsynthesis").click(function(){
	    $('.prodsort').hide();$('#prodsynthesis').show();});
	$("#sortpriceup").click(function(){
	    $('.prodsort').hide();$('#prodpriceup').show();});
	$("#sortpricedown").click(function(){
		$('.prodsort').hide();$('#prodpricedown').show();});
	$("#sortsales").click(function(){
	    $('.prodsort').hide();$('#prodsales').show();});
	$("#sortregdate").click(function(){
	    $('.prodsort').hide();$('#prodregdate').show();});
})
</script>
<script type="text/javascript">
//上滑消失，下滑显示
$(document).ready(function(){
	$("#fixedstandard").css({"height":$("#searchsort").height()});
	$x= $("#fixedstandard").offset().top - $(window).scrollTop();//变化中参考div距离屏幕高度
	$(document).scroll(function(){
		if($x>$("#fixedstandard").offset().top - $(window).scrollTop()){
              $("#searchsort").slideUp("slow");
              $x= $("#fixedstandard").offset().top - $(window).scrollTop();
			}else{
				$("#searchsort").slideDown("slow");
	            $x= $("#fixedstandard").offset().top - $(window).scrollTop();
			}
		});
})
</script>
<?php //TODO homepage2?>
<div id="pagehead">
 <!-- 搜索栏 -->
 <div id="searchsort" style="z-index: 2;position:fixed;">
 <form action="<?php echo $this->url('customer', array('action'=>'productlist'));?>" method="get">
 <div class="input-group input-group-sm" style="padding: 5px;" id="searchcolumn">
      <span class="input-group-btn" onclick="location='<?php echo $this->url('customer', array('action'=>'classify'));?>'">
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
      <input type="text" name="searching" class="form-control pageheadbtn"  placeholder="Search for...">
      <span class="input-group-btn">
     <input style="border-width:1px;border-style:solid;border-color:#ccc;" type="submit" value="搜" class="btn btn-default pageheadbtn">
      </span>
 </div>
 </form>
<div class="btn-group btn-group-justified"  role="group" id="productsort">
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default" id="sortsynthesis" ><a href="#pagehead">综合</a></button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default"  id="sortpriceup"><a href="#pagehead">价格↑</a></button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default"  id="sortpricedown"><a href="#pagehead">价格↓</a></button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default" id="sortsales"><a href="#pagehead">销量</a></button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default"  id="sortregdate"><a href="#pagehead">新品</a></button>
  </div>
</div>
</div>
<div id="fixedstandard"></div>
<?php
$homepage2cars=array();
foreach ($products as $product){
    if (preg_match("^".$_GET['classify']."^", $product->getProddemandclassifyseries())) {
        if(preg_match("^".$_GET['searching']."^", $product->getProdtitle())){
array_push($homepage2cars,array("prodid"=>$product->getProdid(),"prodsales"=>$product->getProdsales(),
    "prodtitle"=>$product->getProdtitle(),"prodpicture1"=>$product->getProdpicture1(),
    "prodprice"=>$product->getProdprice(),"prodoriginal"=>$product->getProdoriginal(),
    "prodregdate"=>$product->getProdregdate(),
    "proddiscount"=>$product->getProddiscount()));
    }
    }
}?>

<div id="prodsynthesis" class="prodsort">
 <?php //综合排序
foreach ($homepage2cars as $key => $row) {
$x[$key] = $row['prodprice'];}
if($x){
array_multisort($x, SORT_DESC,$homepage2cars);
}else{?>
    <div id="noproductAlert" style="text-align:center;">
    <div class="alert alert-danger">没有相关产品或服务，请重新输入搜索条件</div>
    </div>
    
    <script type="text/javascript">
    $(document).ready(function(){
    setTimeout(function(){$("#noproductAlert").hide()},3000);
    })
    </script>
<?php }?>
<div class="row" >
<?php foreach ($homepage2cars as $car): ?>
  <div class="col-xs-6 productdisplay" onclick="location='productitem/<?php echo $car["prodid"];?>';">
  <img alt="" src="<?php echo $car["prodpicture1"];?>" style="height:150px;width:100%">
  <div style="padding: 3px;">
  <p class="producttitle"><?php echo $car["prodtitle"];?></p>
  <p>原价：<span style="text-decoration:line-through;color:gray;font-size:small;"><?php echo $car["prodoriginal"];?></span></p>
  <p>
  <span style="color:red;font-size:large;">¥ <?php echo $car["prodprice"];?></span>
  <span style="float:right;color:gray;">销量：<?php echo $car["prodsales"];?></span>
  </p>
  </div>
  </div>
<?php endforeach;?>
</div>
</div>

<div id="prodpriceup" class="prodsort">
 <?php //价格升
foreach ($homepage2cars as $key => $row) {
$x[$key] = $row['prodprice'];}
array_multisort($x, SORT_ASC,$homepage2cars);
?>
<div class="row" >
<?php foreach ($homepage2cars as $car): ?>
  <div class="col-xs-6 productdisplay" onclick="location='productitem/<?php echo $car["prodid"];?>';">
  <img alt="" src="<?php echo $car["prodpicture1"];?>" style="height:150px;width:100%">
  <div style="padding: 3px;">
  <p class="producttitle"><?php echo $car["prodtitle"];?></p>
    <p>原价：<span style="text-decoration:line-through;color:gray;font-size:small;"><?php echo $car["prodoriginal"];?></span></p>
  <p>
  <span style="color:red;font-size:large;">¥ <?php echo $car["prodprice"];?></span>
  <span style="float:right;color:gray;">销量：<?php echo $car["prodsales"];?></span>
  </p>
  </div>
</div>
<?php endforeach;?>
</div>
</div>

<div id="prodpricedown" class="prodsort">
 <?php //价格降
foreach ($homepage2cars as $key => $row) {
$x[$key] = $row['prodprice'];}
array_multisort($x, SORT_DESC,$homepage2cars);
?>
<div class="row">
<?php foreach ($homepage2cars as $car): ?>
  <div class="col-xs-6 productdisplay" style="float:left;" onclick="location='productitem/<?php echo $car["prodid"];?>';">
  <img alt="" src="<?php echo $car["prodpicture1"];?>" style="height:150px;width:100%">
  <div  style="padding: 3px;">
  <p class="producttitle"><?php echo $car["prodtitle"];?></p>
    <p>原价：<span style="text-decoration:line-through;color:gray;font-size:small;"><?php echo $car["prodoriginal"];?></span></p>
  <p>
  <span style="color:red;font-size:large;">¥ <?php echo $car["prodprice"];?></span>
  <span style="float:right;color:gray;">销量：<?php echo $car["prodsales"];?></span>
  </p>
 </div>
</div>
<?php endforeach;?>
</div>
</div>

<div id="prodsales" class="prodsort">
 <?php  //销量排序
foreach ($homepage2cars as $key => $row) {
$x[$key] = $row['prodsales'];}
array_multisort($x, SORT_ASC,$homepage2cars);
?>
<div class="row">
<?php foreach ($homepage2cars as $car): ?>
  <div class="col-xs-6 productdisplay" style="float: left" onclick="location='productitem/<?php echo $car["prodid"];?>';">
  <img alt="" src="<?php echo $car["prodpicture1"];?>" style="height:150px;width:100%">
  <div style="padding: 3px;">
  <p class="producttitle"><?php echo $car["prodtitle"];?></p>
  <p>原价：<span style="text-decoration:line-through;color:gray;font-size:small;"><?php echo $car["prodoriginal"];?></span></p>
  <p>
  <span style="color:red;font-size:large;">¥ <?php echo $car["prodprice"];?></span>
  <span style="float:right;color:gray;">销量：<?php echo $car["prodsales"];?></span>
  </p>
  </div>
  </div>
<?php endforeach;?>
</div>
</div>

<div id="prodregdate" class="prodsort">
 <?php  //新品排序
foreach ($homepage2cars as $key => $row) {
$x[$key] = $row['prodregdate'];}
array_multisort($x, SORT_DESC,$homepage2cars);
?>
<div class="row" >
<?php foreach ($homepage2cars as $car): ?>
  <div class="col-xs-6 productdisplay" style="float:left;" onclick="location='productitem/<?php echo $car["prodid"];?>';">
  <img alt="" src="<?php echo $car["prodpicture1"];?>" style="height:150px;width:100%">
  <div style="padding: 3px;">
  <p class="producttitle"><?php echo $car["prodtitle"];?></p>
  <p>原价：<span style="text-decoration:line-through;color:gray;font-size:small;"><?php echo $car["prodoriginal"];?></span></p>
  <p>
  <span style="color:red;font-size:large;">¥ <?php echo $car["prodprice"];?></span>
  <span style="float:right;color:gray;">销量：<?php echo $car["prodsales"];?></span>
  </p>
  </div>
  </div>
<?php endforeach;?>
</div>
</div>
</div>