<?php //文件上传插件?>
<link href="/css/fileinput.min.css" media="screen" rel="stylesheet" type="text/css">
<script src="/js/fileinput.min.js"></script>
<script src="/js/fileinput.zh.js"></script>

<div class="well" style="text-align:center"><?php echo $homepage->getPageheaddata2();?></div>

<div style="text-align:center">
<img src="<?php echo $homepage->getPageheaddata1();?>" style="height:100px;width:120px;">
</div>



<script>
$("document").ready(function(){
$customer=new Array();
$('#phonenumber').hide();
<?php  //已有账号存入js数组
foreach ($customers as $customer):?>
$customer.push("<?php echo $customer->getCusphone();?>");
<?php endforeach;?>
})
</script>
<script>
function getfocus(){
	$('#cusphonediv').removeClass("has-error");
	$('#submit').show();
	$('#phonenumber').hide();
}
function checkout(){
	$value=$('#cusphone').val();
	if($value!==""){
         for($i=0;$i<$customer.length;$i++){
               if($value==$customer[$i]){
                     $('#cusphonediv').addClass("has-error");
                     $('#submit').hide();
                     $('#phonenumber').show();
                   }
             }
		}
}
</script>

<script>
$("document").ready(function(){
	$("#repeatwrong").hide();
	$("#repeatpassword").change(function(){
	    if($("#repeatpassword").val()!==$("#cuspassword").val()){
	    	$("#repeatwrong").show();
		    }
	});
	$("#repeatpassword").focus(function(){
		$("#repeatwrong").hide();
	});
	$("#cusphone").focus(function(){
		$("#phonewrong").hide();
	});
	$("#verificationinput").focus(function(){
		$("#verificationwrong").hide();
	});
})
</script>
<script>
$("document").ready(function(){
	$("#countdown").hide();
	$("#registerverification").click(function(){
		$num=59;
		//发短信
		$.post("<?php echo $this->url('customerajax', array('action'=>'registerverification'));?>",
			      {
			  	        cusregisterphone:$("#cusphone").val()
			  	    },
			  	        function(data,status){
			  	        //alert("数据: \n" + data + "\n状态: " + status);
			  	    });
  	    
  	    //显示倒计时
  	    $("#verification").hide();
    	$("#countdown").show();
    	$interval=setInterval(function(){
    	    if($num==0){
    	    $("#countdown").hide();
    	    $("#verification").show();
    	    clearInterval($interval);
    		};
    		$("#numDiv").html($num--);
    		},1000);
		})
})
</script>

<?php
$form = $this->form;
$form->setAttribute('action',$this->url('customer', array(
    'action' => 'register','sub'=>$sub
)));
$form->get('submit')->setAttribute('value', '提交');
$form->get('cusphone')->setAttribute('onblur', 'checkout()');
$form->get('cusphone')->setAttribute('onfocus', 'getfocus()');
$form->prepare();echo $this->form()->openTag($form);?>
<fieldset>
    <legend>注册账号</legend>
    <?php echo $this->formhidden($form->get('salnumber'));?>
	<div class="form-group" id="cusphonediv">
    <label for="name"><span class="glyphicon glyphicon-phone" aria-hidden="true"></span>&nbsp;手机号</label>
    <div id="phonenumber" style="color:red;" id="phonewrong">
    <?php if ($existcustomer):?>
        此号码已注册
    <?php endif;?>
    </div>
    <?php echo $this->formRow($form->get('cusphone'));?>
    </div>
    <div style="color:red;" id="verificationwrong">
    <?php if ($verificationwrong):?>
      验证码输入错误
    <?php endif;?>
    </div>
    <?php //注册验证码?>
    <div class="container">
      <div class="row">
      <div class="col-xs-8 col-sm-8"><input type="text" class="form-control"  placeholder="请输入短信验证码" id="verificationinput" name="registerverification"></div>
      <div class="col-xs-4 col-sm-4" id="verification"><a class="btn" id="registerverification">获取短息验证码</a></div> 
  	  <div class="col-xs-4 col-sm-4" id="countdown"><div id='numDiv' style="text-align:center;padding:5px;">60</div></div>
      </div>
    </div>


  <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>&nbsp;密码</label>
    <?php echo $this->formRow($form->get('cuspassword'));?>
  </div>
  <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>&nbsp;密码确认</label>
    <div style="color:red;" id="repeatwrong">
     两次输入密码不匹配
    </div>
    <input type="password" class="form-control" placeholder="请再次输入密码" id="repeatpassword">
  </div>
   <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;姓名</label>
    <?php echo $this->formRow($form->get('cusname'));?>
  </div>
  <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp;头像</label>
    <?php echo $this->formhidden($form->get('cusphoto'));?>
     <?php echo $this->formRow($form->get('cusphotof'));?>
  </div>
  <div class="form-group" style="text-align:center">
    <?php echo $this->formInput($form->get('submit')); ?>
  </div>
</fieldset>
<?php echo $this->form()->closeTag($form);?>
<button type="button" class="btn btn-default btn-lg btn-block" onclick="location='../login/<?php echo $sub;?>'">登陆</button>



<script>
$(document).on('ready', function() {
    $("#cusphotof").fileinput({
    	language: 'zh', //设置语言
   	 browseClass: "btn btn-default btn-block",
     showCaption: false,
     showRemove: false,
     showUpload: false
    });
});
</script>