<?php //文件上传插件?>
<link href="/css/fileinput.min.css" media="screen" rel="stylesheet" type="text/css">
<script src="/js/fileinput.min.js"></script>
<script src="/js/fileinput.zh.js"></script>

<div class="well" style="text-align:center"><?php echo $homepage->getPageheaddata2();?></div>

<div style="text-align:center">
<img src="<?php echo $homepage->getPageheaddata1();?>" style="height:100px;width:120px;">
</div>



<script>
$("document").ready(function(){
$customer=new Array();
$('#phonenumber').hide();
<?php  //已有账号存入js数组
foreach ($customers as $customer):?>
$customer.push("<?php echo $customer->getCusphone();?>");
<?php endforeach;?>
})
</script>
<script>
function getfocus(){
	$('#cusphonediv').removeClass("has-error");
	$('#submit').show();
	$('#phonenumber').hide();
}
function checkout(){
	$value=$('#cusphone').val();
	if($value!==""){
         for($i=0;$i<$customer.length;$i++){
               if($value==$customer[$i]){
                     $('#cusphonediv').addClass("has-error");
                     $('#submit').hide();
                     $('#phonenumber').show();
                   }
             }
		}
}
</script>

<script>
//密码确认
$("document").ready(function(){
	$("#repeatwrong").hide();
	$("#repeatpassword").change(function(){
	    if($("#repeatpassword").val()!==$("#cuspassword").val()){
	    	$("#repeatwrong").show();
		    }
	});
	$("#repeatpassword").focus(function(){
		$("#repeatwrong").hide();
	});
	$("#cusphone").focus(function(){
		$("#phonewrong").hide();
	});
})
</script>

<?php
$form = $this->form;
$form->setAttribute('action',$this->url('customer', array(
    'action' => 'reset','sub'=>$sub
)));
$form->get('submit')->setAttribute('value', '提交');
$form->get('cusphone')->setAttribute('onblur', 'checkout()');
$form->get('cusphone')->setAttribute('onfocus', 'getfocus()');
$form->prepare();echo $this->form()->openTag($form);?>
<fieldset>
    <legend>账号设置</legend>
    <?php echo $this->formhidden($form->get('salnumber'));?>
    <?php echo $this->formhidden($form->get('cusid'));?>
    <?php echo $this->formhidden($form->get('cusphone'));?>
  <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>&nbsp;新密码</label>
    <?php echo $this->formRow($form->get('cuspassword'));?>
  </div>
  <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>&nbsp;新密码确认</label>
    <div style="color:red;" id="repeatwrong">
     两次输入密码不匹配
    </div>
    <input type="password" class="form-control" placeholder="请再次输入密码" id="repeatpassword">
  </div>
   <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;姓名</label>
    <?php echo $this->formRow($form->get('cusname'));?>
  </div>
  <div class="form-group">
    <label for="name"><span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp;头像</label>
    <?php echo $this->formhidden($form->get('cusphoto'));?>
     <?php echo $this->formRow($form->get('cusphotof'));?>
  </div>
  <div class="form-group" style="text-align:center">
    <?php echo $this->formInput($form->get('submit')); ?>
  </div>
</fieldset>
<?php echo $this->form()->closeTag($form);?>
<button type="button" class="btn btn-default btn-lg btn-block" onclick="location='login/<?php echo $sub;?>'">登陆</button>


<script>
$(document).on('ready', function() {
    $("#cusphotof").fileinput({
    	language: 'zh', //设置语言
   	 browseClass: "btn btn-default btn-block",
     allowedFileExtensions: ['jpg', 'gif', 'png','jpeg'],
     showCaption: false,
     showRemove: false,
     showUpload: false
    });
});
</script>