<?php
//表情转换方法
include_once 'public/php/emotionreplace.php';?>

<link rel="stylesheet" href="/css/zoomify.css">
<script src="/js/zoomify.zoomed.js"></script>

<style>
.fbpicture1 {
	padding:2px;
    width: 100%;
}
.glyphicon-star{
color:#FFD700;
}
#mehead {
     background: -webkit-linear-gradient(<?php echo $homepage->getPagecolor();?>, white); /* Safari 5.1 - 6.0 */ 
     background: -o-linear-gradient(<?php echo $homepage->getPagecolor();?>, white); /* Opera 11.1 - 12.0 */ 
     background: -moz-linear-gradient(<?php echo $homepage->getPagecolor();?>, white); /* Firefox 3.6 - 15 */ 
     background: linear-gradient(<?php echo $homepage->getPagecolor();?>,white); /* 标准的语法（必须放在最后） */
}
	span{color: #708090;font-size:120%}
</style>
<style>

.img1 {
	width: 100%;
	max-height: 400px;
	min-height: 200px;
}

.img2 {
	width: 100%;
	max-height: 200px;
	min-height:100px;
}
.pageheadbtn{
	opacity:0.5;
}
.btn-default{
	color:<?php echo $homepage->getPagecolor();?>;
}


.ui-widget-content a {
	color:<?php echo $homepage->getPagecolor();?>;
}	
.swiper-slide  {
        font-size: 18px;
        color:<?php echo $homepage->getPagecolor();?>;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
    }
    .parallax-bg {
        position: absolute;
        left: 0;
        top: 0;
        width: 130%;
        height: 100%;
        -webkit-background-size: 100% 100%;;
        background-size: 100% 100%;;
        background-position: center;
    }
    .swiper-slide .title {
        font-size: 20px;
        font-weight: 300;
    }
    .swiper-slide .text {
        font-size: 7px;
    }

ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
}
</style>


<?php //TODO 页头?>
<script type="text/javascript">
//上滑消失，下滑显示
$(document).ready(function(){
	$("#fixedstandard").css({"height":$("#headanchor").height()});
	$x= $("#fixedstandard").offset().top - $(window).scrollTop();//变化中参考div距离屏幕高度
	$(document).scroll(function(){
		if($x>$("#fixedstandard").offset().top - $(window).scrollTop()&&$x<-400){
              $("#headanchor").slideUp("slow");
              $x= $("#fixedstandard").offset().top - $(window).scrollTop();
			}else{
				$("#headanchor").slideDown("slow");
	            $x= $("#fixedstandard").offset().top - $(window).scrollTop();
			}
		});
})
</script>
<!-- 页头 -->

<div class="input-group input-group-sm"
	style="position: fixed; z-index: 2; background: white;" id="headanchor">
	<span class="input-group-btn" onclick="window.history.back();"> 
	<span class="glyphicon glyphicon-chevron-left btn"></span>
	</span> <span class="input-group-btn"> <a href="#mehead" class="btn">基本信息</a>
	</span> <span class="input-group-btn"> <a href="#homepagenav1"
		class="btn">详情</a>
	</span>
    <span class="input-group-btn"> <a href="#feedbacks" class="btn">评价</a></span>
</div>
<div id="fixedstandard"></div>

<div style="text-align:center" id="mehead" class="container">
   <div class="row">
      <div class="col-xs-5 col-sm-5">
      <img src="<?php echo $salon->getSalphoto1();?>" class="img-thumbnail" style="width:150px;height:120px;padding-top:10px;padding-bottom:10px;">
      </div>
      <div class="col-xs-7 col-sm-7*">
      <div class="row" style="padding-top:10px;">
      <span><?php echo $salon->getSalname();?></span>
      </div>
      
      <div class="row" style="padding-top:10px;">
      <span>电话:</span>
      <span><?php echo $salon->getSalphone();?></span>
      </div>
      
      
      <div class="row" style="padding-top:10px;">
       <span>地址:</span>
      <span><?php echo $salon->getSaladdress();?></span>
      </div>
      
      </div>
   </div>
</div> 



<div class="nav_wrap homepagenav" id="homepagenav1" >
<div class="panel-heading" id="feedbacks"><span class="title">简介</span></div>
   <ul id="sortable" class="nav_ul">
<?php //TODO 组件输出模块 
include_once 'public/php/templateforui.phtml';?>
	</ul>
</div>



<div id="feedbacks">

<script>
//评论下拉加载更多
$(document).ready(function(){
  $commentoffset=0;
  $salbranch=<?php echo $salbranch;?>
  //初始化加载
  $.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'commentajax'));?>",dataType:"text",data:{commentoffset:$commentoffset,salbranch:$salbranch},type:"POST",success:function(data,status){
	   $("#commentcontainer").append(data);
}});
$(document).scroll(function(){
if($(window).scrollTop()+$(window).height()>$("#commentfixedstandard").offset().top-100){
 $commentoffset=$commentoffset+1;
 $.ajax({url:"<?php echo $this->url('customerajax', array('action'=>'commentajax'));?>",dataType:"text",data:{commentoffset:$commentoffset,salbranch:$salbranch},type:"POST",success:function(data,status){
	   $("#commentcontainer").append(data);
	   $(".commentloading").remove();
}});
}
})
});
</script>

<div class="panel panel-default" id="svn">
	<div class="panel-heading" id="feedbacks"><span class="title">评价</span></div>
	<div class="panel-body">
	  <div class="container" id="commentcontainer">
	  
       </div>
	<div id="commentfixedstandard"></div>
	</div>
</div>


</div>
