 <?php //文件上传插件?>
<link href="/css/fileinput.min.css" media="screen" rel="stylesheet" type="text/css">
<script src="/js/fileinput.min.js"></script>
<script src="/js/fileinput.zh.js"></script>
 
 <div class="input-group input-group-sm" style="opacity:0.9;background-color:white;padding: 5px;z-index:10;position:fixed;text-align:center;" id="searchcolumn">
      <span class="input-group-btn" onclick="window.history.back();">
        <button  class="btn btn-default btn-lg" type="button" style="color:	#00E5EE;">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
      <span style="font-weight: bold;">
              意见与建议
      </span>
      <span>
      
      </span>
 </div>
<!-- 没有作用，只为平衡高度 -->
<div class="input-group input-group-sm" style="visibility:hidden;padding: 5px;" >
      <span class="input-group-btn" >
        <button class="btn btn-default" type="button">
        <span class="glyphicon glyphicon-chevron-left"></span>
        </button>
      </span>
      <span>
      <button type="button" class="btn btn-info" onclick="">聊天历史</button>
      </span>
 </div>
 
<hr>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('customer', array(
    'action' => 'suggestioncus'
)));
$form->get('submitname')->setAttribute('value', '提交');
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
     <?php echo $this->formRow($form->get('cuscomment'));?>
</div>
<br>
<div class="form-group">
     <?php echo $this->formhidden($form->get('cuspicture'));?>
     <?php echo $this->formRow($form->get('cuspicturef'));?>
</div>
<div>
 <?php echo $this->formInput($form->get('submitname')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);?>


<script>
$(document).on('ready', function() {
    $("#cuspicturef").fileinput({
    	language: 'zh', //设置语言
   	 browseClass: "btn btn-default btn-block",
     allowedFileExtensions: ['jpg', 'gif', 'png','jpeg'],
     showCaption: false,
     showRemove: false,
     showUpload: false
    });
});
</script>


<script>
$(document).ready(function() {
    $('#suggestioncus').bootstrapValidator({
        message: 'This value is not valid',
        //excluded:[":hidden",":disabled",":not(visible)"] ,//bootstrapValidator的默认配置
        //excluded: ':disabled',//关键配置，表示只对于禁用域不进行验证，其他的表单元素都要验证

        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',//显示验证成功或者失败时的一个小图标
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
        	cuscomment: {
                message: '内容无效',
                validators: {
                	notEmpty: {
                        message: '内容不能为空'
                    },
                    stringLength: {
                        min: 1,
                        max: 250,
                        message: '内容长度在1-250之间'
                    },
                    regexp: {
                        regexp: /^[^<>]+$/,
                        message: '不得使用特殊字符'
                    }
                }
            },

        }
    }).on('error.form.bv', function(e) {
        console.log('error');

        // Active the panel element containing the first invalid element
        var $form         = $(e.target),
            validator     = $form.data('bootstrapValidator'),
            $invalidField = validator.getInvalidFields().eq(0),
            $collapse     = $invalidField.parents('.collapse');

        $collapse.collapse('show');
    });
});
</script>