<?php
$title = '添加购物车';
$this->headTitle($title);
?>
<h5><?php echo $this->escapeHtml($title); ?></h5>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('customer', array(
    'action' => 'trolleyadd'
)));
$form->get('submit')->setAttribute('value', '注册');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('salnumber'));
echo $this->formRow($form->get('cusid'));
echo $this->formRow($form->get('prodid'));
echo $this->formRow($form->get('prodtitle'));
echo $this->formRow($form->get('productcombinationid'));
echo $this->formRow($form->get('productcombinationprice'));
echo $this->formRow($form->get('productcombinationpicture'));
echo $this->formRow($form->get('productcombinationname'));
echo $this->formRow($form->get('productquantity'));
echo $this->formRow($form->get('trolleydate'));
?>
<div>
 <?php echo $this->formInput($form->get('submit'));
 echo $this->form()->closeTag($form);?>
 </div>
