<script type="text/javascript">
<!--

//-->
//为图片选择器切换目录
function rootdir1(){
	$(".subdir1").hide();
	$("#rootdir1").show();
	$("#dropdownMenu1").html("图片根目录");
};
function dirchoose1(dirname){
	$(".subdir1").hide();
	$("#rootdir1").hide();
    $("."+dirname+"1").show();
    $("#dropdownMenu1").html(dirname);
}
//输出化图片选择器的显示目录为根目录
$(function(){
	$(".subdir1").hide();
	$("#rootdir1").show();
	
});
//选择图片
function copyfilesrc1(src){
	switch($("#picturemanager1" ).attr("data-imgnumber"))
	{
	    case "picturechoose1":
	    	$(".picturechoose1").attr("src",src);
	        break;
	    case "picturechoose2":
	    	$(".picturechoose2").attr("src",src);
	        break;
	    case "picturechoose3":
	    	$(".picturechoose3").attr("src",src);
	        break;
	    case "picturechoose4":
	    	$(".picturechoose4").attr("src",src);
	        break;
	    case "picturechoose5":
	    	$(".picturechoose5").attr("src",src);
	        break;
	    default:
	}
	$("#picturemanager1").dialog("close");
};
//打开图片选择器
$(function() {
    $( "#picturemanager1" ).dialog({modal: true,autoOpen: false,width:800,height: 500,});
    $( ".picturechoose1" ).click(function() {
    	$( "#picturemanager1" ).attr("data-imgnumber","picturechoose1");
        $( "#picturemanager1" ).dialog( "open" );
      });
    $( ".picturechoose2" ).click(function() {
    	$( "#picturemanager1" ).attr("data-imgnumber","picturechoose2");
        $( "#picturemanager1" ).dialog( "open" );
      });
    $( ".picturechoose3" ).click(function() {
    	$( "#picturemanager1" ).attr("data-imgnumber","picturechoose3");
        $( "#picturemanager1" ).dialog( "open" );
      });
    $( ".picturechoose4" ).click(function() {
    	$( "#picturemanager1" ).attr("data-imgnumber","picturechoose4");
        $( "#picturemanager1" ).dialog( "open" );
      });
    $( ".picturechoose5" ).click(function() {
    	$( "#picturemanager1" ).attr("data-imgnumber","picturechoose5");
        $( "#picturemanager1" ).dialog( "open" );
      });
  });
</script>
<?php //TODO picturemanager?>
<?php
$dir2 = "public/salon/".$id;
$dir3 = iconv('utf-8', 'gbk', $dir2);
$file = scandir($dir3);
?>
 <?php 
 $photo=array();
 $directory=array();
 foreach ($file as $filegb): 
 $filesrc=iconv("GB2312","UTF-8",$filegb);
 if(substr(strrchr($filesrc, '.'), 1)==null){
     array_push($directory,$filesrc);
 }else{array_push($photo,$filesrc);}
 ?>
<?php endforeach; ?> 
<div id="picturemanager1" title="图片选择器" class="picturemanager" data-imgnumber="">
<div class="dropdown" style="float: left">
	<button type="button" class="btn dropdown-toggle" id="dropdownMenu1" 
			data-toggle="dropdown">
		图片根目录
		<span class="caret"></span>
	</button>
	<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
		<li role="presentation" onclick="rootdir1()">
			<a role="menuitem" tabindex="-1">图片根目录</a>
		</li>
		<li role="presentation" class="divider"></li>
		<?php for($i=0;$i<count($directory);$i++):
		if($directory[$i]!="."&&$directory[$i]!=".."){?>
		<li role="presentation" onclick="dirchoose1('<?php echo $directory[$i];?>')">
			<a role="menuitem" tabindex="-1"><?php echo $directory[$i];?></a>
		</li>
		<?php }endfor;?>
	</ul>
</div>

	<table class="table">
		<caption>点击图片进行选择</caption>
		<thead>
			<tr>
				<th>预览</th>
				<th>名称</th>
			</tr>

		</thead>
		
		<tbody id="rootdir1">
        <?php for($i=0;$i<count($photo);$i++):
        $endimg=explode('.', $photo[$i]);
        if(end($endimg)=="jpg"||end($endimg)=="png"||end($endimg)=="gif"):?>
            <tr>
				<td><img src="<?php echo '/salon/'.$id.'/'.$photo[$i]; ?>"
					onclick="copyfilesrc1('<?php echo '/salon/'.$id.'/'.$photo[$i]; ?>')"
					alt="Smiley face" width="60" height="30" class="imgchoose" data-imgnumber=""></td>
				<td><?php echo $photo[$i]; ?></td>
			</tr>
			<?php elseif (end($endimg)=="mp4"):?>
			<tr>
				
			    <td>
                     <video width="160" height="120" controls class="imgchoose" data-imgnumber="" onclick="copyfilesrc1('<?php echo '/salon/'.$id.'/'.$photo[$i]; ?>')">
                     <source src="<?php echo '/salon/'.$id.'/'.$photo[$i]; ?>" type="video/mp4">
                    </video>
               </td>
				<td><?php echo $photo[$i]; ?></td>
			</tr>
			<?php endif;?>
       <?php endfor; ?>
       </tbody>
       <?php for($i=0;$i<count($directory);$i++):
		if($directory[$i]!="."&&$directory[$i]!=".."){
		    $dir4 = "public/salon/".$id.'/'.$directory[$i];
		    $dir5 = iconv('utf-8', 'gbk', $dir4);
		    $photo1 = scandir($dir5);
		    ?>
       	<tbody class="subdir1 <?php echo $directory[$i]?>1">
        <?php for($j=0;$j<count($photo1);$j++):
        if($photo1[$j]!="."&&$photo1[$j]!=".."){
        if(1):?>
            <tr>
				<td><img src="<?php echo '/salon/'.$id.'/'.$directory[$i].'/'.$photo1[$j]; ?>"
					onclick="copyfilesrc1('<?php echo '/salon/'.$id.'/'.$directory[$i].'/'.$photo1[$j]; ?>')"
					alt="Smiley face" width="60" height="30" class="imgchoose" data-imgnumber=""></td>
				<td><?php echo $photo1[$j]; ?></td>
			</tr>
			<?php elseif (end(explode('.', $photo[$i]))=="mp4"):?>
						<tr>
				
			    <td>
                     <video width="160" height="120" controls class="imgchoose" data-imgnumber="" onclick="copyfilesrc1('<?php echo '/salon/'.$id.'/'.$directory[$i].'/'.$photo[$i]; ?>')">
                     <source src="<?php echo '/salon/'.$id.'/'.$directory[$i].'/'.$photo[$i]; ?>" type="video/mp4">
                    </video>
               </td>
				<td><?php echo $photo[$i]; ?></td>
			</tr>
			<?php endif;?>
       <?php }endfor; ?>
       </tbody>
       <?php }endfor;?>
	</table>
</div>
