<style>
#side_nav ul{display:none}
</style>
<script type="text/javascript">
<!--

//-->
//为图片选择器切换目录
function rootdir1(){
	$(".subdir1").hide();
	$("#rootdir1").show();
	$("#dropdownMenu1").html("图片根目录");
};
function dirchoose1(dirname){
	$(".subdir1").hide();
	$("#rootdir1").hide();
    $("."+dirname+"1").show();
    $("#dropdownMenu1").html(dirname);
}
//输出化图片选择器的显示目录为根目录
$(function(){
	$(".subdir1").hide();
	$("#rootdir1").show();
	
});
//选择图片
function copyfilesrc1(src){
	switch($("#picturemanager1" ).attr("data-imgnumber"))
	{
	    case "picturechoose1":
	    	$(".picturechoose1").attr("src",src);
	        break;
	    case "picturechoose2":
	    	$(".picturechoose2").attr("src",src);
	        break;
	    case "picturechoose3":
	    	$(".picturechoose3").attr("src",src);
	        break;
	    case "picturechoose4":
	    	$(".picturechoose4").attr("src",src);
	        break;
	    case "picturechoose5":
	    	$(".picturechoose5").attr("src",src);
	        break;
	    case "picturechoose6":
	    	$(".picturechoose6").attr("src",src);
	        break;
	    case "picturechoose7":
	    	$(".picturechoose7").attr("src",src);
	        break;
	    case "picturechoose8":
	    	$(".picturechoose8").attr("src",src);
	        break;
	    default:
	}
	$("#picturemanager1").dialog("close");
};
//打开图片选择器
$(function() {
    $( "#picturemanager1" ).dialog({modal: true,autoOpen: false,width:1000,height: 500,});
    $( ".picturechoose1" ).click(function() {
    	$( "#picturemanager1" ).attr("data-imgnumber","picturechoose1");
        $( "#picturemanager1" ).dialog( "open" );
      });
    $( ".picturechoose2" ).click(function() {
    	$( "#picturemanager1" ).attr("data-imgnumber","picturechoose2");
        $( "#picturemanager1" ).dialog( "open" );
      });
    $( ".picturechoose3" ).click(function() {
    	$( "#picturemanager1" ).attr("data-imgnumber","picturechoose3");
        $( "#picturemanager1" ).dialog( "open" );
      });
    $( ".picturechoose4" ).click(function() {
    	$( "#picturemanager1" ).attr("data-imgnumber","picturechoose4");
        $( "#picturemanager1" ).dialog( "open" );
      });
    $( ".picturechoose5" ).click(function() {
    	$( "#picturemanager1" ).attr("data-imgnumber","picturechoose5");
        $( "#picturemanager1" ).dialog( "open" );
      });
    $( ".picturechoose6" ).click(function() {
    	$( "#picturemanager1" ).attr("data-imgnumber","picturechoose6");
        $( "#picturemanager1" ).dialog( "open" );
      });
    $( ".picturechoose7" ).click(function() {
    	$( "#picturemanager1" ).attr("data-imgnumber","picturechoose7");
        $( "#picturemanager1" ).dialog( "open" );
      });
    $( ".picturechoose8" ).click(function() {
    	$( "#picturemanager1" ).attr("data-imgnumber","picturechoose8");
        $( "#picturemanager1" ).dialog( "open" );
      });
  });
</script>
<?php //TODO picturemanager?>
<?php
$dir2 = "public/salon/".$id;
$dir3 = iconv('utf-8', 'gbk', $dir2);
$file = scandir($dir3);

 $photo=array();
 $directory=array();
 foreach ($file as $filegb): 
 $filesrc=iconv("GB2312","UTF-8",$filegb);
 if(substr(strrchr($filesrc, '.'), 1)==null){
     array_push($directory,$filesrc);
 }else{array_push($photo,$filesrc);}
 endforeach; ?> 
 
 
<div id="picturemanager1"  style="overflow-x: hidden;" title="图片选择器" class="picturemanager" data-imgnumber="">
<div class="container">
   <div class="row">
      <div class="col-md-2 col-lg-2" style="border-right:1px solid #BEBEBE;">
      <ul id="side_nav">
 <?php for($i=0;$i<count($directory);$i++):
		if($directory[$i]!="."&&$directory[$i]!=".."){
		    $dir4 = "public/salon/".$id.'/'.$directory[$i];
		    $dir5 = iconv('utf-8', 'gbk', $dir4);
		    $file1 = scandir($dir5);
		    
		    $photo1=array();
		    $directory1=array();
		    foreach ($file1 as $filegb):
		    $filesrc=iconv("GB2312","UTF-8",$filegb);
		    if(substr(strrchr($filesrc, '.'), 1)==null){
		        array_push($directory1,$filesrc);
		    }else{array_push($photo1,$filesrc);}
		    endforeach;
		    ?>
 <li><span><img onclick='$.post("<?php echo $this->url('decorateajax', array('action'=>'picturechoiceajax'));?>",{id:"<?php echo $id;?>",sub:"<?php echo $directory[$i];?>",third:""},function(data,status){
	   $("#picturelist").html(data);
});'  src="<?php echo '/img/dir.jpg'; ?>" alt="Smiley face" width="32" height="32" ><?php echo $directory[$i];?></span>
  <ul>
  <?php for($j=0;$j<count($directory1);$j++):
       	if($directory1[$j]!="."&&$directory1[$j]!=".."){
        if(1):?>
   <li onclick='$.post("<?php echo $this->url('decorateajax', array('action'=>'picturechoiceajax'));?>",{id:"<?php echo $id;?>",sub:"<?php echo $directory[$i];?>",third:"<?php echo $directory1[$j];?>"},function(data,status){
	   $("#picturelist").html(data);
});'>&nbsp;&nbsp;&nbsp;&nbsp;<img src="<?php echo '/img/dir.jpg'; ?>" alt="Smiley face" width="32" height="32" ><?php echo $directory1[$j]; ?></li>
   <?php endif;?>
       <?php }endfor; ?>
  </ul>
 </li>
 <?php }endfor;?>
</ul> 
      </div>
      
      <div class="col-md-10 col-lg-10" >
      <div id="picturelist">
        <table class="table">
		<caption>点击图片进行选择</caption>
		<thead>
			<tr>
				<th>预览</th>
				<th>名称</th>
			</tr>

		</thead>
		
		<tbody id="rootdir1">
        <?php for($i=0;$i<count($photo);$i++):
        $endimg=explode('.', $photo[$i]);
        if(end($endimg)=="jpg"||end($endimg)=="png"||end($endimg)=="gif"):?>
            <tr>
				<td><img src="<?php echo '/salon/'.$id.'/'.$photo[$i]; ?>"
					onclick="copyfilesrc1('<?php echo '/salon/'.$id.'/'.$photo[$i]; ?>')"
					alt="Smiley face" width="60" height="30" class="imgchoose" data-imgnumber=""></td>
				<td><?php echo $photo[$i]; ?></td>
			</tr>
			<?php elseif (end($endimg)=="mp4"):?>
			<tr>
				
			    <td>
                     <video width="160" height="120" controls class="imgchoose" data-imgnumber="" onclick="copyfilesrc1('<?php echo '/salon/'.$id.'/'.$photo[$i]; ?>')">
                     <source src="<?php echo '/salon/'.$id.'/'.$photo[$i]; ?>" type="video/mp4">
                    </video>
               </td>
				<td><?php echo $photo[$i]; ?></td>
			</tr>
			<?php endif;?>
       <?php endfor; ?>
       </tbody>
     </table>
    </div>
      </div>      
   </div>
</div>


</div>


 <script type="text/javascript">
 (function(){
  var navWrap=document.getElementById("side_nav");
  var nav1s=navWrap.getElementsByTagName("span");
  var nav2s=navWrap.getElementsByTagName("ul");
  for(var i=0,len=nav1s.length;i<len;i++){
   nav1s[i].onclick=(function(i){
    return function(){
     for(var j=0;j<len;j++){
      nav2s[j].style.display="none";
     }
     nav2s[i].style.display="block";
    }
   })(i)
  }
 })()
</script>