<?php foreach ($templateitem as $item) :?>
<?php switch ($item->getTemplatetype()): ?>
<?php case "singlerow": ?>
<li data-type="singlerow" class="ui-state-highlight intro">
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<a href="<?php echo $item->getTemplatedata1()?>"
										class="singlea"> <img
										data-original="<?php echo $item->getTemplatedata2()?>"
										class="img1 singleimg">
									</a>
								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "doublerow": ?>
<li data-type="doublerow" class="ui-state-highlight intro">
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<a href="<?php echo  $item->getTemplatedata1()?>"
										class="doublea1"> <img 
										data-original="<?php echo  $item->getTemplatedata2()?>"
										class="img2 doubleimg1">
									</a>
								</div>
							</div>
							<div class="col">
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<a href="<?php echo  $item->getTemplatedata3()?>"
										class="doublea2"> <img 
										data-original="<?php echo $item->getTemplatedata4()?>"
										class="img2 doubleimg2">
									</a>
								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "swiperrow": ?>
<li id="draggable23" data-type="swiperrow"
					class="ui-state-highlight intro">
					<!-- Swiper -->
					<div class="swiper-container swiperswiper" style="height: 200px">
						<div class="swiper-wrapper">
        <?php if($item->getTemplatedata2()!="/img/123.jpg"):?>
            <div class="swiper-slide">
								<a href="<?php echo  $item->getTemplatedata1()?>"
									class="swipera1"> <img 
									data-original="<?php echo  $item->getTemplatedata2()?>"
									class="img1 swiperimg1" style="height: 100%; width: 100%">
								</a>
							</div><?php endif;?>
	    <?php if($item->getTemplatedata4()!="/img/123.jpg"):?>
            <div class="swiper-slide">
								<a href="<?php echo  $item->getTemplatedata3()?>"
									class="swipera2"> <img 
									data-original="<?php echo  $item->getTemplatedata4()?>"
									class="img1 swiperimg2" style="height: 100%; width: 100%">
								</a>
							</div><?php endif;?>
	   <?php if($item->getTemplatedata6()!="/img/123.jpg"):?>
            <div class="swiper-slide">
								<a href="<?php echo  $item->getTemplatedata5()?>"
									class="swipera3"> <img 
									data-original="<?php echo  $item->getTemplatedata6()?>"
									class="img1 swiperimg3" style="height: 100%; width: 100%">
								</a>
							</div><?php endif;?>
       <?php if($item->getTemplatedata8()!="/img/123.jpg"):?>
            <div class="swiper-slide">
								<a href="<?php echo  $item->getTemplatedata7()?>"
									class="swipera4"> <img 
									data-original="<?php echo  $item->getTemplatedata8()?>"
									class="img1 swiperimg4" style="height: 100%; width: 100%">
								</a>
							</div><?php endif;?>
	   <?php if($item->getTemplatedata10()!="/img/123.jpg"):?>
            <div class="swiper-slide">
								<a href="<?php echo  $item->getTemplatedata9()?>"
									class="swipera5"> <img 
									data-original="<?php echo  $item->getTemplatedata10()?>"
									class="img1 swiperimg5" style="height: 100%; width: 100%">
								</a>
							</div><?php endif;?>
        </div>
						<!-- Add Pagination -->
						<div class="swiper-pagination swiperpagination"></div>
					</div>
				</li>
<?php break;?>
<?php case "headlinerow": ?>
				<li data-type="headlinerow" class="ui-state-highlight intro">
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<div class="well">
										<a href="<?php echo $item->getTemplatedata1()?>"
											class="headlinea"> <span class="headlinetext"><?php echo $item->getTemplatedata2()?></span>
											<span class="ui-icon ui-icon-triangle-1-e"
											style="float: right"></span>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "textrow": ?>
<li id="draggable32" data-type="textrow"
					class="ui-state-highlight intro">
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<div class="well">
										<span class="texttext"><?php echo $item->getTemplatedata1()?> </span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "imgtextrow": ?>
<li id="draggable33" data-type="imgtextrow"
					class="ui-state-highlight intro">
					<!-- Swiper图文 -->
					<div class="swiper-container imgtextswiper" style="height: 200px">
						<div class="parallax-bg imgtextimg" data-backgroundimage="<?php echo $item->getTemplatedata1()?>" style="background-image:url(<?php echo $item->getTemplatedata1()?>)" data-swiper-parallax="-23%"></div>
						<div class="swiper-wrapper">
							<div class="swiper-slide">
								<div class="title" data-swiper-parallax="-100">
									<a href="<?php echo $item->getTemplatedata2()?>"
										class="imgtexttitle1 imgtexta1"><?php echo $item->getTemplatedata3()?></a>
								</div>
								<div class="text" data-swiper-parallax="-300">
									<p class="imgtexttext1"><?php echo $item->getTemplatedata4()?></p>
								</div>
							</div>
							<div class="swiper-slide">
								<div class="title" data-swiper-parallax="-100">
									<a href="<?php echo $item->getTemplatedata5()?>"
										class="imgtexttitle2 imgtexta2"><?php echo $item->getTemplatedata6()?></a>
								</div>

								<div class="text" data-swiper-parallax="-300">
									<p class="imgtexttext2"><?php echo $item->getTemplatedata7()?></p>
								</div>
							</div>
							<div class="swiper-slide">
								<div class="title" data-swiper-parallax="-100">
									<a href="<?php echo $item->getTemplatedata8()?>"
										class="imgtexttitle3 imgtexta3"><?php echo $item->getTemplatedata9()?></a>
								</div>

								<div class="text" data-swiper-parallax="-300">
									<p class="imgtexttext3"><?php echo $item->getTemplatedata10()?></p>
								</div>
							</div>
						</div>
						<!-- Add Pagination -->
						<div
							class="swiper-pagination imgtextpagination swiper-pagination-white"></div>
					</div>
				</li>
<?php break;?>
<?php case "videorow": ?>
				<li data-type="videorow" class="ui-state-highlight intro">
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<div class="embed-responsive embed-responsive-16by9">
										
										<video width="100%"  controls class="videosrc embed-responsive-item" poster="/meicon/corporatelogo2.png">
                                           <source src="<?php echo $item->getTemplatedata1()?>#t=0.1" type="video/mp4">
                                        </video> 
									</div>

								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php endswitch; ?>
<?php endforeach;?>