<?php foreach ($templateitem as $item) :?>
<?php switch ($item->getTemplatetype()): ?>
<?php case "singlerow": ?>
<li  data-type="singlerow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#singlesubmit").attr("onclick","mysingle("+$(this).index(".intro")+")");
						$("#singledelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#singlerowimg").attr("src",$(this).find(".singleimg").attr("src"));
           $("#singlerowlink").val($(this).find(".singlea").attr("data-href"));
           $(".fieldset").hide();
           $("#singlerowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<a  data-href="<?php echo $item->getTemplatedata1()?>" class="singlea"> <img alt=""
										src="<?php echo $item->getTemplatedata2()?>" class="img1 singleimg">
									</a>
								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "doublerow": ?>
<li  data-type="doublerow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#doublesubmit").attr("onclick","mydouble("+$(this).index(".intro")+")");
						$("#doubledelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#doublerowimg1").attr("src",$(this).find(".doubleimg1").attr("src"));
           $("#doublerowlink1").val($(this).find(".doublea1").attr("data-href"));
           $("#doublerowimg2").attr("src",$(this).find(".doubleimg2").attr("src"));
           $("#doublerowlink2").val($(this).find(".doublea2").attr("data-href"));
           $(".fieldset").hide();
           $("#doublerowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<a  data-href="<?php echo  $item->getTemplatedata1()?>" class="doublea1"> <img alt=""
										src="<?php echo  $item->getTemplatedata2()?>" class="img2 doubleimg1">
									</a>
								</div>
							</div>
							<div class="col">
								<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<a  data-href="<?php echo  $item->getTemplatedata3()?>" class="doublea2"> <img alt=""
										src="<?php echo $item->getTemplatedata4()?>" class="img2 doubleimg2">
									</a>
								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "swiperrow": ?>
<li data-type="swiperrow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#swipersubmit").attr("onclick","myswiper("+$(this).index(".intro")+")");
						$("#swiperdelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#swiperrowimg1").attr("src",$(this).find(".swiperimg1").attr("src"));
           $("#swiperrowlink1").val($(this).find(".swipera1").attr("data-href"));
           $("#swiperrowimg2").attr("src",$(this).find(".swiperimg2").attr("src"));
           $("#swiperrowlink2").val($(this).find(".swipera2").attr("data-href"));
           $("#swiperrowimg3").attr("src",$(this).find(".swiperimg3").attr("src"));
           $("#swiperrowlink3").val($(this).find(".swipera3").attr("data-href"));
           $("#swiperrowimg4").attr("src",$(this).find(".swiperimg4").attr("src"));
           $("#swiperrowlink4").val($(this).find(".swipera4").attr("data-href"));
           $("#swiperrowimg5").attr("src",$(this).find(".swiperimg5").attr("src"));
           $("#swiperrowlink5").val($(this).find(".swipera5").attr("data-href"));
           $("#swiperrowimg6").attr("src",$(this).find(".swiperimg6").attr("src"));
           $("#swiperrowlink6").val($(this).find(".swipera6").attr("data-href"));
           
           $(".fieldset").hide();
           $("#swiperrowfield").show();}'>
		    <!-- Swiper -->
    <div class="swiper-container swiperswiper" style="height:200px">
        <div class="swiper-wrapper">
        <?php if($item->getTemplatedata2()!="/img/mylogo.png"):?>
            <div class="swiper-slide"><a  data-href="<?php echo  $item->getTemplatedata1()?>" class="swipera1"> <img alt=""
										src="<?php echo  $item->getTemplatedata2()?>" class="img1 swiperimg1" style="height:100%;width: 100%">
									</a></div><?php endif;?>
	    <?php if($item->getTemplatedata4()!="/img/mylogo.png"):?>
            <div class="swiper-slide"><a  data-href="<?php echo  $item->getTemplatedata3()?>" class="swipera2"> <img alt=""
										src="<?php echo  $item->getTemplatedata4()?>" class="img1 swiperimg2" style="height:100%;width: 100%">
									</a></div><?php endif;?>
	   <?php if($item->getTemplatedata6()!="/img/mylogo.png"):?>
            <div class="swiper-slide"><a  data-href="<?php echo  $item->getTemplatedata5()?>" class="swipera3"> <img alt=""
										src="<?php echo  $item->getTemplatedata6()?>" class="img1 swiperimg3" style="height:100%;width: 100%">
									</a></div><?php endif;?>
       <?php if($item->getTemplatedata8()!="/img/mylogo.png"):?>
            <div class="swiper-slide"><a  data-href="<?php echo  $item->getTemplatedata7()?>" class="swipera4"> <img alt=""
										src="<?php echo  $item->getTemplatedata8()?>" class="img1 swiperimg4" style="height:100%;width: 100%">
									</a></div><?php endif;?>
	   <?php if($item->getTemplatedata10()!="/img/mylogo.png"):?>
            <div class="swiper-slide"><a  data-href="<?php echo  $item->getTemplatedata9()?>" class="swipera5"> <img alt=""
										src="<?php echo  $item->getTemplatedata10()?>" class="img1 swiperimg5" style="height:100%;width: 100%">
									</a></div><?php endif;?>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination swiperpagination"></div>
        </div>
</li>
<?php break;?>
<?php case "headlinerow": ?>
				<li  data-type="headlinerow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#headlinesubmit").attr("onclick","myheadline("+$(this).index(".intro")+")");
						$("#headlinedelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#headlinerowtext").val($(this).find(".headlinetext").html());
	       $("#headlinerowlink").val($(this).find(".headlinea").attr("data-href"));
           $(".fieldset").hide();
           $("#headlinerowfield").show();}'>
					<div class="content">
						<div class="row" >
							<div class="col">
							<div class="col-demo">
							<div class="well">
							<a  data-href="<?php echo $item->getTemplatedata1()?>" class="headlinea">
							<span class="headlinetext"><?php echo $item->getTemplatedata2()?></span>
							<span class="ui-icon ui-icon-triangle-1-e" style="float: right"></span>
							</a>
							</div>
						    </div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "textrow": ?>
<li  data-type="textrow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#textsubmit").attr("onclick","mytext("+$(this).index(".intro")+")");
						$("#textdelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#textrowtext").val($(this).find(".texttext").html());
           $(".fieldset").hide();
           $("#textrowfield").show();}'>
					<div class="content">
						<div class="row" >
							<div class="col">
							<div class="col-demo">
							<div class="well">
							<span class="texttext"><?php echo $item->getTemplatedata1()?> </span>
							</div>
						    </div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "imgtextrow": ?>
<li  data-type="imgtextrow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#imgtextsubmit").attr("onclick","myimgtext("+$(this).index(".intro")+")");
						$("#imgtextdelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
		   $("#imgtextrowimg").attr("src",$(this).find(".imgtextimg").attr("data-backgroundimage"));
	       $("#imgtextrowtitle1").val($(this).find(".imgtexttitle1").html());
	       $("#imgtextrowlink1").val($(this).find(".imgtexta1").attr("data-href"));
	       $("#imgtextrowtext1").val($(this).find(".imgtexttext1").html());
	       $("#imgtextrowtitle2").val($(this).find(".imgtexttitle2").html());
	       $("#imgtextrowlink2").val($(this).find(".imgtexta2").attr("data-href"));
	       $("#imgtextrowtext2").val($(this).find(".imgtexttext2").html());
	       $("#imgtextrowtitle3").val($(this).find(".imgtexttitle3").html());
	       $("#imgtextrowlink3").val($(this).find(".imgtexta3").attr("data-href"));
	       $("#imgtextrowtext3").val($(this).find(".imgtexttext3").html());
           $(".fieldset").hide();
           $("#imgtextrowfield").show();}'>
					<!-- Swiper图文 -->
    <div class="swiper-container imgtextswiper" style="height:200px">
        <div class="parallax-bg imgtextimg" data-backgroundimage="<?php echo $item->getTemplatedata1();?>" style="background-image:url(<?php echo $item->getTemplatedata1()?>)" data-swiper-parallax="-23%"></div>
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <div class="title" data-swiper-parallax="-100"><a data-href="<?php echo $item->getTemplatedata2();?>" class="imgtexttitle1 imgtexta1" ><?php echo $item->getTemplatedata3()?></a></div>
                <div class="text" data-swiper-parallax="-300">
                    <p class="imgtexttext1"><?php echo $item->getTemplatedata4();?></p>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="title" data-swiper-parallax="-100"><a data-href="<?php echo $item->getTemplatedata5();?>" class="imgtexttitle2 imgtexta2"><?php echo $item->getTemplatedata6()?></a></div>
              
                <div class="text" data-swiper-parallax="-300">
                    <p class="imgtexttext2"><?php echo $item->getTemplatedata7();?></p>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="title" data-swiper-parallax="-100"><a data-href="<?php echo $item->getTemplatedata8();?>" class="imgtexttitle3 imgtexta3" ><?php echo $item->getTemplatedata9()?></a></div>
              
                <div class="text" data-swiper-parallax="-300">
                    <p class="imgtexttext3"><?php echo $item->getTemplatedata10();?></p>
                </div>
            </div>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination imgtextpagination swiper-pagination-white"></div>
    </div>
</li>
<?php break;?>
<?php case "videorow": ?>
				<li  data-type="videorow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#videosubmit").attr("onclick","myvideo("+$(this).index(".intro")+")");
						$("#videodelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#videorowsrc").attr("src",$(this).find(".videosrc").attr("src"));
           $(".fieldset").hide();
           $("#videorowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<div class="embed-responsive embed-responsive-16by9">
                                     <video width="100%"  controls class="videosrc embed-responsive-item" src="<?php echo $item->getTemplatedata1()?>">
                                     
                                    </video> 
                                    </div>
								
								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "lotteryrow": ?>
				<li  data-type="lotteryrow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#lotterysubmit").attr("onclick","mylottery("+$(this).index(".intro")+")");
						$("#lotterydelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#lotteryrowimg1").attr("src",$(this).find(".lotteryimg1").attr("src"));
	       $("#lotteryrowimg2").attr("src",$(this).find(".lotteryimg2").attr("src"));
	       $("#lotteryrowimg3").attr("src",$(this).find(".lotteryimg3").attr("src"));
	       $("#lotteryrowimg4").attr("src",$(this).find(".lotteryimg4").attr("src"));
	       $("#lotteryrowimg5").attr("src",$(this).find(".lotteryimg5").attr("src"));
	       $("#lotteryrowimg6").attr("src",$(this).find(".lotteryimg6").attr("src"));
	       $("#lotteryrowimg7").attr("src",$(this).find(".lotteryimg7").attr("src"));
	       $("#lotteryrowimg8").attr("src",$(this).find(".lotteryimg8").attr("src"));
	       $("#lotteryrowtext1").val($(this).find(".lotteryrowtext1").attr("data-lotteryrate"));
           $(".fieldset").hide();
           $("#lotteryrowfield").show();}'>
					<div class="content">
						<div class="row">
  <div id="lottery">
    <table class="lotteryrowtext1" data-lotteryrate="<?php echo $item->getTemplatedata9();?>">
        <tbody><tr>
            <td class="lottery-unit lottery-unit-0"><img src="<?php echo $item->getTemplatedata1();?>" class="lotteryimg1"><div class="mask"></div></td>
            <td class="lottery-unit lottery-unit-1"><img src="<?php echo $item->getTemplatedata2();?>" class="lotteryimg2"><div class="mask"></div></td>
            <td class="lottery-unit lottery-unit-2"><img src="<?php echo $item->getTemplatedata3();?>" class="lotteryimg3"><div class="mask"></div></td>
        </tr>
        <tr>
            <td class="lottery-unit lottery-unit-7"><img src="<?php echo $item->getTemplatedata8();?>" class="lotteryimg8"><div class="mask"></div></td>
            <td><a href="#"><img src="/img/lottery1.jpg"></a></td>
            <td class="lottery-unit lottery-unit-3 active"><img src="<?php echo $item->getTemplatedata4();?>" class="lotteryimg4"><div class="mask"></div></td>
        </tr>
        <tr>
            <td class="lottery-unit lottery-unit-6"><img src="<?php echo $item->getTemplatedata7();?>" class="lotteryimg7"><div class="mask"></div></td>
            <td class="lottery-unit lottery-unit-5"><img src="<?php echo $item->getTemplatedata6();?>" class="lotteryimg6"><div class="mask"></div></td>
            <td class="lottery-unit lottery-unit-4"><img src="<?php echo $item->getTemplatedata5();?>" class="lotteryimg5"><div class="mask"></div></td>
        </tr>
    </tbody></table>
  </div>
						</div>
					</div>
				</li>
<?php break;?>
<?php endswitch; ?>
<?php endforeach;?>