<?php //TODO template?>
<div class="template" id="template" data-template="template">
	<div id="accordion">
	    <h3>新老用户，vip模块，宝贝推荐</h3>
		<div>
			<ul>
			   <!-- 新老用户 -->
				<li id="draggable11" data-type="newoldrow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#newoldsubmit").attr("onclick","mynewold("+$(this).index(".intro")+")");
						$("#newolddelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#newoldrowimg1").attr("src",$(this).find(".newoldimg1").attr("src"));
           $("#newoldrowlink1").val($(this).find(".newolda1").attr("data-href"));
           $("#newoldrowimg2").attr("src",$(this).find(".newoldimg2").attr("src"));
           $("#newoldrowlink2").val($(this).find(".newolda2").attr("data-href"));
           $(".fieldset").hide();
           $("#newoldrowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<a  data-href="" class="newolda1"> <img alt=""
										src="/img/new.jpg" class="img2 newoldimg1">
									</a>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<a  data-href="" class="newolda2"> <img alt=""
										src="/img/old.jpg" class="img2 newoldimg2">
									</a>
								
							</div>
						</div>
					</div>
				</li>
				<!-- vip模块  -->
				<li id="draggable12" data-type="viprow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#vipsubmit").attr("onclick","myvip("+$(this).index(".intro")+")");
						$("#vipdelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#viprowimg").attr("src",$(this).find(".vipimg").attr("src"));
           $("#viprowlink").val($(this).find(".vipa").attr("data-href"));
           $("#viprowlevel").val($(this).find(".vipa").attr("data-level"));
           $(".fieldset").hide();
           $("#viprowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<a data-level=""  data-href="" class="vipa"> <img alt=""
										src="/img/vip.jpg" class="img1 vipimg">
									</a>
								</div>
							</div>
						</div>
					</div>
				</li>
				<!-- 宝贝推荐  -->
				<li id="draggable13" data-type="recommendedprodrow" class="ui-state-highlight intro"
				onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#recommendedproddelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
           $(".fieldset").hide();
           $("#recommendedprodrowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<img alt="" src="/img/recommend.jpg" class="img1">
								</div>
							</div>
						</div>
					</div>
				</li>
			</ul>
		</div>
		<h3>单、双列图片，轮播图</h3>
		<div>
			<ul>
				<!-- 单列图片  -->
				<li id="draggable21" data-type="singlerow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#singlesubmit").attr("onclick","mysingle("+$(this).index(".intro")+")");
						$("#singledelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#singlerowimg").attr("src",$(this).find(".singleimg").attr("src"));
           $("#singlerowlink").val($(this).find(".singlea").attr("data-href"));
           $(".fieldset").hide();
           $("#singlerowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<a  data-href="" class="singlea"> <img alt=""
										src="/img/single.jpg" class="img1 singleimg">
									</a>
								</div>
							</div>
						</div>
					</div>
				</li>
				<!-- 双列图片 -->
				<li id="draggable22" data-type="doublerow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#doublesubmit").attr("onclick","mydouble("+$(this).index(".intro")+")");
						$("#doubledelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#doublerowimg1").attr("src",$(this).find(".doubleimg1").attr("src"));
           $("#doublerowlink1").val($(this).find(".doublea1").attr("data-href"));
           $("#doublerowimg2").attr("src",$(this).find(".doubleimg2").attr("src"));
           $("#doublerowlink2").val($(this).find(".doublea2").attr("data-href"));
           $(".fieldset").hide();
           $("#doublerowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<a  data-href="" class="doublea1"> <img alt=""
										src="/img/double.jpg" class="img2 doubleimg1">
									</a>
							</div>
							<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
									<a  data-href="" class="doublea2"> <img alt=""
										src="/img/double.jpg" class="img2 doubleimg2">
									</a>
								
							</div>
						</div>
					</div>
				</li>
				<!-- 轮播 -->
				<li id="draggable23" data-type="swiperrow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#swipersubmit").attr("onclick","myswiper("+$(this).index(".intro")+")");
						$("#swiperdelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#swiperrowimg1").attr("src",$(this).find(".swiperimg1").attr("src"));
           $("#swiperrowlink1").val($(this).find(".swipera1").attr("data-href"));
           $("#swiperrowimg2").attr("src",$(this).find(".swiperimg2").attr("src"));
           $("#swiperrowlink2").val($(this).find(".swipera2").attr("data-href"));
           $("#swiperrowimg3").attr("src",$(this).find(".swiperimg3").attr("src"));
           $("#swiperrowlink3").val($(this).find(".swipera3").attr("data-href"));
           $("#swiperrowimg4").attr("src",$(this).find(".swiperimg4").attr("src"));
           $("#swiperrowlink4").val($(this).find(".swipera4").attr("data-href"));
           $("#swiperrowimg5").attr("src",$(this).find(".swiperimg5").attr("src"));
           $("#swiperrowlink5").val($(this).find(".swipera5").attr("data-href"));
           $("#swiperrowimg6").attr("src",$(this).find(".swiperimg6").attr("src"));
           $("#swiperrowlink6").val($(this).find(".swipera6").attr("data-href"));
           
           $(".fieldset").hide();
           $("#swiperrowfield").show();}'>
		    <!-- Swiper -->
    <div class="swiper-container swiperswiper" style="height:200px">
        <div class="swiper-wrapper">
            <div class="swiper-slide"><a  data-href="" class="swipera1"> <img alt=""
										src="/img/swiper.jpg" class="img1 swiperimg1" style="width: 100%">
									</a></div>
            <div class="swiper-slide"><a  data-href="" class="swipera2"> <img alt=""
										src="/img/swiper.jpg" class="img1 swiperimg2" style="width: 100%">
									</a></div>
            <div class="swiper-slide"><a  data-href="" class="swipera3"> <img alt=""
										src="/img/swiper.jpg" class="img1 swiperimg3" style="width: 100%">
									</a></div>
            <div class="swiper-slide"><a  data-href="" class="swipera4"> <img alt=""
										src="/img/swiper.jpg" class="img1 swiperimg4" style="width: 100%">
									</a></div>
            <div class="swiper-slide"><a  data-href="" class="swipera5"> <img alt=""
										src="/img/swiper.jpg" class="img1 swiperimg5" style="width: 100%">
									</a></div>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination swiperpagination"></div>
        </div>
        </li>
</ul>
		</div>
		<h3>标题，文本，图文</h3>
		<div>
			<ul>
		<!-- 标题  -->
				<li id="draggable31" data-type="headlinerow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#headlinesubmit").attr("onclick","myheadline("+$(this).index(".intro")+")");
						$("#headlinedelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#headlinerowtext").val($(this).find(".headlinetext").html());
	       $("#headlinerowlink").val($(this).find(".headlinea").attr("data-href"));
           $(".fieldset").hide();
           $("#headlinerowfield").show();}'>
					<div class="content">
						<div class="row" >
							<div class="col">
							<div class="col-demo">
							<div class="well">
							<a  data-href="" class="headlinea">
							<span class="headlinetext">这是一个标题</span>
							<span class="ui-icon ui-icon-triangle-1-e" style="float: right"></span>
							</a>
							</div>
						    </div>
							</div>
						</div>
					</div>
				</li>
				<!-- 文本  -->
				<li id="draggable32" data-type="textrow" class="ui-state-highlight intro"
					onclick='editorsync2($(this).find(".texttext").html());
					if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#textsubmit").attr("onclick","mytext("+$(this).index(".intro")+")");
						$("#textdelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#textrowtext").val($(this).find(".texttext").html());
           $(".fieldset").hide();
           $("#textrowfield").show();}'>
					<div class="content">
						<div class="row" >
							<div class="col">
							<div class="col-demo">
							<div class="well">
							<div class="texttext">这是一个文本 </div>
							</div>
						    </div>
							</div>
						</div>
					</div>
				</li>
			<!-- 图文  -->
				<li id="draggable33" data-type="imgtextrow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#imgtextsubmit").attr("onclick","myimgtext("+$(this).index(".intro")+")");
						$("#imgtextdelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
		   $("#imgtextrowimg").attr("src",$(this).find(".imgtextimg").attr("data-backgroundimage"));
	       $("#imgtextrowtitle1").val($(this).find(".imgtexttitle1").html());
	       $("#imgtextrowlink1").val($(this).find(".imgtexta1").attr("data-href"));
	       $("#imgtextrowtext1").val($(this).find(".imgtexttext1").html());
	       $("#imgtextrowtitle2").val($(this).find(".imgtexttitle2").html());
	       $("#imgtextrowlink2").val($(this).find(".imgtexta2").attr("data-href"));
	       $("#imgtextrowtext2").val($(this).find(".imgtexttext2").html());
	       $("#imgtextrowtitle3").val($(this).find(".imgtexttitle3").html());
	       $("#imgtextrowlink3").val($(this).find(".imgtexta3").attr("data-href"));
	       $("#imgtextrowtext3").val($(this).find(".imgtexttext3").html());
           $(".fieldset").hide();
           $("#imgtextrowfield").show();}'>
					<!-- Swiper图文 -->
    <div class="swiper-container imgtextswiper" style="height:200px">
        <div class="parallax-bg imgtextimg" data-backgroundimage="/img/imgtext.jpg" style="background-image:url(/img/imgtext.jpg)" data-swiper-parallax="-23%"></div>
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <div class="title" data-swiper-parallax="-100"><a data-href="" class="imgtexttitle1 imgtexta1" >第一页标题</a></div>
                <div class="text" data-swiper-parallax="-300">
                    <p class="imgtexttext1">第一页内容</p>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="title" data-swiper-parallax="-100"><a data-href="" class="imgtexttitle2 imgtexta2">第二页标题</a></div>
              
                <div class="text" data-swiper-parallax="-300">
                    <p class="imgtexttext2">第二页内容</p>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="title" data-swiper-parallax="-100"><a data-href="" class="imgtexttitle3 imgtexta3" >第三页标题</a></div>
              
                <div class="text" data-swiper-parallax="-300">
                    <p class="imgtexttext3">第三页内容</p>
                </div>
            </div>
            
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination imgtextpagination swiper-pagination-white"></div>
    </div>
				</li>
		    </ul>
		</div>
		<h3>视频,抽奖</h3>
		<div>
		<ul>
		<!-- 视频  -->
				<li id="draggable41" data-type="videorow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#videosubmit").attr("onclick","myvideo("+$(this).index(".intro")+")");
						$("#videodelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#videorowsrc").attr("src",$(this).find(".videosrc").attr("src"));
           $(".fieldset").hide();
           $("#videorowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<div class="embed-responsive embed-responsive-16by9">
                                     <video width="100%"  controls autoplay class="videosrc embed-responsive-item" src="/img/test.mp4" >
                            
                                    </video> 
                                    </div> 
								</div>
							</div>
						</div>
					</div>
				</li>
		 <!-- 每日抽奖  -->
				<li id="draggable42" data-type="lotteryrow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#lotterysubmit").attr("onclick","mylottery("+$(this).index(".intro")+")");
						$("#lotterydelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#lotteryrowimg1").attr("src",$(this).find(".lotteryimg1").attr("src"));
	       $("#lotteryrowimg2").attr("src",$(this).find(".lotteryimg2").attr("src"));
	       $("#lotteryrowimg3").attr("src",$(this).find(".lotteryimg3").attr("src"));
	       $("#lotteryrowimg4").attr("src",$(this).find(".lotteryimg4").attr("src"));
	       $("#lotteryrowimg5").attr("src",$(this).find(".lotteryimg5").attr("src"));
	       $("#lotteryrowimg6").attr("src",$(this).find(".lotteryimg6").attr("src"));
	       $("#lotteryrowimg7").attr("src",$(this).find(".lotteryimg7").attr("src"));
	       $("#lotteryrowimg8").attr("src",$(this).find(".lotteryimg8").attr("src"));
	       $("#lotteryrowtext1").val($(this).find(".lotterytable").attr("data-lotteryrate"));
	       $("#lotteryrowtext2").val($(this).find(".lotterytable").attr("data-lotterypoints"));
           $(".fieldset").hide();
           $("#lotteryrowfield").show();}'>
					<div class="content">
						<div class="row"> 
  <div id="lottery">
    <table class="lotterytable" data-lotteryrate="" data-lotterypoints="">
     <caption style="font-size: 150%">&nbsp;<span style="color: #ba1809;" class="glyphicon glyphicon-gift" aria-hidden="true"></span>&nbsp;&nbsp;每日抽奖</caption>
        <tbody><tr>
            <td class="lottery-unit lottery-unit-0 active"><img src="/img/prize1.jpg" class="lotteryimg1"><div class="mask"></div></td>
            <td class="lottery-unit lottery-unit-1"><img src="/img/prize2.jpg" class="lotteryimg2"><div class="mask"></div></td>
            <td class="lottery-unit lottery-unit-2"><img src="/img/prize3.jpg" class="lotteryimg3"><div class="mask"></div></td>
        </tr>
        <tr>
            <td class="lottery-unit lottery-unit-7"><img src="/img/thanksforyou.jpg" class="lotteryimg8"><div class="mask"></div></td>
            <td><a href="#"><img src="/img/lottery1.jpg"></a></td>
            <td class="lottery-unit lottery-unit-3"><img src="/img/prize4.jpg" class="lotteryimg4"><div class="mask"></div></td>
        </tr>
        <tr>
            <td class="lottery-unit lottery-unit-6"><img src="/img/prize7.jpg" class="lotteryimg7"><div class="mask"></div></td>
            <td class="lottery-unit lottery-unit-5"><img src="/img/prize6.jpg" class="lotteryimg6"><div class="mask"></div></td>
            <td class="lottery-unit lottery-unit-4"><img src="/img/prize5.jpg" class="lotteryimg5"><div class="mask"></div></td>
        </tr>
    </tbody></table>
  </div>
						</div>
					</div>
				</li>
				
				<!-- 积分抽奖  -->
				<li id="draggable43" data-type="lotterypointsrow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#lotterypointssubmit").attr("onclick","mylotterypoints("+$(this).index(".intro")+")");
						$("#lotterypointsdelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#lotterypointsrowimg1").attr("src",$(this).find(".lotterypointsimg1").attr("src"));
	       $("#lotterypointsrowimg2").attr("src",$(this).find(".lotterypointsimg2").attr("src"));
	       $("#lotterypointsrowimg3").attr("src",$(this).find(".lotterypointsimg3").attr("src"));
	       $("#lotterypointsrowimg4").attr("src",$(this).find(".lotterypointsimg4").attr("src"));
	       $("#lotterypointsrowimg5").attr("src",$(this).find(".lotterypointsimg5").attr("src"));
	       $("#lotterypointsrowimg6").attr("src",$(this).find(".lotterypointsimg6").attr("src"));
	       $("#lotterypointsrowimg7").attr("src",$(this).find(".lotterypointsimg7").attr("src"));
	       $("#lotterypointsrowimg8").attr("src",$(this).find(".lotterypointsimg8").attr("src"));
	       $("#lotterypointsrowtext1").val($(this).find(".lotterypointstable").attr("data-lotterypointsrate"));
	       $("#lotterypointsrowtext2").val($(this).find(".lotterypointstable").attr("data-lotterypointspoints"));
           $(".fieldset").hide();
           $("#lotterypointsrowfield").show();}'>
					<div class="content">
						<div class="row"> 
  <div id="lotterypoints">
    <table class="lotterypointstable" data-lotterypointsrate="" data-lotterypointspoints="">
     <caption style="font-size: 150%">&nbsp;<span style="color: #ba1809;" class="glyphicon glyphicon-gift" aria-hidden="true"></span>&nbsp;&nbsp;积分抽奖</caption>
        <tbody><tr>
            <td class="lottery-unit lottery-unit-0 active"><img src="/img/prize1.jpg" class="lotterypointsimg1"><div class="mask"></div></td>
            <td class="lottery-unit lottery-unit-1"><img src="/img/prize2.jpg" class="lotterypointsimg2"><div class="mask"></div></td>
            <td class="lottery-unit lottery-unit-2"><img src="/img/prize3.jpg" class="lotterypointsimg3"><div class="mask"></div></td>
        </tr>
        <tr>
            <td class="lottery-unit lottery-unit-7"><img src="/img/thanksforyou.jpg" class="lotterypointsimg8"><div class="mask"></div></td>
            <td><a href="#"><img src="/img/lottery1.jpg"></a></td>
            <td class="lottery-unit lottery-unit-3"><img src="/img/prize4.jpg" class="lotterypointsimg4"><div class="mask"></div></td>
        </tr>
        <tr>
            <td class="lottery-unit lottery-unit-6"><img src="/img/prize7.jpg" class="lotterypointsimg7"><div class="mask"></div></td>
            <td class="lottery-unit lottery-unit-5"><img src="/img/prize6.jpg" class="lotterypointsimg6"><div class="mask"></div></td>
            <td class="lottery-unit lottery-unit-4"><img src="/img/prize5.jpg" class="lotterypointsimg5"><div class="mask"></div></td>
        </tr>
    </tbody></table>
  </div>
						</div>
					</div>
				</li>
		    </ul>
		</div>
	</div>
</div>