<?php //TODO 登陆后，在app中存入美容院id,用于订单通知?>
<script>
	var u = navigator.userAgent;
	var isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1; //android终端
	var isiOS = !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/); //ios终端
    if(isAndroid){
        //加引号就是字符串
    	window.android.salidsave(<?php echo $id;?>);
        }
    if(isiOS){
        window.webkit.messageHandlers.iossalidsave.postMessage(<?php echo $id;?>);
            }
</script>

<style>
.menubottom{
	z-index:100;
	position:fixed;
	bottom:0px;
	background-color:<?php echo $homepage->getPagecolor();?>;
	}
.bottom-btn{
	border-right:0.1px solid rgba(0, 0, 0, 0.0980392);
	border-top:0.1px solid rgba(0, 0, 0, 0.0980392);
}
.bottom-btn-me{
	border-top:0.1px solid rgba(0, 0, 0, 0.0980392);
}
</style>

<div class="well"><span class="glyphicon glyphicon-list-alt" style="color:red;" aria-hidden="true"></span>&nbsp;&nbsp;顾客订单</div>

<script src="/js/Chart.min.js"></script>
<canvas id="myChart"></canvas>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var chart = new Chart(ctx, {
    // The type of chart we want to create
    type: 'line',

    // The data for our dataset
    data: {
        labels: ["1", "2", "3", "4", "5", "6", "今"],
        datasets: [{
            label: "近七日销量图",
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            data: [<?php echo $sevendayscount[6];?>, <?php echo $sevendayscount[5];?>, <?php echo $sevendayscount[4];?>, <?php echo $sevendayscount[3];?>, <?php echo $sevendayscount[2];?>, <?php echo $sevendayscount[1];?>, <?php echo $sevendayscount[0];?>],
        }]
    },

    // Configuration options go here
    options: {}
});
</script>





<div class="container" style="padding: 5px;">
   <div class="row" align="center">
      <div class="col-xs-3 col-sm-3"><button type="button" class="btn btn-default datepick" id="today">今日</button></div>
      <div class="col-xs-3 col-sm-3"><button type="button" class="btn btn-default datepick" id="yesterday">昨日</button></div>
      <div class="col-xs-3 col-sm-3"><button type="button" class="btn btn-default datepick" id="aweek">7日</button></div>
      <div class="col-xs-3 col-sm-3"><button type="button" class="btn btn-default datepick" id="amonth">30日</button></div>   
   </div>
</div>

<div id="cusorderajaxcontent">

</div>


<script type="text/javascript">
$(document).ready(function(){
	
	//默认
	$("#today").addClass("active");
	$.post("<?php echo $this->url('salonbossajax', array('action'=>'cusorderajax'));?>",
		    {
		        minValue:"today"
		    },
		        function(data,status){
		        $("#cusorderajaxcontent").html(data);
    });
    //点击
	$("#today").click(function(){
		$(".datepick").removeClass("active");
		$("#today").addClass("active");
	    $.post("<?php echo $this->url('salonbossajax', array('action'=>'cusorderajax'));?>",
	    {
	        minValue:"today"
	    },
	        function(data,status){
	        $("#cusorderajaxcontent").html(data);
	    });
	});
	$("#yesterday").click(function(){
		$(".datepick").removeClass("active");
		$("#yesterday").addClass("active");
	    $.post("<?php echo $this->url('salonbossajax', array('action'=>'cusorderajax'));?>",
	    {
	        minValue:"yesterday"
	    },
	        function(data,status){
	    	$("#cusorderajaxcontent").html(data);
	    });
	});
	$("#aweek").click(function(){
		$(".datepick").removeClass("active");
		$("#aweek").addClass("active");
	    $.post("<?php echo $this->url('salonbossajax', array('action'=>'cusorderajax'));?>",
	    {
	        minValue:"aweek"
	    },
	        function(data,status){
	    	$("#cusorderajaxcontent").html(data);
	    });
	});
	$("#amonth").click(function(){
		$(".datepick").removeClass("active");
		$("#amonth").addClass("active");
	    $.post("<?php echo $this->url('salonbossajax', array('action'=>'cusorderajax'));?>",
	    {
	        minValue:"amonth"
	    },
	        function(data,status){
	    	$("#cusorderajaxcontent").html(data);
	    });
	});
})
</script>







<?php //TODO 底部菜单栏  用于站位?>
<div class="btn-group btn-group-justified" role="group" style="visibility:hidden">
  <div class="btn-group" role="group" style="text-align:center;" >
  <span class="glyphicon glyphicon-home" style="font-size:25px;color:red;" aria-hidden="true"></span>
  <div style="color:red;">首页</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-time" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>预约</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-edit" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>咨询</div>
  </div>
  <div class="btn-group" role="group" style="text-align:center;">
  <span class="glyphicon glyphicon-user" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>我</div>
  </div>
</div>

<?php //TODO 底部菜单栏?>
<div class="btn-group btn-group-justified menubottom" role="group" >
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('salonboss', array('action'=>'cusorder','sub'=>$id));?>';">
  <span class="glyphicon glyphicon-list-alt" style="font-size:25px;color:red;" aria-hidden="true"></span>
  <div  style="color:red;">订单</div>
  </div>
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('salonboss', array('action'=>'cusreview'));?>';">
  <span class="glyphicon glyphicon-star" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>评星</div>
  </div>
  <div class="btn-group bottom-btn" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('salonboss', array('action'=>'cusbrowsing'));?>';">
  <span class="glyphicon glyphicon-phone" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>客户</div>
  </div>
  <div class="btn-group bottom-btn-me" role="group" style="text-align:center;" 
  onclick="location='<?php echo $this->url('salonboss', array('action'=>'me'));?>';">
  <span class="glyphicon glyphicon-user" style="font-size:20px;color:gray;" aria-hidden="true"></span>
  <div>我</div>
  </div>
</div>

<?php //TODO 登陆后，在ios app中调用方法执行保存devicetoken,android不需要?>
<script>
$(document).ready(function(){
	var u = navigator.userAgent;
	var isAndroid = u.indexOf('Android') > -1 || u.indexOf('Adr') > -1; //android终端
	var isiOS = !!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/); //ios终端
    if(isAndroid){
        //加引号就是字符串
    	//window.android.cusidsave();
        }
    if(isiOS){
        window.webkit.messageHandlers.salonbosstoken.postMessage("1");//方法必须要有参数才会调用
            }
})
</script>