<style type="text/css">  
body{  
  background: url("/img/registerok.jpg") no-repeat;
  height:100%;
  width:100%;
  overflow: hidden;
  background-size:cover;
}
</style> 
<style>
#agreement
{
	position:fixed;
	bottom:50px;
}
</style>
 
<div id="agreement">
<div style="text-align: center;">
<h3>恭喜您，注册成功！</h3>
</div>

<div style="padding:25px;color:#708090;">
我们会安排一位专职工作人员协助您工作，请保持电话畅通
</div>
</div>