<style type="text/css">  
body{  
  background: url("/img/registerok.jpg") no-repeat;
  height:100%;
  width:100%;
  overflow: hidden;
  background-size:cover;
}
</style> 
<style>
#agreement
{
	position:fixed;
	bottom:50px;
}
</style>
 
<div id="agreement">
<div style="text-align: center;">
<h3>恭喜您，注册成功！</h3>
<p>账号：<?php echo $sub;?></p>
<p>密码：<?php echo $third;?></p>
</div>

<div style="padding:25px;color:#708090;">
请稍后使用台式机或笔记本，登陆<span style="color: blue;">www.oushelun.cn</span>
下载后台系统，使用以上账号密码，登陆后可查看APP的下载二维码。android版24小时后即可下载，ios版需要通过苹果公司审核，预计时间为一周。请耐心等待......
</div>
</div>