<div class="well" style="text-align:center"><?php echo $homepage->getPageheaddata2();?></div>

<div style="text-align:center">
<img src="<?php echo $homepage->getPageheaddata1();?>" style="height:100px;width:120px;">
</div>


<?php
$form = $this->form;
$form->setAttribute('action', $this->url('salonboss', array(
    'action' => 'salonbosslogin','sub'=>$sub
)));
$form->get('submit')->setAttribute('value', '登陆');
$form->get('submit')->setAttribute('class', 'button blue bigrounded');
$form->prepare();
echo $this->form()->openTag($form);?>
<fieldset>
    <legend>账号登陆</legend>
    <label for="name" style="color:red;"><?php echo $result;?></label>
	<div class="form-group">
    <label for="name">手机（试用账号：15195770746）</label>
    <?php echo $this->formRow($form->get('salbossphone'));?>
    </div>
    <div class="form-group">
    <label for="name">密码（试用密码：123456）</label>
    <?php echo $this->formRow($form->get('salpassword'));?>
    </div>
    <div class="form-group" style="text-align:center">
    <?php echo $this->formInput($form->get('submit')); ?>
    </div>
</fieldset>
<?php echo $this->form()->closeTag($form);?>