<style>
.fontred{
	color:red;
}
</style>
<script>
function change(file,text) {
var x="0123456789qwertyuioplkjhgfdsazxcvbnm";
var tmp="";
var timestamp = new Date().getTime();
for(var i=0;i< 10;i++) {
tmp += x.charAt(Math.ceil(Math.random()*100000000)%x.length);}
var random=timestamp+tmp;
var obj = document.getElementById(file);
var len = obj.files.length;
for (var i = 0; i < len; i++) {
var temp = obj.files[i].name;}
var fileExt=(/[.]/.exec(temp)) ? /[^.]+$/.exec(temp.toLowerCase()) : '';
var randomname=random+"."+fileExt;
var obj2 = document.getElementById(text);
obj2.value=randomname;
}
</script>
<div class="well" style="text-align:center">oushelun</div>

<div style="text-align:center">
<img src="/meicon/corporatelogo.png" style="height:100px;width:120px;">
</div>


<?php
$form = $this->form;
$form->setAttribute('action', $this->url('salonboss', array(
    'action' => 'salonbossregister'
)));
$form->get('submit')->setAttribute('value', '注册');
$form->get('submit')->setAttribute('class', 'button blue bigrounded');
$form->prepare();
echo $this->form()->openTag($form);?>
<fieldset>
    <legend>账号登陆</legend>
    <?php if ($existaccount):?>
    <p style="color:red;">账号已存在</p>
    <?php endif;?>
    <label for="name" style="color:red;"><?php echo $result;?></label>
    <div class="form-group">
    <label for="name">编号<span class="fontred">*</span></label>
    <?php echo $this->formRow($form->get('salnumber'));?>
    </div>
	<div class="form-group">
    <label for="name">账号<span class="fontred">*</span></label>
    <?php echo $this->formRow($form->get('salaccount'));?>
    </div>
    <div class="form-group">
    <label for="name">密码<span class="fontred">*</span></label>
    <?php echo $this->formRow($form->get('salpassword'));?>
    </div>
    <div class="form-group">
    <label for="name">姓名</label>
    <?php echo $this->formRow($form->get('salbossname'));?>
    </div>
    <div class="form-group">
    <label for="name">手机号</label>
    <?php echo $this->formRow($form->get('salbossphone'));?>
    </div>
    <div class="form-group">
    <label for="name">身份证号</label>
    <?php echo $this->formRow($form->get('salbossidentity'));?>
    </div>
    <div class="form-group">
    <label for="name">照片</label>
    <?php echo $this->formhidden($form->get('salbossphoto'));?>
    <?php echo $this->formRow($form->get('salbossphotof'));?>
    </div>
    <div class="form-group" style="text-align:center">
    <?php echo $this->formInput($form->get('submit')); ?>
    </div>
</fieldset>
<?php echo $this->form()->closeTag($form);?>