<?php //文件上传插件?>
<link href="/css/fileinput.min.css" media="screen" rel="stylesheet" type="text/css">
<script src="/js/fileinput.min.js"></script>
<script src="/js/fileinput.zh.js"></script>


<style>
.fontred{
	color:red;
}
</style>
<script>
function change(file,text) {
var x="0123456789qwertyuioplkjhgfdsazxcvbnm";
var tmp="";
var timestamp = new Date().getTime();
for(var i=0;i< 10;i++) {
tmp += x.charAt(Math.ceil(Math.random()*100000000)%x.length);}
var random=timestamp+tmp;
var obj = document.getElementById(file);
var len = obj.files.length;
for (var i = 0; i < len; i++) {
var temp = obj.files[i].name;}
var fileExt=(/[.]/.exec(temp)) ? /[^.]+$/.exec(temp.toLowerCase()) : '';
var randomname=random+"."+fileExt;
var obj2 = document.getElementById(text);
obj2.value=randomname;
}
</script>
<div class="well" style="text-align:center;color:#FFB90F;">美&nbsp;&nbsp;店&nbsp;&nbsp;汇</div>
<br>
<div style="text-align:center">
<img src="/img/mylogo.png" style="height:100px;width:120px;">
</div>

<script>
$("document").ready(function(){
	//密码确认
	/*$("#repeatwrong").hide();
	$("#repeatpassword").change(function(){
	    if($("#repeatpassword").val()!==$("#salpassword").val()){
	    	$("#repeatwrong").show();
		    }
	});*/
	//密码不同点击提交无效，未确认协议点击无效
	/*$("#submitbtn").click(function(){
		 if($("#repeatpassword").val()!==$("#salpassword").val()){
		    	$("#repeatwrong").show();
			    }else{
			    	if($("#checkagreement").is(":checked")){
						 $("#submit").click();
						 }else{$("#unconfirmedagreement").show();}
				     } 
		})*/
	$("#submitbtn").click(function(){
			    	if($("#checkagreement").is(":checked")){
						 $("#submitid").click();
						 }else{$("#unconfirmedagreement").show();}		     
		})
    //同意协议后隐藏
    $("#checkagreement").click(function(){
    	$("#unconfirmedagreement").hide();
    })
    //点击密码框后隐藏
	$("#repeatpassword").focus(function(){
		$("#repeatwrong").hide();
	});
	//点击账号框后隐藏
	$("#salaccount").focus(function(){
        $("#accountwrong").hide();
		})
    //点击电话框后隐藏
	$("#salbossphone").focus(function(){
		$("#phonewrong").hide();
	});
	//点击验证码框后隐藏
	$("#verificationinput").focus(function(){
		$("#verificationwrong").hide();
	});
})
</script>
<script>
$("document").ready(function(){
	$("#countdown").hide();
	$("#loadingimg").hide();
	$("#registerverification").click(function(){
		$num=59;
		//发短信
		$.post("<?php echo $this->url('customerajax', array('action'=>'registerverification'));?>",
			      {
			  	        cusregisterphone:$("#salbossphone").val(),
				  	      TemplateCode:"SMS_126585304"
			  	    },
			  	        function(data,status){
			  	        //alert("数据: \n" + data + "\n状态: " + status);
			  	    });
  	    
  	    //显示倒计时
  	    $("#verification").hide();
    	$("#countdown").show();
    	$interval=setInterval(function(){
    	    if($num==0){
    	    $("#countdown").hide();
    	    $("#verification").show();
    	    clearInterval($interval);
    		};
    		$("#numDiv").html($num--);
    		},1000);
		})
})
</script>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('salonboss', array(
    'action' => 'salonbossregister','sub'=>$recommend
)));
$form->get('submitname')->setAttribute('value', '注册');
$form->get('submitname')->setAttribute('class', 'button blue bigrounded');
$form->get('submitname')->setAttribute('style', 'visibility: hidden');
$form->get('salbossphone')->setAttribute('onblur', 'checkout()');
$form->get('salbossphone')->setAttribute('onfocus', 'getfocus()');
$form->get('salbossphone')->setAttribute('required', 'required');
$form->get('salpassword')->setAttribute('required', 'required');
$form->prepare();
echo $this->form()->openTag($form);?>
<fieldset>
    <legend>美容院注册</legend>
    <div class="form-group">
    <label for="name"><span class="fontred">*</span>&nbsp;手机号</label>
    <div  style="color:red;" id="phonewrong">
    <?php if ($existsalbossphone):?>
        此号码已注册
    <?php endif;?>
    </div>
    <?php echo $this->formRow($form->get('salbossphone'));?>
    </div>
    <div class="form-group">
    <label for="name"><span class="fontred">*</span>&nbsp;密码</label>
    <?php echo $this->formRow($form->get('salpassword'));?>
    </div>
    <!--
    <div class="form-group">
    <label for="name"><span class="fontred">*</span>&nbsp;密码确认</label>
    <div style="color:red;display:none;" id="repeatwrong">
     两次输入密码不匹配
    </div>
    <input type="password" name="repeatpassword" class="form-control" required="required" placeholder="请再次输入密码" id="repeatpassword">
    </div>
    -->
    <div style="color:red;" id="verificationwrong">
    <?php if ($verificationwrong):?>
      验证码输入错误
    <?php endif;?>
    </div>
    <?php //注册验证码?>
    <div class="container form-group">
      <div class="row">
      <div class="col-xs-8 col-sm-8"><input type="text" required="required" class="form-control"  placeholder="请输入短信验证码" id="verificationinput" name="registerverification"></div>
      <div class="col-xs-4 col-sm-4" id="verification"><a class="btn" id="registerverification">获取短息验证码</a></div> 
  	  <div class="col-xs-4 col-sm-4" id="countdown"><div id='numDiv' style="text-align:center;padding:5px;">60</div></div>
      </div>
    </div>
     <div class="form-group">
    <label for="name">&nbsp;美容院名称（选填）</label>
    <?php echo $this->formRow($form->get('salname'));?>
    </div>
    <div class="form-group">
    <label for="name">&nbsp;商标图（选填）</label>
    <?php echo $this->formhidden($form->get('salbossphoto'));?>
    <?php echo $this->formRow($form->get('salbossphotof'));?>
    </div>
    <?php echo $this->formInput($form->get('submitname')); ?>
</fieldset>
<?php echo $this->form()->closeTag($form);?>
    <div style="color:red;display:none;" id="unconfirmedagreement">
        未同意协议
    </div>
    <div class="form-group" style="text-align: center;">
    <input type="checkbox" id="checkagreement">已阅读并同意遵守<a href="/salonboss/salonagreement">《欧奢伦服务协议》</a>
    </div>
    <div class="form-group" style="text-align:center">
    <button type="button" id="submitbtn" class="button blue bigrounded btn-block">提交</button>
    </div>
<div class="form-group" style="text-align:center">
<button type="button" class="button white bigrounded btn-block" onclick="location='/salonboss/salonbosslogin/123'">登陆</button>
</div>
<script>
$(document).on('ready', function() {
    $("#salbossphotof").fileinput({
    	language: 'zh', //设置语言
   	 browseClass: "btn btn-default btn-block",
     allowedFileExtensions: ['jpg', 'gif', 'png','jpeg'],
     showCaption: false,
     showRemove: false,
     showUpload: false
    });
});
</script>



<script>
$(document).ready(function() {
    $('#Account').bootstrapValidator({
        message: 'This value is not valid',
        //excluded:[":hidden",":disabled",":not(visible)"] ,//bootstrapValidator的默认配置
        //excluded: ':disabled',//关键配置，表示只对于禁用域不进行验证，其他的表单元素都要验证

        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',//显示验证成功或者失败时的一个小图标
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
        	salbossphone: {
                message: '号码无效',
                validators: {
                    notEmpty: {
                        message: '手机号码不能为空'
                    },
//                     digits: {
//                         min: 1,
//                         max: 11,
//                         message: '请输入11位手机号码'
//                     },
                    regexp: {
                    	regexp: /^1[3|4|5|6|7|8|9]{1}[0-9]{9}$/,
                        message: '请输入11位手机号码'
                    }
                }
            },
            salpassword: {
                message:'密码无效',
                validators: {
                    notEmpty: {
                        message: '密码不能为空'
                    },
                    stringLength: {
                        min: 6,
                        max: 30,
                        message: '密码长度必须在6到30之间'
                    },
                    regexp: {
                        regexp: /^[a-zA-Z0-9_\.]+$/,
                        message: '密码只能包含数字，字母，标点或下划线'
                    }
                }
            },
            salname: {
                message: '名称无效',
                validators: {
                    
                    stringLength: {
                        min: 1,
                        max: 30,
                        message: '名称长度在1-30之间'
                    },
                    regexp: {
                        regexp: /^[^<>]+$/,
                        message: '不得使用特殊字符'
                    }
                }
            },

        }
    }).on('error.form.bv', function(e) {
        console.log('error');

        // Active the panel element containing the first invalid element
        var $form         = $(e.target),
            validator     = $form.data('bootstrapValidator'),
            $invalidField = validator.getInvalidFields().eq(0),
            $collapse     = $invalidField.parents('.collapse');

        $collapse.collapse('show');
    });
});
</script>