<div class="well" style="text-align:center">oushelun</div>

<div style="text-align:center">
<img src="/img/mylogo.png" style="height:100px;width:120px;">
</div>


<?php
$form = $this->form;
$form->setAttribute('action', $this->url('salonboss', array(
    'action' => 'salonbosslogin','sub'=>$sub
)));
$form->get('submitname')->setAttribute('value', '登陆');
$form->get('submitname')->setAttribute('class', 'button blue bigrounded btn-block');
$form->prepare();
echo $this->form()->openTag($form);?>
<fieldset>
    <legend>账号登陆</legend>
    <label for="name" style="color:red;"><?php echo $result;?></label>
	<div class="form-group">
    <label for="name">手机</label>
    <?php echo $this->formRow($form->get('salbossphone'));?>
    </div>
    <div class="form-group">
    <label for="name">密码</label>
    <?php echo $this->formRow($form->get('salpassword'));?>
    </div>
    <div class="form-group" style="text-align:center">
    <?php echo $this->formInput($form->get('submitname')); ?>
    </div>
</fieldset>
<?php echo $this->form()->closeTag($form);?>
<div class="form-group" style="text-align:center">
<button type="button" class="button white bigrounded btn-block" onclick="location='/salonboss/salonbossregister'">注册</button>
</div>


<script>
$(document).ready(function() {
    $('#Account').bootstrapValidator({
        message: 'This value is not valid',
        //excluded:[":hidden",":disabled",":not(visible)"] ,//bootstrapValidator的默认配置
        //excluded: ':disabled',//关键配置，表示只对于禁用域不进行验证，其他的表单元素都要验证

        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',//显示验证成功或者失败时的一个小图标
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
        	salbossphone: {
                message: '号码无效',
                validators: {
                    notEmpty: {
                        message: '手机号码不能为空'
                    },
//                     digits: {
//                         min: 1,
//                         max: 11,
//                         message: '请输入11位手机号码'
//                     },
                    regexp: {
                    	regexp: /^1[3|4|5|6|7|8|9]{1}[0-9]{9}$/,
                        message: '请输入11位手机号码'
                    }
                }
            },
            salpassword: {
                message:'密码无效',
                validators: {
                    notEmpty: {
                        message: '密码不能为空'
                    },
                    stringLength: {
                        min: 6,
                        max: 30,
                        message: '密码长度必须在6到30之间'
                    },
                    regexp: {
                        regexp: /^[a-zA-Z0-9_\.]+$/,
                        message: '密码只能包含数字，字母，标点或下划线'
                    }
                }
            },

        }
    }).on('error.form.bv', function(e) {
        console.log('error');

        // Active the panel element containing the first invalid element
        var $form         = $(e.target),
            validator     = $form.data('bootstrapValidator'),
            $invalidField = validator.getInvalidFields().eq(0),
            $collapse     = $invalidField.parents('.collapse');

        $collapse.collapse('show');
    });
});
</script>