<?php
 $title = '修改账号';
 $this->headTitle($title);
 ?>
 <h5><?php echo $this->escapeHtml($title); ?></h5>

 <?php
 $form = $this->form;
 $url = $this->url('cosmetic', array('action' => 'accountedit','sub'=>$sub));
 $form->setAttribute('action', $url);
 $form->get('submit')->setAttribute('value', '提交');
 $form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('salnumber'));
echo $this->formRow($form->get('salaccount'));
echo $this->formRow($form->get('salpassword'));
 ?>
 <div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
 <?php
 echo $this->form()->closeTag($form);