<?php
$title = '注册账号';
$this->headTitle($title);
?>
<h5><?php echo $this->escapeHtml($title); ?></h5>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cosmetic', array(
    'action' => 'accountadd'
)));
$form->get('submit')->setAttribute('value', '注册');
$form->prepare();
echo $this->form()->openTag($form);?>
 
 <fieldset>
    <legend>美容院注册</legend>
	<div class="form-group">
	<label for="name">编号</label>
    <?php echo $this->formRow($form->get('salnumber'));?>
    </div>
    <div class="form-group">
    <label for="name">账号</label>
    <?php echo $this->formRow($form->get('salaccount'));?>
    </div>
    <div class="form-group">
    <label for="name">密码</label>
    <?php echo $this->formRow($form->get('salpassword'));?>
    </div>
    <div class="form-group" style="text-align:center">
    <?php echo $this->formInput($form->get('submit')); ?>
    </div>
</fieldset>


<?php echo $this->form()->closeTag($form);?>