<div class="well btnshadow radius-circle" style="text-align:center"><h4><?php echo $homepage->getPageheaddata2();?></h4></div>

<br>

<div style="text-align:center">
<img class="btnshadow img-rounded" src="<?php echo $homepage->getPageheaddata1();?>" style="height:100px;width:120px;">
</div>


<hr>

<?php if ($appname=='androidcustomer'):?>
<div style="text-align:center">
<img class="img-rounded" src="/img/androidicon.png" style="height:100px;width:100px;">
</div>
<br>
<div style="text-align:center">
<a class="button blue bigrounded" href="https://www.oushelun.cn/appdownload/<?php echo $salonnumber;?>/Customer.apk">顾客App下载</a>
</div>
<?php elseif($appname=='androidcosmetologist'): ?>
<div style="text-align:center">
<img class="img-rounded" src="/img/androidicon.png" style="height:100px;width:100px;">
</div>
<br>
<div style="text-align:center">
<a class="button blue bigrounded" href="https://www.oushelun.cn/appdownload/<?php echo $salonnumber;?>/Cosmetologist.apk">美容师App下载</a>
</div>
<?php elseif($appname=='androidsalonboss'): ?>
<div style="text-align:center">
<img class="img-rounded" src="/img/androidicon.png" style="height:100px;width:100px;">
</div>
<br>
<div style="text-align:center">
<a class="button blue bigrounded" href="https://www.oushelun.cn/appdownload/<?php echo $salonnumber;?>/Salonboss.apk">院长App下载</a>
</div>
<?php elseif($appname=='ioscustomer'): ?>
<div style="text-align:center">
<img class="img-rounded" src="/img/appleicon.png" style="height:100px;width:100px;">
</div>
<br>
<div style="text-align:center">
<a class="button blue bigrounded" href="https://itunes.apple.com/cn/app/id1366546695?mt=8">顾客App下载</a>
<a style="display: none;" class="button blue bigrounded" href="itms-services://?action=download-manifest&url=https://www.oushelun.cn/appdownload/<?php echo $salonnumber;?>/Customerios.plist">顾客App下载</a>
</div>
<?php elseif($appname=='ioscosmetologist'): ?>
<div style="text-align:center">
<img class="img-rounded" src="/img/appleicon.png" style="height:100px;width:100px;">
</div>
<br>
<div style="text-align:center">
<a class="button blue bigrounded" href="https://itunes.apple.com/cn/app/id1380011236?mt=8">美容师App下载</a>
<a style="display: none;" class="button blue bigrounded" href="itms-services://?action=download-manifest&url=https://www.oushelun.cn/appdownload/<?php echo $salonnumber;?>/Cosmetologistios.plist">美容师App下载</a>
</div>
<?php elseif($appname=='iossalonboss'): ?>
<div style="text-align:center">
<img class="img-rounded" src="/img/appleicon.png" style="height:100px;width:100px;">
</div>
<br>
<div style="text-align:center">
<a class="button blue bigrounded" href="https://itunes.apple.com/cn/app/id1380141522?mt=8">院长App下载</a>
<a style="display: none;" class="button blue bigrounded" href="itms-services://?action=download-manifest&url=https://www.oushelun.cn/appdownload/<?php echo $salonnumber;?>/Salonbossios.plist">院长App下载</a>
</div>
<?php endif;?>