<div class="well btnshadow radius-circle" style="text-align:center"><h4>云巍生鲜</h4></div>

<br>

<div style="text-align:center">
<img class="btnshadow img-rounded" src="/appdownload/1/fruiticon.512x512.png" style="height:100px;width:120px;">
</div>


<hr>
<div style="text-align:center">
<img class="img-rounded" src="/img/appleicon.png" style="height:100px;width:100px;">
</div>
<br>
<div style="text-align:center">
<a class="button blue bigrounded" href="itms-services://?action=download-manifest&url=https://www.oushelun.cn/appdownload/1/fruitios.plist">云巍生鲜下载</a>
</div>