<div class="well">注：院长和美容师app已统一使用通用版，不再为美容院单独制作</div>
<div class="container">
   <div class="row">
   <h1 style="color:#cc0000;">android:</h1>
      <div class="col-md-4 col-lg-4">
      <span style="color:#696969;font-size:20px;">顾客APP:</span>
      <img alt="" style="width:50%;"  src="http://qr.topscan.com/api.php?text=https://www.oushelun.cn/cosmeticlogin/appdownload/123/androidcustomer&logo=39.105.36.168/salon/123/corporatelogo.png&gc=cc0000">
      </div>
      <div class="col-md-4 col-lg-4">
      <span style="color:#696969;font-size:20px;">院长APP:</span>
      <img alt="" style="width:50%;" src="http://qr.topscan.com/api.php?text=https://www.oushelun.cn/cosmeticlogin/appdownload/123/androidsalonboss&logo=39.105.36.168/salon/123/corporatelogo.png&gc=cc0000">
      </div>
      <div class="col-md-4 col-lg-4">
      <span style="color:#696969;font-size:20px;">美容师APP:</span>
      <img alt="" style="width:50%;" src="http://qr.topscan.com/api.php?text=https://www.oushelun.cn/cosmeticlogin/appdownload/123/androidcosmetologist&logo=39.105.36.168/salon/123/corporatelogo.png&gc=cc0000">
      </div>    
   </div>
   <hr>
   <div class="row">
   <h1 style="color:#EE3A8C;">ios:</h1>
      <div class="col-md-4 col-lg-4">
      <span style="color:#696969;font-size:20px;">顾客APP:</span>
      <img alt="" style="width:50%;" src="http://qr.topscan.com/api.php?text=https://www.oushelun.cn/cosmeticlogin/appdownload/123/ioscustomer&logo=39.105.36.168/salon/123/corporatelogo.png&gc=EE3A8C">
      </div>
      <div class="col-md-4 col-lg-4">
      <span style="color:#696969;font-size:20px;">院长APP:</span>
      <img alt="" style="width:50%;" src="http://qr.topscan.com/api.php?text=https://www.oushelun.cn/cosmeticlogin/appdownload/123/iossalonboss&logo=39.105.36.168/salon/123/corporatelogo.png&gc=EE3A8C">
      </div>
      <div class="col-md-4 col-lg-4">
      <span style="color:#696969;font-size:20px;">美容师APP:</span>
      <img alt="" style="width:50%;" src="http://qr.topscan.com/api.php?text=https://www.oushelun.cn/cosmeticlogin/appdownload/123/ioscosmetologist&logo=39.105.36.168/salon/123/corporatelogo.png&gc=EE3A8C">
      </div>    
   </div>
</div>