<div class="container">
   <div class="row">
   <h1 style="color:#cc0000;">android:</h1>
      <div class="col-md-4 col-lg-4">
      <h3 style="color:#696969;">顾客APP:</h3>
      <img alt=""  src="http://qr.topscan.com/api.php?text=https://www.oushelun.cn/cosmeticlogin/appdownload/<?php echo $id;?>/androidcustomer&logo=47.96.173.116<?php echo $homepage->getPageheaddata1();?>&gc=cc0000">
      </div>
      <div class="col-md-4 col-lg-4">
      <h3 style="color:#696969;">院长APP:</h3>
      <img alt="" src="http://qr.topscan.com/api.php?text=https://www.oushelun.cn/cosmeticlogin/appdownload/<?php echo $id;?>/androidsalonboss&logo=47.96.173.116<?php echo $homepage->getPageheaddata1();?>&gc=cc0000">
      </div>
      <div class="col-md-4 col-lg-4">
      <h3 style="color:#696969;">美容师APP:</h3>
      <img alt="" src="http://qr.topscan.com/api.php?text=https://www.oushelun.cn/cosmeticlogin/appdownload/<?php echo $id;?>/androidcosmetologist&logo=47.96.173.116<?php echo $homepage->getPageheaddata1();?>&gc=cc0000">
      </div>    
   </div>
   <hr>
   <div class="row">
   <h1 style="color:#EE3A8C;">ios:</h1>
      <div class="col-md-4 col-lg-4">
      <h3 style="color:#696969;">顾客APP:</h3>
      <img alt="" src="http://qr.topscan.com/api.php?text=https://www.oushelun.cn/cosmeticlogin/appdownload/<?php echo $id;?>/ioscustomer&logo=47.96.173.116<?php echo $homepage->getPageheaddata1();?>&gc=EE3A8C">
      </div>
      <div class="col-md-4 col-lg-4">
      <h3 style="color:#696969;">院长APP:</h3>
      <img alt=""  src="http://qr.topscan.com/api.php?text=https://www.oushelun.cn/cosmeticlogin/appdownload/<?php echo $id;?>/iossalonboss&logo=47.96.173.116<?php echo $homepage->getPageheaddata1();?>&gc=EE3A8C">
      </div>
      <div class="col-md-4 col-lg-4">
      <h3 style="color:#696969;">美容师APP:</h3>
      <img alt="" src="http://qr.topscan.com/api.php?text=https://www.oushelun.cn/cosmeticlogin/appdownload/<?php echo $id;?>/ioscosmetologist&logo=47.96.173.116<?php echo $homepage->getPageheaddata1();?>&gc=EE3A8C">
      </div>    
   </div>
</div>