<script type="text/javascript" src="/validjs/cosmetologistvalid.js"></script>

 <?php
 $form = $this->form;
 $url = $this->url('cosmetic', array('action' => 'cosmetologistedit', 'sub'=>$sub));
 $form->setAttribute('action', $url);
 $form->get('submitname')->setAttribute('value', '提交');
 $form->get('cosphone')->setAttribute('required', 'required');
 $form->get('cospassword')->setAttribute('required', 'required');
 $form->get('cosyears')->setAttribute('required', 'required');
 $form->prepare();

echo $this->form()->openTag($form);?>

 <fieldset>
    <legend>编辑美容师</legend>
	<div class="form-group">
		<div class="col-sm-12">
			<?php foreach ($salbranches as $salbranch):?>
			<input checked="checked" type="radio" name="salbranch" checked value="<?php echo $salbranch->getSalbranch();?>">
			<?php echo $salbranch->getSalname();?>
			<?php endforeach;?>
		</div>
	</div>
	<div class="form-group">
	
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosphone'));?>
			<?php if ($cosexist):?>
            <span style="color: red">账号已存在</span>
            <?php endif;?>
		</div>
	</div>
	<div class="form-group">
	
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cospassword'));?>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosname'));?>
		</div>
	</div>
		<div class="form-group">
	
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosaddress'));?>
		</div>
	</div>
	<div class="form-group">
	
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosposition'));?>
		</div>
	</div>
	<div class="form-group">
	
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosspeciality'));?>
		</div>
	</div>
	<div class="form-group">
	
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosyears'));?>
		</div>
	</div>
	<div class="form-group">
	
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosidentity'));?>
		</div>
	</div>
	<div class="form-group">
		
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosbirthday'));?>
		</div>
	</div>
			<?php echo $this->formhidden($form->get('cosphoto'));?>
			
    <div class="form-group">
	
		<div class="col-sm-4 col-md-4 col-lg-4">
			<img alt="" src="/img/234.jpg" class="picturechoose1 img1 img-thumbnail" style="wdith:200px;height:150px"> 
		</div>
	</div>
	
	<div class="form-group">
		<div class=" col-sm-4 col-md-4 col-lg-4">
			<?php echo $this->formInput($form->get('submitname')); ?>
		</div>
	</div>
</fieldset>

 <?php
 echo $this->form()->closeTag($form);?>
 
<script type="text/javascript">
//设图片src为已有的值
 $(function (){
 	$(".picturechoose1").attr("src",$("#cosphoto").val());
 	
 })
</script>

<script>
//提交图片
$(function(){
	$("#submitid").click(function(){
		$("#cosphoto").val($(".picturechoose1").attr("src"));
		})
})
</script>
<?php //TODO图片选择器
include_once 'public/php/picturechoice.phtml';?>