 <?php
 $title = '删除美容师';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>确认想删除名为
   '<?php echo $this->escapeHtml($cosmetologist->getCosname()); ?>' 的美容师吗?
 </p>
 <?php
 $url = $this->url('cosmetic', array('action' => 'cosmetologistdelete','sub'=>$sub)); ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
   <input type="submit" name="del" value="Yes" />
   <input type="submit" name="del" value="No" />
 </div>
 </form>