<script type="text/javascript" src="/validjs/cosmetologistvalid.js"></script>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cosmetic', array(
    'action' => 'cosmetologistadd'
)));
$form->get('cosphone')->setAttribute('required', 'required');
$form->get('cospassword')->setAttribute('required', 'required');
$form->get('cosyears')->setAttribute('required', 'required');
$form->get('submitname')->setAttribute('value', '提交');
$form->prepare();echo $this->form()->openTag($form);?>

 <fieldset>
    <legend>添加美容师</legend>
	<div class="form-group">
		<div class="col-sm-12">
			<?php foreach ($salbranches as $salbranch):?>
			<input checked="checked" type="radio" name="salbranch" value="<?php echo $salbranch->getSalbranch();?>">
			<?php echo $salbranch->getSalname();?>
			<?php endforeach;?>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosphone'));?>
			<?php if ($cosexist):?>
            <span style="color: red">账号已存在</span>
            <?php endif;?>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cospassword'));?>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosname'));?>
		</div>
	</div>
		<div class="form-group">
	
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosaddress'));?>
		</div>
	</div>
	<div class="form-group">
	
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosposition'));?>
		</div>
	</div>
	<div class="form-group">
	
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosspeciality'));?>
		</div>
	</div>
	<div class="form-group">
	
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosyears'));?>
		</div>
	</div>
	<div class="form-group">
	
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosidentity'));?>
		</div>
	</div>
		<div class="form-group">
		
		<div class="col-sm-6 col-md-6 col-lg-6">
			<?php echo $this->formRow($form->get('cosbirthday'));?>
		</div>
	</div>
			<?php echo $this->formhidden($form->get('cosphoto'));?>
			
    <div class="form-group">
	
		<div class="ol-sm-4 col-md-4 col-lg-4">
			<img  alt="" src="/img/choose.jpg" class="picturechoose1 img1 img-thumbnail" style="wdith:200px;height:150px"> 
		</div>
	</div>
	
	<div class="form-group">
		<div class="col-sm-10 col-md-10 col-lg-10">
			<?php echo $this->formInput($form->get('submitname')); ?>
		</div>
	</div>
</fieldset>
<?php echo $this->form()->closeTag($form);?>

<script>
//提交图片
$(function(){
	$("#submitid").click(function(){
		$("#cosphoto").val($(".picturechoose1").attr("src"));
		})
})
</script>
<?php //TODO图片选择器
include_once 'public/php/picturechoice.phtml';?>
