<?php
 $title = '会员设定';
 $this->headTitle($title);
 ?>
 <h5><?php echo $this->escapeHtml($title); ?></h5>
 <?php
 $form = $this->form;
 $url = $this->url('cosmetic', array('action' => 'cusleveltypeedit', 'sub'=>$sub));
 $form->setAttribute('action', $url);
 $form->get('submit')->setAttribute('value', '编辑');
 $form->prepare();

echo $this->form()->openTag($form);

echo $this->formhidden($form->get('cusid'));?>

<div class="form-group">
    <label for="name">会员级别</label>
    <?php echo $this->formRow($form->get('cuslevel'));?>
</div>
<div class="form-group">
    <label for="name">需求类型</label>
    <?php echo $this->formRow($form->get('custype'));?>
</div>
<div class="form-group">
    <label for="name">指定分院</label>
    <?php echo $this->formRow($form->get('cussalonbranch'));?>
</div>

 <div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
 <?php
 echo $this->form()->closeTag($form);?>
