<?php
$title = 'Add new task';
$this->headTitle($title);
?>
<h5><?php echo $this->escapeHtml($title); ?></h5>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cosmetic', array(
    'action' => 'customeradd'
)));
$form->get('submit')->setAttribute('value', 'Add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('cusid'));
echo $this->formhidden($form->get('salnumber'));
echo $this->formRow($form->get('cusnumber'));
echo $this->formRow($form->get('cusphone'));
echo $this->formRow($form->get('cuspassword'));
echo $this->formRow($form->get('cusname'));
echo $this->formRow($form->get('cusidentity'));
echo $this->formRow($form->get('cusaddress'));
echo $this->formRow($form->get('cusphoto'));
echo $this->formRow($form->get('cuspoints'));
echo $this->formRow($form->get('cusphotof'));
echo $this->formRow($form->get('cuspoints'));
echo $this->formRow($form->get('cuslevel'));
echo $this->formRow($form->get('custype'));

?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
var_dump($post);