 <?php
 $title = '删除按钮';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>确定删除按钮
   '<?php echo $this->escapeHtml($custombutton->getButtonname()); ?>' 吗?
 </p>
 <?php
 $url = $this->url('cosmetic', array('action' => 'custombuttondelete','sub'=>$sub)); ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
   <input type="submit" name="del" value="Yes" />
   <input type="submit" name="del" value="No" />
 </div>
 </form>