<?php
$title = '添加分类';
$this->headTitle($title);
?>
<h5><?php echo $this->escapeHtml($title); ?></h5>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cosmetic', array(
    'action' => 'demandclassifyseriesadd','sub'=>$sub
)));
$form->get('submit')->setAttribute('value', '提交');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('dcsid'));
echo $this->formhidden($form->get('salnumber'));
echo $this->formRow($form->get('dcscolumn'));
echo $this->formRow($form->get('dcsname'));
echo $this->formhidden($form->get('dcsbackground'));
?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);?>


<div class="form-group">
		<div>
		    <h3>背景图选择</h3>
			<img alt="" src="/img/choose.jpg" class="picturechoose1 img1" style="wdith:200px;height:150px"> 
		</div>
	</div>
 <script>
//提交图片
$(function(){
	$("#submit").click(function(){
		$("#dcsbackground").val($(".picturechoose1").attr("src"));
		})
})
</script>
 <?php //图片选择器
include_once 'public/php/picturechoice.phtml';?>