 <?php
 $title = '删除分类';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>你确定要删除分类
   '<?php echo $this->escapeHtml($demandclassifyseries->getDcsname()); ?>' 吗?
 </p>
 <?php
 $url = $this->url('cosmetic', array('action' => 'demandclassifyseriesdelete','sub'=>$sub)); ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
   <input type="submit" name="del" value="Yes" />
   <input type="submit" name="del" value="No" />
 </div>
 </form>