<div style="text-align:center">
<img src="/meicon/corporatelogo.png" style="height:100px;width:120px;">
</div>


<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cosmeticlogin', array(
    'action' => 'login','sub'=>$sub
)));
$form->get('submit')->setAttribute('value', '登陆');
$form->get('submit')->setAttribute('class', 'button blue bigrounded');
$form->prepare();
echo $this->form()->openTag($form);?>
<fieldset>
    <legend>账号登陆</legend>
    <label for="name" style="color:red;"><?php echo $result;?></label>
	<div class="form-group">
    <label for="name">账号</label>
    <?php echo $this->formRow($form->get('salaccount'));?>
    </div>
    <div class="form-group">
    <label for="name">密码</label>
    <?php echo $this->formRow($form->get('salpassword'));?>
    </div>
    <div class="form-group" style="text-align:center">
    <?php echo $this->formInput($form->get('submit')); ?>
    </div>
</fieldset>
<?php echo $this->form()->closeTag($form);?>
