
      <div class="list">
        <label class="item item-input">
          <input type="text" placeholder="First Name">
        </label>
        <label class="item item-input">
          <input type="text" placeholder="Last Name">
        </label>
        <label class="item item-input">
          <textarea placeholder="Comments"></textarea>
        </label>
      </div>
      <div class="padding">
        <button class="button button-block button-positive">Submit</button>
      </div>
    
<link href="https://cdn.bootcss.com/ionic/1.3.2/css/ionic.css" rel="stylesheet">