 <?php
 $title = '删除通知';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>你确定要删除通知
   '<?php echo $this->escapeHtml($notification->getNotitle()); ?>' 吗?
 </p>
 <?php
 $url = $this->url('cosmetic', array('action' => 'notificationinfodelete', 'sub'=>$id)); ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
   <input type="submit" name="del" value="Yes" />
   <input type="submit" name="del" value="No" />
 </div>
 </form>