<script type="text/javascript" src="/validjs/notificationinfovalid.js"></script>



<?php
 $title = '编辑通知';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $url = $this->url('cosmetic', array('action' => 'notificationinfoedit', 'sub' => $sub));
 $form->setAttribute('action', $url);
 $form->get('submitname')->setAttribute('value', '编辑');
 $form->get('nolink')->setAttribute('class', 'form-control linkinput1');
 $form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formhidden($form->get('salnumber'));?>
<div class="form-group"><label>标题</label><?php
echo $this->formRow($form->get('notitle'));?></div>
<div class="form-group"><label>内容</label><?php
echo $this->formRow($form->get('nocontent'));?></div>
<div class="form-group"><label>链接</label><?php
echo $this->formRow($form->get('nolink'));
?><span class="input-group-btn">
						<button class="btn btn-default linkchoose1" type="button" >
							<span class="ui-icon  ui-icon-link"></span>
						</button>
					</span></div>
 <div>
 <?php echo $this->formInput($form->get('submitname')); ?>
 </div>
 <?php
 echo $this->form()->closeTag($form);?>
 
 <?php //链接选择器
include_once 'public/php/linkchoice.phtml';?>