<script type="text/javascript" src="/js/js.pickcolor.js"></script>

<?php
$title = '添加页面';
$this->headTitle($title);
?>
<h5><?php echo $this->escapeHtml($title); ?></h5>


<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cosmetic', array(
    'action' => 'pageadd'
)));
$form->get('submit')->setAttribute('value', '提交');
$form->get('pagetype')->setAttribute('class', 'form-control');
$form->get('pagetype')->setAttribute('id', 'pagetype');
$form->get('pagetype')->setAttribute('value', '活动');
$form->get('pagecondition')->setAttribute('value', '显示');
$form->get('pageexpiration')->setAttribute('class', 'form-control');
$form->get('pagename')->setAttribute('class', 'form-control');
$form->get('pagecolor')->setAttribute('class', 'form-control');
$form->get('pagecolor')->setAttribute('onclick', 'initColorPicker();return false');
$form->get('pagepaddingtop')->setAttribute('class', 'form-control');
$form->get('pagepaddinglr')->setAttribute('class', 'form-control');
$form->get('pagepaddingbottom')->setAttribute('class', 'form-control');
$form->get('pageheaddata1')->setAttribute('class', 'form-control');
$form->get('pageheaddata2')->setAttribute('class', 'form-control');
$form->get('pagepaddingtop')->setAttribute('value', '0');
$form->get('pagepaddinglr')->setAttribute('value', '0');
$form->get('pagepaddingbottom')->setAttribute('value', '0');
$form->get('releasetime')->setAttribute('value', '0000-00-00 00:00:00');
$form->get('pageheaddata3')->setAttribute('class', 'form-control');
$form->prepare();
echo $this->form()->openTag($form);?>
<div class="form-group"><?php
echo $this->formHidden($form->get('pageid'));?></div>
<div class="form-group"><?php
echo $this->formhidden($form->get('salnumber'));?></div>
<div class="form-group"><?php
echo $this->formhidden($form->get('releasetime'));?></div>
<div class="form-group"><?php
echo $this->formhidden($form->get('modificationtime'));?></div>


<div class="form-group"><label>页面类型</label><?php
echo $this->formhidden($form->get('pagetype'));?>
<div>
<button type="button" class="btn btn-default btn-lg pagetypebtn active" id="pagetypebtn1">活动页</button>
<button type="button" class="btn btn-default btn-lg pagetypebtn" id="pagetypebtn2">动态页</button>
</div>
</div>

<div class="form-group"><label>页面状态</label><?php
echo $this->formhidden($form->get('pagecondition'));
?>
<div>
<button type="button" class="btn btn-default btn-lg pageconditionbtn active" id="pageconditionbtn1">显示</button>
<button type="button" class="btn btn-default btn-lg pageconditionbtn" id="pageconditionbtn2">隐藏</button>
</div>
</div>

<div class="form-group" id="expiredate"><label>截止日期</label>
<?php echo $this->formRow($form->get('pageexpiration'));?></div>

<br>
<div class="form-group"><label>简介</label><?php
echo $this->formtextarea($form->get('pageheaddata3'));
?></div>


<div class="form-group"><label>页面展示图（与视频二选一填写即可）</label>
<?php echo $this->formhidden($form->get('pageheaddata1'));?>
<br>
<img alt="" src="/img/choose.jpg" class="picturechoose1 img1 img-thumbnail" style="wdith:200px;height:150px">
<button type="button" id="deletepicture">去除图片</button>
</div>
<div class="form-group"><label>页面展示视频</label><?php
echo $this->formhidden($form->get('pageheaddata2'));?></div>
<br>
<video width="320"  controls class="videosrc embed-responsive-item picturechoose2" src="/salon/test.mp4">
</video>
<button type="button" id="deletevideo">去除视频</button>


<div class="form-group"><label>页面名称</label><?php
echo $this->formRow($form->get('pagename'));?></div>
<div class="form-group"><label>页面主题颜色</label><?php
echo $this->formRow($form->get('pagecolor'));?></div>
<div class="form-group"><label>模块上间距</label><?php
echo $this->formRow($form->get('pagepaddingtop'));?></div>
<div class="form-group"><label>模块左右间距</label><?php
echo $this->formRow($form->get('pagepaddinglr'));?></div>
<div class="form-group"><label>模块下间距</label><?php
echo $this->formRow($form->get('pagepaddingbottom'));?></div>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);?>
<script>
$(document).ready(function(){
	$("#pagetypebtn1").click(function(){
          $("#pagetype").val("活动");
          $(".pagetypebtn").removeClass("active");
          $("#pagetypebtn1").addClass("active");
          $("#expiredate").show();
		});
	$("#pagetypebtn2").click(function(){
        $("#pagetype").val("动态");
        $(".pagetypebtn").removeClass("active");
        $("#pagetypebtn2").addClass("active");
        $("#expiredate").hide();
		});
	$("#pageconditionbtn1").click(function(){
        $("#pagecondition").val("显示");
        $(".pageconditionbtn").removeClass("active");
        $("#pageconditionbtn1").addClass("active");
		});
	$("#pageconditionbtn2").click(function(){
      $("#pagecondition").val("隐藏");
      $(".pageconditionbtn").removeClass("active");
      $("#pageconditionbtn2").addClass("active");
		});
})
</script>
<script>
$(document).ready(function(){
	$("#deletepicture").click(function(){
		$(".picturechoose1").attr("src","/img/choose.jpg");
		});
	$("#deletevideo").click(function(){
		$(".picturechoose2").attr("src","");
		});
})
</script>
<script>
//提交图片
$(function(){
	$("#submit").click(function(){
		$("#pageheaddata1").val($(".picturechoose1").attr("src"));
		$("#pageheaddata2").val($(".picturechoose2").attr("src"));
		})
})
</script>
<?php //TODO图片选择器
include_once 'public/php/picturechoice.phtml';?>


<script type="text/javascript">
function initColorPicker(){
 picker = new colorPicker('pagecolor');
}
</script>