<link href="/css/fileinput.min.css" media="screen" rel="stylesheet" type="text/css">
<script src="/js/fileinput.min.js"></script>
<script src="/js/fileinput.zh.js"></script>


<?php
$title = '添加图片';
$this->headTitle($title);
?>
<h5><?php echo $this->escapeHtml($title); ?></h5>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cosmetic', array(
    'action' => 'pictureadd','sub'=>$sub
)));
$form->get('submit')->setAttribute('value', '提交');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('picturefile'));
?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>

 
<script>
$(document).on('ready', function() {
    $("#picturefile").fileinput({
    	language: 'zh', //设置语言
        showUpload: false,
        maxFileCount: 10,
        mainClass: "input-group-normal"
    });
});
</script>