  <?php
$title = 'My task list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

 <p><a href="<?php echo $this->url('cosmetic', array('management',
         'action'=>'prizeadd'));?>">添加促销活动</a></p>


 <table class="table table-hover">
 <tr>
     <th>Task</th>
     <th>Created</th>
     
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($prizes as $prize): ?>
 
 <tr>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('management','action'=>'prizeedit','sub'=>$prize->getPriid()));?>">
             <?php echo $this->escapeHtml($prize->getPriid()); ?></a>
     </td>
     <td><?php echo $this->escapeHtml($prize->getProdtitle()); ?></td>
     
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('action'=>'prizedelete','sub'=>$prize->getPriid()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>

