<?php
$title = '组合分类管理';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><?php echo $product->getProdtitle();?></p>
 <p><a href="<?php echo $this->url('cosmetic', array(
         'action'=>'productcombinationadd','sub'=>$sub));?>">添加组合分类</a></p>


 <table class="table table-hover">
 <tr>
     <th>组合分类名</th>
     <th>价格</th>
     <th>图片</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($productcombinations as $productcombination): ?>
 
 <tr>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('action'=>'productcombinationedit','sub'=>$sub,'third'=>$productcombination->getProductcombinationid()));?>">
             <?php echo $this->escapeHtml($productcombination->getProductcombinationname()); ?></a>
     </td>
     <td><?php echo $this->escapeHtml($productcombination->getProductcombinationprice()); ?></td>
     <td><img src="<?php echo $this->escapeHtml($productcombination->getProductcombinationpicture()); ?>" style="width:50px;height:30px"></td>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('action'=>'productcombinationdelete','sub'=>$sub,'third'=>$productcombination->getProductcombinationid()));?>">删除</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>

