 <?php
 $title = '删除组合分类';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>您确定要删除组合分类:
   '<?php echo $this->escapeHtml($productcombination->getproductcombinationname()); ?>' 吗?
 </p>
 <?php
 $url = $this->url('cosmetic', array('action' => 'productcombinationdelete','sub'=>$sub,'third'=>$third)); ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
   <input type="submit" name="del" value="Yes" />
   <input type="submit" name="del" value="No" />
 </div>
 </form>