<?php
$title = 'Add new task';
$this->headTitle($title);
?>
<h5><?php echo $this->escapeHtml($title); ?></h5>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cosmetic', array(
    'action' => 'promotionadd'
)));
$form->get('submit')->setAttribute('value', 'Add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('promid'));
echo $this->formhidden($form->get('salnumber'));
echo $this->formhidden($form->get('cosnumber'));
echo $this->formhidden($form->get('cusnumber'));
echo $this->formhidden($form->get('promthumbnail'));
echo $this->formRow($form->get('promsort'));
echo $this->formRow($form->get('promauthor'));
echo $this->formRow($form->get('promtitle'));
echo $this->formRow($form->get('promdetail'));
echo $this->formRow($form->get('promphoto1'));
echo $this->formRow($form->get('promphoto2'));
echo $this->formRow($form->get('promphoto3'));
echo $this->formRow($form->get('promphoto4'));
echo $this->formRow($form->get('promphoto5'));
echo $this->formRow($form->get('promphoto6'));
echo $this->formRow($form->get('promphoto7'));
echo $this->formRow($form->get('promphoto8'));
echo $this->formRow($form->get('promphoto9'));
echo $this->formRow($form->get('promphoto10'));
echo $this->formRow($form->get('promphoto1f'));
echo $this->formRow($form->get('promphoto2f'));
echo $this->formRow($form->get('promphoto3f'));
echo $this->formRow($form->get('promphoto4f'));
echo $this->formRow($form->get('promphoto5f'));
echo $this->formRow($form->get('promphoto6f'));
echo $this->formRow($form->get('promphoto7f'));
echo $this->formRow($form->get('promphoto8f'));
echo $this->formRow($form->get('promphoto9f'));
echo $this->formRow($form->get('promphoto10f'));
echo $this->formRow($form->get('promsrc1'));
echo $this->formRow($form->get('promsrc2'));
echo $this->formRow($form->get('promsrc3'));
echo $this->formRow($form->get('promsrc4'));
echo $this->formRow($form->get('promsrc5'));
echo $this->formRow($form->get('promsrc6'));
echo $this->formRow($form->get('promsrc7'));
echo $this->formRow($form->get('promsrc8'));
echo $this->formRow($form->get('promsrc9'));
echo $this->formRow($form->get('promsrc10'));
echo $this->formRow($form->get('promvideo'));
echo $this->formRow($form->get('promvideof'));
echo $this->formRow($form->get('promdescription1'));
echo $this->formRow($form->get('promdescription2'));
echo $this->formRow($form->get('promdescription3'));
echo $this->formRow($form->get('promdescription4'));
echo $this->formRow($form->get('promdescription5'));
echo $this->formRow($form->get('promdescription6'));
echo $this->formRow($form->get('promdescription7'));
echo $this->formRow($form->get('promdescription8'));
echo $this->formRow($form->get('promdescription9'));
echo $this->formRow($form->get('promdescription10'));
echo $this->formRow($form->get('promoverdue'));
?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
var_dump($post);