  <?php
$title = '优惠券管理';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

 <p><a href="<?php echo $this->url('cosmetic', array('management',
         'action'=>'saloncouponissueadd'));?>">添加优惠券</a></p>


 <table class="table table-hover">
 <tr>
     <th>id</th>
     <th>用户编号</th>
     <th>限制</th>
     <th>金额</th>
     <th>截止日期</th>
     <th>每人限领次数</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($saloncouponissues as $saloncouponissue): ?>
 
 <tr>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('management','action'=>'saloncouponissueedit','sub'=>$saloncouponissue->getSciid()));?>">
             <?php echo $this->escapeHtml($saloncouponissue->getSciid()); ?></a>
     </td>
     <td><?php echo $this->escapeHtml($saloncouponissue->getCusid()); ?></td>
     <td><?php echo $this->escapeHtml($saloncouponissue->getScirestriction()); ?></td>
     <td><?php echo $this->escapeHtml($saloncouponissue->getScimoney()); ?></td>
     <td><?php echo $this->escapeHtml($saloncouponissue->getSciavailable()); ?></td>
     <td><?php echo $this->escapeHtml($saloncouponissue->getScitimes()); ?></td>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('action'=>'saloncouponissuedelete','sub'=>$saloncouponissue->getSciid()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>

