<script type="text/javascript" src="/validjs/saloncouponissuevalid.js"></script>


	<script type="text/javascript" src="/datetimepicker/jquery-ui-timepicker-addon.js"></script>
    <script type="text/javascript" src="/datetimepicker/jquery-ui-timepicker-zh-CN.js"></script>

     <script type="text/javascript">
     //优惠券截止日期选择器
    $(function () {
        $(".ui_timepicker").datetimepicker({
            //showOn: "button",
            //buttonImage: "./css/images/icon_calendar.gif",
            //buttonImageOnly: true,
            showSecond: true,
            timeFormat: 'hh:mm:ss',
            stepHour: 1,
            stepMinute: 1,
            stepSecond: 1
        })
    })
    </script>


<?php
$title = '修改优惠券';
$this->headTitle($title);
?>
<h5><?php echo $this->escapeHtml($title); ?></h5>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cosmetic', array(
    'action' => 'saloncouponissueadd'
)));
$form->get('submitname')->setAttribute('value', '修改');
$form->get('sciavailable')->setAttribute('readonly', 'readonly');
$form->get('scirestriction')->setAttribute('required', 'required');
$form->get('scimoney')->setAttribute('required', 'required');
$form->get('sciavailable')->setAttribute('required', 'required');
$form->get('scitimes')->setAttribute('required', 'required');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('sciid'));  echo "<br>";
echo $this->formhidden($form->get('salnumber')); echo "<br>";
?>
<div class="form-group">
<label for="name">用户编号</label>
			<?php echo $this->formRow($form->get('cusid'));?>		
</div>
<div class="form-group">
<label for="name">所需消费金额</label>
			<?php echo $this->formRow($form->get('scirestriction'));?>		
</div>
<div class="form-group">
<label for="name">优惠劵金额</label>
			<?php echo $this->formRow($form->get('scimoney'));?>		
</div>
<div class="form-group">
<label for="name">有效期</label>
			<?php echo $this->formRow($form->get('sciavailable'));?>		
</div>
<div class="form-group">
<label for="name">每人限领次数</label>
			<?php echo $this->formRow($form->get('scitimes'));?>		
</div>
<div>
 <?php echo $this->formInput($form->get('submitname')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);