  <?php
$title = '美容院分院管理';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

 <p><a href="<?php echo $this->url('cosmetic', array('management',
         'action'=>'salonadd'));?>">添加分院</a></p>

 <table class="table table-hover">
 <tr>
     <th>分店号</th>
     <th>美院名</th>
     <th>美院门头</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($salons as $salon): ?>
 
 <tr>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('management','action'=>'salonedit','sub'=>$salon->getSalid()));?>">
             <?php echo $this->escapeHtml($salon->getSalbranch()); ?></a>
     </td>
     <td><?php echo $this->escapeHtml($salon->getSalname()); ?></td>
     
     <td><img src="<?php echo $this->escapeHtml($salon->getSalphoto1()); ?>" style="height: 50px;width:70px;"></td>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('action'=>'salondelete','sub'=>$salon->getSalid()));?>">删除</a>
     </td>
     
 </tr>
 <?php endforeach; ?>
 </table>