  <?php
$title = 'My task list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

 <p><a href="<?php echo $this->url('cosmetic', array('management',
         'action'=>'stageadd'));?>">添加幻灯片活动</a></p>


 <table class="table">
 <tr>
     <th>Task</th>
     <th>Created</th>
     
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($stages as $stage): ?>
 
 <tr>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('management','action'=>'stageedit','sub'=>$stage->getStaid()));?>">
             <?php echo $this->escapeHtml($stage->getStaid()); ?></a>
     </td>
     <td><?php echo $this->escapeHtml($stage->getStacomment()); ?></td>
     
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('action'=>'stagedelete','sub'=>$stage->getStaid()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>

