	<script type="text/javascript" src="/datetimepicker/jquery-ui-timepicker-addon.js"></script>
    <script type="text/javascript" src="/datetimepicker/jquery-ui-timepicker-zh-CN.js"></script>

     <script type="text/javascript">
     //交易完成日期选择器
    $(function () {
        $(".gmtclosebegin").datetimepicker({
            //showOn: "button",
            //buttonImage: "./css/images/icon_calendar.gif",
            //buttonImageOnly: true,
            showSecond: true,
            timeFormat: 'hh:mm:ss',
            stepHour: 1,
            stepMinute: 1,
            stepSecond: 1
        })
        $(".gmtclosefinish").datetimepicker({
            //showOn: "button",
            //buttonImage: "./css/images/icon_calendar.gif",
            //buttonImageOnly: true,
            showSecond: true,
            timeFormat: 'hh:mm:ss',
            stepHour: 1,
            stepMinute: 1,
            stepSecond: 1
        })
    })
    </script>



<?php
$title = '订单';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<form class="form-inline" role="form" action="<?php echo $this->url('cosmetic', array('action'=>'treatment'));?>" method="get">
  <div class="form-group" style="padding:5px;">
    <label  for="name">产品</label>
    <input type="text" class="form-control" name="prodtitle"  placeholder="请输入产品名称" value="<?php echo $_GET['prodtitle'];?>">
  </div>
  <div class="form-group" style="padding:5px;">
    <label for="name">订单号</label>
    <input type="text" class="form-control" name="orderid" placeholder="请输入订单号" value="<?php echo $_GET['orderid'];?>">
  </div>
  <div class="form-group" style="padding:5px;">
    <label  for="name">顾客</label>
    <input type="text" class="form-control" name="cusname" placeholder="请输顾客姓名" value="<?php echo $_GET['cusname'];?>">
  </div>
  <div class="form-group" style="padding:5px;">
    <label  for="name">成交日期</label>
    <input type="text" class="form-control gmtclosebegin" name="gmtclosebegin" placeholder="选择时间范围起始" value="<?php echo $_GET['gmtclosebegin'];?>">-
    <input type="text" class="form-control gmtclosefinish" name="gmtclosefinish" placeholder="选择时间范围结束" value="<?php echo $_GET['gmtclosefinish'];?>">
  </div>
  <div class="form-group" style="padding:5px;">
    <label for="name">交易状态</label>
<div class="radio">
    <label>
        <input type="radio" name="trestate" id="alltrestate" value="" checked>全部
    </label>
</div>
<div class="radio">
    <label>
        <input type="radio" name="trestate" id="optionsRadios1" value="nonpayment">未付款
    </label>
</div>
<div class="radio">
    <label>
        <input type="radio" name="trestate" id="optionsRadios2" value="paid">已付款
    </label>
</div>
  </div>
  <button type="submit" class="btn btn-default">提交</button>
</form>

<?php

?>
 <table class="table table-hover">
 <caption>订单数：<?php echo count($carscount);?></caption>
 <tr>
     <th>订单号</th>
     <th>&nbsp;</th>
     <th>名称</th>
     <th>交易金额</th>
     <th>数量</th>
     <th>买家</th>
     <th>交易状态</th>
 </tr>
 <?php foreach ($cars as $car):?>
 <tr>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('management','action'=>'treatmentedit','sub'=>$car['treid']));?>">
             <?php echo $this->escapeHtml($car['orderid']); ?></a>
             <p><?php echo $car['gmtclose'];?></p>
     </td>
     <td><img alt="" style="height:50px;width:50px;" src="<?php echo $car['productcombinationpicture'];?>"></td>
     <td><p><?php echo $car['prodtitle'];?></p>
     <p><?php echo $car['productcombinationname'];?></p>
     </td>
     <td><p style="color:red;"><?php echo $car['treprice'];?></p></td>
     <td><?php echo $car['productquantity'];?></td>
     <td><?php echo $car['cusname'];?></td>
     <td>
     <?php 
     if ($car['trestate']=="paid"){
         echo "已付款";
     }
     elseif($car['trestate']=="nonpayment"){
         echo "未付款";
         };
      ?>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>

<?php echo $this->paginationControl($cars,
                                    'Sliding',
                                    'paginatortreatment', array('route' => 'cosmetic')); ?>