<?php
if ($_POST['third']==null):
$dir2 = "public/salon/".$id."/".$_POST['sub'];
$dir3 = iconv('utf-8', 'gbk', $dir2);
$file = scandir($dir3);
 $photo=array();
 $directory=array();
 foreach ($file as $filegb): 
 $filesrc=iconv("GB2312","UTF-8",$filegb);
 if(substr(strrchr($filesrc, '.'), 1)==null){
     array_push($directory,$filesrc);
 }else{array_push($photo,$filesrc);}
 endforeach; ?> 
 
 
     <table class="table">
		<caption>点击图片进行选择</caption>
		<thead>
			<tr>
				<th>预览</th>
				<th>名称</th>
			</tr>

		</thead>
		
		<tbody id="rootdir1">
        <?php for($i=0;$i<count($photo);$i++):
        $endimg=explode('.', $photo[$i]);
        if(end($endimg)=="jpg"||end($endimg)=="png"||end($endimg)=="gif"):?>
            <tr>
				<td><img src="<?php echo '/salon/'.$id."/".$_POST['sub'].'/'.$photo[$i]; ?>"
					onclick="copyfilesrc1('<?php echo '/salon/'.$id."/".$_POST['sub'].'/'.$photo[$i]; ?>')"
					alt="Smiley face" width="60" height="30" class="imgchoose" data-imgnumber=""></td>
				<td><?php echo $photo[$i]; ?></td>
			</tr>
			<?php elseif (end($endimg)=="mp4"):?>
			<tr>
				
			    <td>
                     <video width="160" height="120" controls class="imgchoose" data-imgnumber="" onclick="copyfilesrc1('<?php echo '/salon/'.$id."/".$_POST['sub'].'/'.$photo[$i]; ?>')">
                     <source src="<?php echo '/salon/'.$id."/".$_POST['sub'].'/'.$photo[$i]; ?>" type="video/mp4">
                    </video>
               </td>
				<td><?php echo $photo[$i]; ?></td>
			</tr>
			<?php endif;?>
       <?php endfor; ?>
       </tbody>
     </table>
<?php else:
$dir2 = "public/salon/".$id."/".$_POST['sub']."/".$_POST['third'];
$dir3 = iconv('utf-8', 'gbk', $dir2);
$file = scandir($dir3);
 $photo=array();
 $directory=array();
 foreach ($file as $filegb): 
 $filesrc=iconv("GB2312","UTF-8",$filegb);
 if(substr(strrchr($filesrc, '.'), 1)==null){
     array_push($directory,$filesrc);
 }else{array_push($photo,$filesrc);}
 endforeach; ?> 
 
 
     <table class="table">
		<caption>点击图片进行选择</caption>
		<thead>
			<tr>
				<th>预览</th>
				<th>名称</th>
			</tr>

		</thead>
		
		<tbody id="rootdir1">
        <?php for($i=0;$i<count($photo);$i++):
        $endimg=explode('.', $photo[$i]);
        if(end($endimg)=="jpg"||end($endimg)=="png"||end($endimg)=="gif"):?>
            <tr>
				<td><img src="<?php echo '/salon/'.$id."/".$_POST['sub']."/".$_POST['third'].'/'.$photo[$i]; ?>"
					onclick="copyfilesrc1('<?php echo '/salon/'.$id."/".$_POST['sub']."/".$_POST['third'].'/'.$photo[$i]; ?>')"
					alt="Smiley face" width="60" height="30" class="imgchoose" data-imgnumber=""></td>
				<td><?php echo $photo[$i]; ?></td>
			</tr>
			<?php elseif (end($endimg)=="mp4"):?>
			<tr>
				
			    <td>
                     <video width="160" height="120" controls class="imgchoose" data-imgnumber="" onclick="copyfilesrc1('<?php echo '/salon/'.$id."/".$_POST['sub']."/".$_POST['third'].'/'.$photo[$i]; ?>')">
                     <source src="<?php echo '/salon/'.$id."/".$_POST['sub']."/".$_POST['third'].'/'.$photo[$i]; ?>" type="video/mp4">
                    </video>
               </td>
				<td><?php echo $photo[$i]; ?></td>
			</tr>
			<?php endif;?>
       <?php endfor; ?>
       </tbody>
     </table>
<?php endif;?>