<?php //TODO 发布?>
<script>
//发布
$(function() {
    $( "#immediatelyrelease" ).click(function() {
       var valuearray=new Array();
       //活动和动态页的页头是放的预览图或视频，相当于初始化，发布时才不会变空
         $pageheaddata1="<?php echo $page->getPageheaddata1();?>";
	     $pageheaddata2="<?php echo $page->getPageheaddata2();?>";
	     $pageheaddata3="<?php echo $page->getPageheaddata3();?>";
	     $pageheaddata4="<?php echo $page->getPageheaddata4();?>";
	     $pageheaddata5="<?php echo $page->getPageheaddata5();?>";
       for(var i=0;i<$("#sortable li").length;i++){
    	  var li=$("#sortable li").eq(i);
    	   switch(li.attr("data-type"))
    	   {
    	       case "headpagerow":
        	     $pageheaddata1=$("#headpageicon").attr("src");
        	     $pageheaddata2=$("#headpagename").html();
        	     $pageheaddata3=$("#pagehead").attr("data-backgroundimg");
        	     $pageheaddata4=$("#pagehead").attr("data-href");
        	     $pageheaddata5="";
  	               break;
    	       case "singlerow":
    	    	  var onerow= [li.attr("data-type"),
    	    	               li.find(".singlea").attr("data-href"),li.find(".singleimg").attr("src")];
    	    	  valuearray.push(onerow);
    	           break;
    	       case "doublerow":
    	    	   var onerow= [li.attr("data-type"),
    	    	                li.find(".doublea1").attr("data-href"),li.find(".doubleimg1").attr("src"),
    	    	                li.find(".doublea2").attr("data-href"),li.find(".doubleimg2").attr("src")];
     	    	  valuearray.push(onerow);
    	           break;
    	       case "swiperrow":
    	    	   var onerow= [li.attr("data-type"),
    	    	                li.find(".swipera1").attr("data-href"),li.find(".swiperimg1").attr("src"),
    	    	                li.find(".swipera2").attr("data-href"),li.find(".swiperimg2").attr("src"),
    	    	                li.find(".swipera3").attr("data-href"),li.find(".swiperimg3").attr("src"),
    	    	                li.find(".swipera4").attr("data-href"),li.find(".swiperimg4").attr("src"),
    	    	                li.find(".swipera5").attr("data-href"),li.find(".swiperimg5").attr("src"),];
     	    	  valuearray.push(onerow);
    	           break;
    	       case "headlinerow":
      	    	  var onerow= [li.attr("data-type"),
      	    	               li.find(".headlinea").attr("data-href"),li.find(".headlinetext").html()];
      	    	  valuearray.push(onerow);
      	           break;
    	       case "textrow":
      	    	  var onerow= [li.attr("data-type"),
      	    	               li.find(".texttext").html()];
      	    	  valuearray.push(onerow);
      	           break;
    	       case "imgtextrow":
        	    	  var onerow= [li.attr("data-type"),
        	    	               li.find(".imgtextimg").attr("data-backgroundimage"),
        	    	               li.find(".imgtexta1").attr("data-href"),li.find(".imgtexttitle1").html(),li.find(".imgtexttext1").html(),
        	    	               li.find(".imgtexta2").attr("data-href"),li.find(".imgtexttitle2").html(),li.find(".imgtexttext2").html(),
        	    	               li.find(".imgtexta3").attr("data-href"),li.find(".imgtexttitle3").html(),li.find(".imgtexttext3").html(),];
        	    	  valuearray.push(onerow);
        	           break;
    	       case "videorow":
    	    	   var onerow= [li.attr("data-type"),
    	    	                li.find(".videosrc").attr("src")];
     	    	   valuearray.push(onerow);
    	           break;
    	       case "lotteryrow":
    	    	   var onerow= [li.attr("data-type"),
    	    		   li.find(".lotteryimg1").attr("src"),li.find(".lotteryimg2").attr("src"),
    	    		   li.find(".lotteryimg3").attr("src"),li.find(".lotteryimg4").attr("src"),
    	    		   li.find(".lotteryimg5").attr("src"),li.find(".lotteryimg6").attr("src"),
    	    		   li.find(".lotteryimg7").attr("src"),li.find(".lotteryimg8").attr("src"),
    	    		   li.find(".lotterytable").attr("data-lotteryrate"),li.find(".lotterytable").attr("data-lotterypoints")];
     	    	   valuearray.push(onerow);
    	           break;
    	       case "lotterypointsrow":
    	    	   var onerow= [li.attr("data-type"),
    	    		   li.find(".lotterypointsimg1").attr("src"),li.find(".lotterypointsimg2").attr("src"),
    	    		   li.find(".lotterypointsimg3").attr("src"),li.find(".lotterypointsimg4").attr("src"),
    	    		   li.find(".lotterypointsimg5").attr("src"),li.find(".lotterypointsimg6").attr("src"),
    	    		   li.find(".lotterypointsimg7").attr("src"),li.find(".lotterypointsimg8").attr("src"),
    	    		   li.find(".lotterypointstable").attr("data-lotterypointsrate"),li.find(".lotterypointstable").attr("data-lotterypointspoints")];
     	    	   valuearray.push(onerow);
    	           break;
    	       default:
    	           
    	   }
       }
       $.post("<?php echo 'http://'.$_SERVER['SERVER_NAME'].':'.$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"]; ?>",{
			valuearray:valuearray,
			pageheaddata1:$pageheaddata1,
			pageheaddata2:$pageheaddata2,
			pageheaddata3:$pageheaddata3,
			pageheaddata4:$pageheaddata4,
			pageheaddata5:$pageheaddata5,
		},
		function(data,status){
			if(status=="success"){
			alert("发布成功");}else{alert("发布失败");}
		});
 
      });
  });
</script>
<?php //TODO style 第一，第二是抽奖的?>
<style>
#lottery{width:100%px;height:100%px;margin:0px auto;border:4px solid #ba1809;}
#lottery table{background-color:yellow;}
#lottery table td{position:relative;width:104px;height:93px;text-align:center;color:#333;font-index:-999}
#lottery table td img{display:block;width:104px;height:93px;}
#lottery table td a{width:104px;height:93px;display:block;text-decoration:none;background:url(/img/lottery1.jpg) no-repeat top center;}
#lottery table td a:hover{background-image:url(/img/lottery2.jpg);}
#lottery table td.active .mask{display:block;}
.mask{
    width:100%;
    height:100%;
    position:absolute;
    left:0;
    top:0;
    background-color: rgba(252,211,4,0.5);
    display:none;
}
</style>
<style>
#lotterypoints {width:100%px;height:100%px;margin:0px auto;border:4px solid #ba1809;}
#lotterypoints table{background-color:yellow;}
#lotterypoints table td{position:relative;width:104px;height:93px;text-align:center;color:#333;font-index:-999}
#lotterypoints table td img{display:block;width:104px;height:93px;}
#lotterypoints table td a{width:104px;height:93px;display:block;text-decoration:none;background:url(/img/lottery1.jpg) no-repeat top center;}
#lotterypoints table td a:hover{background-image:url(/img/lottery2.jpg);}
#lotterypoints table td.active .mask{display:block;}
.mask{
    width:100%;
    height:100%;
    position:absolute;
    left:0;
    top:0;
    background-color: rgba(252,211,4,0.5);
    display:none;
}
</style>
<style>@font-face{font-family:uc-nexus-iconfont;src:url(chrome-extension://pogijhnlcfmcppgimcaccdkmbedjkmhi/res/font_9qmmi8b8jsxxbt9.woff) format('woff'),url(chrome-extension://pogijhnlcfmcppgimcaccdkmbedjkmhi/res/font_9qmmi8b8jsxxbt9.ttf) format('truetype')}</style><style type="text/css">
:root div[style="background:#C91521;height:90px;"],
:root .txtAdBox,
:root .titright,
:root .red[href*=".wsisp.net/"],
:root .plate-layout,
:root .newsMainBox-textad,
:root .kwLink,
:root .adtext,
:root .adfixbug,
:root .adbox,
:root .Postcon-ad
{ display: none !important; }
</style>


<style>
.pageheadbtn{
	opacity:0.3;
}
.btn-default{
	color:<?php echo $page->getPagecolor();?>;
}
#pagehead{
	    height:180px;
	    -webkit-background-size: 100% 100%;;
        background-size: 100% 100%;;
        background-position: center;
}
.headlogo{
	
	height:60px;
	width:80px;
}
#headdetail{
	position:relative;
	bottom:-100px;
}
a,span {
	 color:<?php echo $page->getPagecolor();?>;
}
.ui-widget-content a {
	color:<?php echo $page->getPagecolor();?>;
}	
.swiper-slide  {
        font-size: 18px;
        color:<?php echo $page->getPagecolor();?>;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
    }
    .parallax-bg {
        position: absolute;
        left: 0;
        top: 0;
        width: 130%;
        height: 100%;
        -webkit-background-size: 100% 100%;;
        background-size: 100% 100%;;
        background-position: center;
    }
    .swiper-slide .title {
        font-size: 20px;
        font-weight: 300;
    }
    .swiper-slide .text {
        font-size: 7px;
    }
.intro{
	background:<?php echo $page->getPagecolor();?>;
    padding:<?php echo $page->getPagepaddingtop();?>px <?php echo $page->getPagepaddinglr();?>px <?php echo $page->getPagepaddingbottom();?>px;
}
.template {
	height: 580px;
	width: 343.5px;
	float: left;
	border: 1px solid #ccc;
	overflow-y: scroll;
	overflow-x: hidden;
}

input {
	border: 2px solid #ccc;
}

.inputbox {
	height: 580px;
	width: 340px;
	float: right;
	border: 1px solid #ccc;
	overflow-y: scroll;
	overflow-x: hidden;
}

.nav_wrap {
	margin: 0 auto;
	height: 580px;
	width: 340px;
	overflow: hidden;
	border: 1px solid #ccc;
}

#picturemanager {
	height: 300px;
	width: 400px;
	overflow-y: scroll;
	overflow-x: hidden;
}

.nav_ul {
	height: 100%;
	width: 340px;
	overflow-y: auto;
	overflow-x: hidden;
}

li {
	width: 320px;
}

.img1 {
	width: 100%;
/* 	max-height: 400px; */
/* 	min-height: 200px; */
    height:300px;
}

.img2 {
	width: 100%;
/* 	max-height: 300px; */
/* 	min-height:150px; */
    height:225px;
}

ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
}

.span {
	position: absolute;
	bottom: 0;
}

.fieldset {
	display: none;
}
</style>


<?php //TODO 菜单栏  ?>
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" >美院装修</a>
		</div>
		<div>
			<ul class="nav navbar-nav">
				<li class="dropdown"><a  class="dropdown-toggle"
					data-toggle="dropdown"> 其他 <b class="caret"></b>
				</a>
					<ul class="dropdown-menu" id="generateinput">
					<li><a >图片管理</a></li>
					<li><a >页面管理</a></li>
						<li class="divider"></li>
						<li><a >优惠券</a></li>
						<li class="divider"></li>
						<li><a >客户标签</a></li>
					</ul></li>
				<li class="dropdown"><a  class="dropdown-toggle"
					data-toggle="dropdown"> 保存 <b class="caret"></b>
				</a>
					<ul class="dropdown-menu" id="generateinput">
						<li class="divider"></li>
						<li><a >保存</a></li>
						<li class="divider"></li>
						<li><a >备份</a></li>
					</ul></li>
				<li class="dropdown"><a  class="dropdown-toggle"
					data-toggle="dropdown"> 发布 <b class="caret"></b>
				</a>
					<ul class="dropdown-menu" id="generateinput">
						<li class="divider"></li>
						<li><button id="immediatelyrelease">立即发布</button></li>
						<li class="divider"></li>
						<li><button id="release">定时发布</button></li>
					</ul></li>
			</ul>
	        <div style="float:right;padding:10px;">
		       <a href="javascript:history.go(-1);"><span class="glyphicon glyphicon-chevron-left"></span></a>
		       &nbsp;&nbsp;&nbsp;&nbsp;
		       <a href="javascript:history.go(1);"><span class="glyphicon glyphicon-chevron-right"></span></a>
		    </div>
		</div>
	</div>
</nav>

<?php //TODO 展示模块
include_once 'public/php/templateformodule.phtml';?>



<?php //TODO 输入模块
include_once 'public/php/templateforinput.phtml';?>

<?php //TODO nav_wrap?>
<div class="nav_wrap">
<ul id="sortable" class="nav_ul">
<?php if($page->getPagetype()=="首页"):?>
<li data-type="headpagerow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#headpagesubmit").attr("onclick","myheadpage("+$(this).index(".intro")+")");
		   $("#headpagerowname").val($("#headpagename").html());
		   $("#headpagerowicon").attr("src",$("#headpageicon").attr("src"));
	       $("#headpagerowimg").attr("src",$("#pagehead").attr("data-backgroundimg"));
           $("#headpagerowlink").val($("#pagehead").attr("data-href"));
           $(".fieldset").hide();
           $("#headpagerowfield").show();}'>
<div data-role="page" id="pageone" >
<div class="container" style="position:fixed;opacity:0.8;z-index:100">
   <div class="row" style="width:320px" id="headpagebtnset">
   <div class="col-xs-2">
   <button type="button" class="btn btn-default btn-sm pageheadbtn">
  <span class="glyphicon glyphicon-qrcode" aria-hidden="true"></span>
</button>
</div>
<div class="col-xs-6">
 <div class="input-group input-group-sm">
      <input type="text" class="form-control pageheadbtn"  placeholder="Search for...">
      <span class="input-group-btn">
        <button class="btn btn-default pageheadbtn" type="button">搜!</button>
      </span>
    </div>
 </div>
 <div class="col-xs-2">
<button type="button" class="btn btn-default btn-sm pageheadbtn">
  <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
</button>
 </div>
 <div class="col-xs-2">
<button type="button" class="btn btn-default btn-sm pageheadbtn">
  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
</button>
 </div>
 </div>
 </div>


<div class="panel panel-default" id="pagehead" data-href="<?php echo $page->getPageheaddata4();?>" style="background-image:url(<?php echo $page->getPageheaddata3();?>);" data-backgroundimg="<?php echo $page->getPageheaddata3();?>">
	<div class="panel-body container" >
	    <div id="headdetail" class="row" style="width:320px">
		   <div class="col-xs-3"><img alt="" src="<?php echo $page->getPageheaddata1();?>" class="headlogo" id="headpageicon"></div>
		   <div class="col-xs-6">
		   <span id="headpagename" style="font-size: 200%"><?php echo $page->getPageheaddata2();?></span>
		   <br>
		   <img alt="" src="/img/mylogo.png" style="width:15px;height:15px;"><span>线上服务</span>
		   </div>
		   <div class="col-xs-3">
		   <span>会员数</span>
		   <br>
		   <span>328</span>
		   </div>
	</div>
</div>
</div>

<div class="btn-group btn-group-justified" role="group" id="subnav" style="z-index:100;width:320px">
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default">首页</button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default">产品</button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default">活动</button>
  </div>
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-default">动态</button>
  </div>
</div>
</div>
</li>

<!-- 注意页面类型 已修改，只要不是首页，就输出空头部  -->
<?php else:?>
<li><div class="btn-group btn-group-justified" role="group" id="subnav" style="z-index:100;width:320px"></div></li>
<?php endif;?>

<?php //TODO 组件模块 
include_once 'public/php/templateforedit.phtml';?>
	</ul>
</div>



    <?php //TODO swiper 轮播图js?>
    <!-- Initialize Swiper -->
    <script>
    var swiper = new Swiper('.swiperswiper', {
        pagination: '.swiperpagination',
        slidesPerView: 'auto',
        paginationClickable: true,
        spaceBetween: 30,
        autoplay: 2500,
        autoplayDisableOnInteraction: false,
        parallax: true,
        speed: 600,
    });
    var imgtext = new Swiper('.imgtextswiper', {
        pagination: '.imgtextpagination',
        slidesPerView: 'auto',
        paginationClickable: true,
        spaceBetween: 30,
        autoplay: 2500,
        autoplayDisableOnInteraction: false,
        parallax: true,
        speed: 600,
    });
    </script>
    
<?php //图片选择器
include_once 'public/php/picturechoice.phtml';?>
<?php //链接选择器
include_once 'public/php/linkchoice.phtml';?>