
<script>
//发布
$(function() {
    $( "#immediatelyrelease" ).click(function() {
    	var valuearray=new Array();
       for(var i=0;i<$("#sortable li").length;i++){
    	  var li=$("#sortable li").eq(i);
    	   switch(li.attr("data-type"))
    	   {
    	       case "singlerow":
    	    	  var onerow= [<?php echo $page->getPageid();?>,li.attr("data-type"),
    	    	               li.find(".singlea").attr("data-href"),li.find(".singleimg").attr("src")];
    	    	  valuearray.push(onerow);
    	           break;
    	       case "doublerow":
    	    	   var onerow= [<?php echo $page->getPageid();?>,li.attr("data-type"),
    	    	                li.find(".doublea1").attr("data-href"),li.find(".doubleimg1").attr("src"),
    	    	                li.find(".doublea2").attr("data-href"),li.find(".doubleimg2").attr("src")];
     	    	  valuearray.push(onerow);
    	           break;
    	       case "videorow":
    	    	   var onerow= [<?php echo $page->getPageid();?>,li.attr("data-type"),
    	    	                li.find(".videorowsrc").attr("src")];
     	    	  valuearray.push(onerow);
    	           break;
    	       default:
    	           
    	   }
       }
       $.post("template",{
			valuearray:valuearray
		},
		function(data,status){
			if(status=="success"){
			alert("发布成功");}else{alert("发布失败");}
		});
      
      });
  });
</script>
<?php //TODO style?>
<style>
.intro{
	background:<?php echo $page->getPagecolor();?>;
}
.template {
	height: 520px;
	width: 343.5px;
	float: left;
	border: 1px solid #ccc;
	overflow-y: scroll;
	overflow-x: hidden;
}

input {
	border: 2px solid #ccc;
}

.inputbox {
	height: 520px;
	width: 340px;
	float: right;
	border: 1px solid #ccc;
	overflow-y: scroll;
	overflow-x: hidden;
}

.nav_wrap {
	margin: 0 auto;
	height: 520px;
	width: 322px;
	overflow: hidden;
	border: 1px solid #ccc;
}

#picturemanager {
	height: 300px;
	width: 400px;
	overflow-y: scroll;
	overflow-x: hidden;
}

.nav_ul {
	height: 100%;
	width: 340px;
	overflow-y: auto;
	overflow-x: hidden;
}

li {
	width: 320px;
}

.img1 {
	width: 100%;
	height: 200px;
}

.img2 {
	width: 100%;
	height: 100px;
}

ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
}

.span {
	position: absolute;
	bottom: 0;
}

.fieldset {
	display: none;
}
</style>


<?php //TODO 菜单栏  ?>
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" >美院装修</a>
		</div>
		<div>
			<ul class="nav navbar-nav">
				<li class="dropdown"><a  class="dropdown-toggle"
					data-toggle="dropdown"> 其他 <b class="caret"></b>
				</a>
					<ul class="dropdown-menu" id="generateinput">
					<li><a >图片管理</a></li>
					<li><a >页面管理</a></li>
						<li class="divider"></li>
						<li><a >优惠券</a></li>
						<li class="divider"></li>
						<li><a >客户标签</a></li>
					</ul></li>
				<li class="dropdown"><a  class="dropdown-toggle"
					data-toggle="dropdown"> 保存 <b class="caret"></b>
				</a>
					<ul class="dropdown-menu" id="generateinput">
						<li class="divider"></li>
						<li><a >保存</a></li>
						<li class="divider"></li>
						<li><a >备份</a></li>
					</ul></li>
				<li class="dropdown"><a  class="dropdown-toggle"
					data-toggle="dropdown"> 发布 <b class="caret"></b>
				</a>
					<ul class="dropdown-menu" id="generateinput">
						<li class="divider"></li>
						<li><button id="immediatelyrelease">立即发布</button></li>
						<li class="divider"></li>
						<li><button id="release">定时发布</button></li>
					</ul></li>
			</ul>
		</div>
	</div>
</nav>



<?php //TODO template?>
<div class="template" id="template" data-template="template">
	<div id="accordion">
		<h3>部分 1</h3>
		<div></div>
		<h3>部分 2</h3>
		<div>
			<ul>
				<!-- 单列图片  -->
				<li id="draggable0" data-type="singlerow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#singlesubmit").attr("onclick","mysingle("+$(this).index(".intro")+")");
						$("#singledelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#singlerowimg").attr("src",$(this).find(".singleimg").attr("src"));
           $("#singlerowlink").val($(this).find(".singlea").attr("data-href"));
           $(".fieldset").hide();
           $("#singlerowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<a  data-href="" class="singlea"> <img alt=""
										src="/img/123.jpg" class="img1 singleimg">
									</a>
								</div>
							</div>
						</div>
					</div>
				</li>
				<!-- 双列图片 -->
				<li id="draggable1" data-type="doublerow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#doublesubmit").attr("onclick","mydouble("+$(this).index(".intro")+")");
						$("#doubledelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#doublerowimg1").attr("src",$(this).find(".doubleimg1").attr("src"));
           $("#doublerowlink1").val($(this).find(".doublea1").attr("data-href"));
           $("#doublerowimg2").attr("src",$(this).find(".doubleimg2").attr("src"));
           $("#doublerowlink2").val($(this).find(".doublea2").attr("data-href"));
           $(".fieldset").hide();
           $("#doublerowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<a  data-href="" class="doublea1"> <img alt=""
										src="/img/123.jpg" class="img2 doubleimg1">
									</a>
								</div>
							</div>
							<div class="col">
								<div class="col-demo">
									<a  data-href="" class="doublea2"> <img alt=""
										src="/img/123.jpg" class="img2 doubleimg2">
									</a>
								</div>
							</div>
						</div>
					</div>
				</li>
				<!-- 视频  -->
				<li id="draggable2" data-type="videorow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#videosubmit").attr("onclick","myvideo("+$(this).index(".intro")+")");
						$("#videodelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#videorowsrc").attr("src",$(this).find(".videorowsrc").attr("src"));
           $(".fieldset").hide();
           $("#videorowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									
									<video width="320" height="auto" controls class="img1 videorowsrc" >
                                     <source src="/salon/test.mp4" type="video/mp4">
                                    </video> 
								</div>
							</div>
						</div>
					</div>
				</li>
			</ul>
		</div>
		<h3>部分 3</h3>
		<div></div>
		<h3>部分 4</h3>
		<div></div>
	</div>
</div>

<?php //TODO input box?>
<div class="inputbox">
	<!-- 单列图片 -->
	<fieldset class="fieldset" id="singlerowfield">
		<legend>单列图片</legend>
		图片<br> <img alt="" src="/img/234.jpg" id="singlerowimg"
			class="picturechoose1 img1"> 链接<input type="text" size="33"
			id="singlerowlink"> <br> <button
			onclick="mysingle('100')" id="singlesubmit">提交</button>
		<button onclick="mydelete('100')" id="singledelete">删除</button>
	</fieldset>

	<!-- 双列图片 -->
	<fieldset class="fieldset" id="doublerowfield">
		<legend>双列图片</legend>
		图片<br> <img alt="" src="/img/234.jpg" id="doublerowimg1"
			class="picturechoose1 img1"> 链接<input type="text" size="33"
			id="doublerowlink1"> <br> 图片<br> <img alt="" src="/img/234.jpg"
			id="doublerowimg2" class="picturechoose2 img1"> 链接<input type="text"
			size="33" id="doublerowlink2"> <br> <button
			onclick="mydouble('100')" id="doublesubmit">提交</button>
		<button onclick="mydelete('100')" id="doubledelete">删除</button>
	</fieldset>
	
		<!-- 视频 -->
	<fieldset class="fieldset" id="videorowfield">
		<legend>视频</legend>
		视频<br> 
			<video width="320" height="240" controls class="picturechoose1 img1" id="videorowsrc">
              <source src="/salon/test.mp4" type="video/mp4"  >
            </video> 
			<button onclick="myvideo('100')" id="videosubmit">提交</button>
		<button onclick="mydelete('100')" id="videodelete">删除</button>
	</fieldset>
</div>

<?php //TODO nav_wrap?>
<div class="nav_wrap">
	<ul id="sortable" class="nav_ul">
<?php foreach ($templateitem as $item) :?>
<?php switch ($item->getTemplatetype()): ?>
<?php case "singlerow": ?>
<li  data-type="singlerow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#singlesubmit").attr("onclick","mysingle("+$(this).index(".intro")+")");
						$("#singledelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#singlerowimg").attr("src",$(this).find(".singleimg").attr("src"));
           $("#singlerowlink").val($(this).find(".singlea").attr("data-href"));
           $(".fieldset").hide();
           $("#singlerowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<a  data-href="<?php echo $item->getTemplatedata1()?>" class="singlea"> <img alt=""
										src="<?php echo $item->getTemplatedata2()?>" class="img1 singleimg">
									</a>
								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "doublerow": ?>
<li  data-type="doublerow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#doublesubmit").attr("onclick","mydouble("+$(this).index(".intro")+")");
						$("#doubledelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#doublerowimg1").attr("src",$(this).find(".doubleimg1").attr("src"));
           $("#doublerowlink1").val($(this).find(".doublea1").attr("data-href"));
           $("#doublerowimg2").attr("src",$(this).find(".doubleimg2").attr("src"));
           $("#doublerowlink2").val($(this).find(".doublea2").attr("data-href"));
           $(".fieldset").hide();
           $("#doublerowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									<a  data-href="<?php echo  $item->getTemplatedata1()?>" class="doublea1"> <img alt=""
										src="<?php echo  $item->getTemplatedata2()?>" class="img2 doubleimg1">
									</a>
								</div>
							</div>
							<div class="col">
								<div class="col-demo">
									<a  data-href="<?php echo  $item->getTemplatedata3()?>" class="doublea2"> <img alt=""
										src="<?php echo $item->getTemplatedata4()?>" class="img2 doubleimg2">
									</a>
								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php case "videorow": ?>
				<li  data-type="videorow" class="ui-state-highlight intro"
					onclick='if($(this).parent().attr("id")){
						$(".intro").css("background","<?php echo $page->getPagecolor();?>");
                        $(this).css("background","#ccc");
						$("#videosubmit").attr("onclick","myvideo("+$(this).index(".intro")+")");
						$("#videodelete").attr("onclick","mydelete("+$(this).index(".intro")+")");
	       $("#videorowsrc").attr("src",$(this).find(".videorowsrc").attr("src"));
           $(".fieldset").hide();
           $("#videorowfield").show();}'>
					<div class="content">
						<div class="row">
							<div class="col">
								<div class="col-demo">
									
									<video width="320" height="240" controls class="img1 videorowsrc" >
                                     <source src="<?php echo $item->getTemplatedata1()?>" type="video/mp4">
                                    </video> 
								</div>
							</div>
						</div>
					</div>
				</li>
<?php break;?>
<?php endswitch; ?>
<?php endforeach;?>
	</ul>
</div>


<?php //TODO picturemanager?>
<?php
$dir2 = "public/salon/".$id;
$dir3 = iconv('utf-8', 'gbk', $dir2);
$file = scandir($dir3);
?>
 <?php 
 $photo=array();
 $directory=array();
 foreach ($file as $filegb): 
 $filesrc=iconv("GB2312","UTF-8",$filegb);
 if(substr(strrchr($filesrc, '.'), 1)==null){
     array_push($directory,$filesrc);
 }else{array_push($photo,$filesrc);}
 ?>
  <?php endforeach; ?>  
<div id="picturemanager1" title="图片选择器" class="picturemanager" data-imgnumber="">
<div class="dropdown" style="float: left">
	<button type="button" class="btn dropdown-toggle" id="dropdownMenu1" 
			data-toggle="dropdown">
		图片根目录
		<span class="caret"></span>
	</button>
	<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
		<li role="presentation" onclick="rootdir1()">
			<a role="menuitem" tabindex="-1">图片根目录</a>
		</li>
		<li role="presentation" class="divider"></li>
		<?php for($i=0;$i<count($directory);$i++):
		if($directory[$i]!="."&&$directory[$i]!=".."){?>
		<li role="presentation" onclick="dirchoose1('<?php echo $directory[$i];?>')">
			<a role="menuitem" tabindex="-1"><?php echo $directory[$i];?></a>
		</li>
		<?php }endfor;?>
	</ul>
</div>

	<table class="table">
		<caption>点击图片进行选择</caption>
		<thead>
			<tr>
				<th>预览</th>
				<th>名称</th>
			</tr>

		</thead>
		
		<tbody id="rootdir1">
        <?php for($i=0;$i<count($photo);$i++):
        if(end(explode('.', $photo[$i]))=="jpg"||end(explode('.', $photo[$i]))=="png"||end(explode('.', $photo[$i]))=="gif"):?>
            <tr>
				<td><img src="<?php echo '/salon/'.$id.'/'.$photo[$i]; ?>"
					onclick="copyfilesrc1('<?php echo '/salon/'.$id.'/'.$photo[$i]; ?>')"
					alt="Smiley face" width="60" height="30" class="imgchoose" data-imgnumber=""></td>
				<td><?php echo $photo[$i]; ?></td>
			</tr>
			<?php elseif (end(explode('.', $photo[$i]))=="mp4"):?>
			<tr>
				
			    <td>
                     <video width="160" height="120" controls class="imgchoose" data-imgnumber="" onclick="copyfilesrc1('<?php echo '/salon/'.$id.'/'.$photo[$i]; ?>')">
                     <source src="<?php echo '/salon/'.$id.'/'.$photo[$i]; ?>" type="video/mp4">
                    </video>
               </td>
				<td><?php echo $photo[$i]; ?></td>
			</tr>
			<?php endif;?>
       <?php endfor; ?>
       </tbody>
       <?php for($i=0;$i<count($directory);$i++):
		if($directory[$i]!="."&&$directory[$i]!=".."){
		    $dir4 = "public/salon/".$id.'/'.$directory[$i];
		    $dir5 = iconv('utf-8', 'gbk', $dir4);
		    $photo1 = scandir($dir5);
		    ?>
       	<tbody class="subdir1 <?php echo $directory[$i]?>1">
        <?php for($j=0;$j<count($photo1);$j++):
        if($photo1[$j]!="."&&$photo1[$j]!=".."){
        if(end(explode('.', $photo[$i]))=="jpg"||end(explode('.', $photo[$i]))=="png"||end(explode('.', $photo[$i]))=="gif"):?>
            <tr>
				<td><img src="<?php echo '/salon/'.$id.'/'.$directory[$i].'/'.$photo1[$j]; ?>"
					onclick="copyfilesrc1('<?php echo '/salon/'.$id.'/'.$directory[$i].'/'.$photo1[$j]; ?>')"
					alt="Smiley face" width="60" height="30" class="imgchoose" data-imgnumber=""></td>
				<td><?php echo $photo1[$j]; ?></td>
			</tr>
			<?php elseif (end(explode('.', $photo[$i]))=="mp4"):?>
						<tr>
				
			    <td>
                     <video width="160" height="120" controls class="imgchoose" data-imgnumber="" onclick="copyfilesrc1('<?php echo '/salon/'.$id.'/'.$directory[$i].'/'.$photo[$i]; ?>')">
                     <source src="<?php echo '/salon/'.$id.'/'.$directory[$i].'/'.$photo[$i]; ?>" type="video/mp4">
                    </video>
               </td>
				<td><?php echo $photo[$i]; ?></td>
			</tr>
			<?php endif;?>
       <?php }endfor; ?>
       </tbody>
       <?php }endfor;?>
	</table>
</div>

<?php //TODO link manager?>
  <script>
  $(function() {
    $( "#linkdialog" ).dialog({
      autoOpen: false,
      width:800,height: 500,
    });
 
    $( "#linkopener" ).click(function() {
      $( "#linkdialog" ).dialog( "open" );
    });
  });
  </script>
<div id="linkdialog" title="链接选择器">
  <div class="btn-group">
	<button type="button" class="btn btn-default">宝贝链接</button>
	<button type="button" class="btn btn-default">页面链接</button>
	<button type="button" class="btn btn-default">分类链接</button>
	<button type="button" class="btn btn-default">常用链接</button>
</div><div class="panel panel-default">
    <div class="panel-body">
        <table class="table">
 <tr>
     <th>按产品编号</th>
     <th>产品名称</th>
     <th>产品图</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($products as $product): ?>
 
 <tr>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('management','action'=>'productedit','sub'=>$product->getProdid()));?>">
             <?php echo $this->escapeHtml($product->getProdid()); ?></a>
     </td>
     <td><?php echo $this->escapeHtml($product->getProdtitle()); ?></td>
     
     <td>
     <td><img alt="" style="height:30px;" src="<?php  echo $product->getProdpicture1(); ?>" ></td>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('action'=>'productdelete','sub'=>$product->getProdid()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
    </div>
</div>
</div>
 
<button id="linkopener">打开对话框</button>
