<?php
$title = 'Add new task';
$this->headTitle($title);
?>
<h5><?php echo $this->escapeHtml($title); ?></h5>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cosmetic', array(
    'action' => 'productadd'
)));
$form->get('submit')->setAttribute('value', 'Add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('prodid'));
echo $this->formhidden($form->get('salnumber'));
echo $this->formhidden($form->get('prodnumber'));
echo $this->formRow($form->get('prodtitle'));
echo $this->formRow($form->get('prodsubtitle'));
echo $this->formRow($form->get('prodprice'));
echo $this->formRow($form->get('prodoriginal'));
echo $this->formRow($form->get('prodpoints'));
echo $this->formRow($form->get('prodsales'));
echo $this->formRow($form->get('proddetail'));
echo $this->formRow($form->get('prodthumbnail'));
echo $this->formRow($form->get('prodphoto1'));
echo $this->formRow($form->get('prodphoto2'));
echo $this->formRow($form->get('prodphoto3'));
echo $this->formRow($form->get('prodphoto4'));
echo $this->formRow($form->get('prodphoto5'));
echo $this->formRow($form->get('prodtimes'));
echo $this->formRow($form->get('prodtype'));
echo $this->formRow($form->get('prodwhitening'));
echo $this->formRow($form->get('prodmoisturize'));
echo $this->formRow($form->get('prodantisenile'));
echo $this->formRow($form->get('prodfreckle'));
echo $this->formRow($form->get('proddesensitization'));
?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
var_dump($post);