<?php
$title = 'Edit task';
$this->headTitle($title);
?>
<h5><?php echo $this->escapeHtml($title); ?></h5>

<?php
$form = $this->form;
$url = $this->url('cosmetic', array(
    'action' => 'productedit',
    'sub' => $sub
));
$form->setAttribute('action', $url);
$form->get('submit')->setAttribute('value', 'Edit');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('prodid'));
echo $this->formhidden($form->get('salnumber'));
echo $this->formhidden($form->get('prodnumber'));
echo $this->formRow($form->get('prodtitle'));
echo $this->formRow($form->get('prodsubtitle'));
echo $this->formRow($form->get('prodprice'));
echo $this->formRow($form->get('prodoriginal'));
echo $this->formRow($form->get('prodpoints'));
echo $this->formRow($form->get('prodsales'));
echo $this->formRow($form->get('proddetail'));
echo $this->formRow($form->get('prodthumbnail'));
echo $this->formRow($form->get('prodphoto1'));
echo $this->formRow($form->get('prodphoto2'));
echo $this->formRow($form->get('prodphoto3'));
echo $this->formRow($form->get('prodphoto4'));
echo $this->formRow($form->get('prodphoto5'));
echo $this->formRow($form->get('prodphoto1f'));
echo $this->formRow($form->get('prodphoto2f'));
echo $this->formRow($form->get('prodphoto3f'));
echo $this->formRow($form->get('prodphoto4f'));
echo $this->formRow($form->get('prodphoto5f'));
echo $this->formRow($form->get('prodtimes'));
echo $this->formRow($form->get('prodtype'));
echo $this->formRow($form->get('prodwhitening'));
echo $this->formRow($form->get('prodmoisturize'));
echo $this->formRow($form->get('prodantisenile'));
echo $this->formRow($form->get('prodfreckle'));
echo $this->formRow($form->get('proddesensitization'));
echo $this->formRow($form->get('detpicture1'));
echo $this->formRow($form->get('detpicture2'));
echo $this->formRow($form->get('detpicture3'));
echo $this->formRow($form->get('detpicture4'));
echo $this->formRow($form->get('detpicture5'));
echo $this->formRow($form->get('detpicture6'));
echo $this->formRow($form->get('detpicture7'));
echo $this->formRow($form->get('detpicture8'));
echo $this->formRow($form->get('detpicture9'));
echo $this->formRow($form->get('detpicture10'));
echo $this->formRow($form->get('detpicture11'));
echo $this->formRow($form->get('detpicture1f'));
echo $this->formRow($form->get('detpicture2f'));
echo $this->formRow($form->get('detpicture3f'));
echo $this->formRow($form->get('detpicture4f'));
echo $this->formRow($form->get('detpicture5f'));
echo $this->formRow($form->get('detpicture6f'));
echo $this->formRow($form->get('detpicture7f'));
echo $this->formRow($form->get('detpicture8f'));
echo $this->formRow($form->get('detpicture9f'));
echo $this->formRow($form->get('detpicture10f'));
echo $this->formRow($form->get('detpicture11f'));
echo $this->formRow($form->get('detvideo'));
echo $this->formRow($form->get('detvideof'));
?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);