  <?php
$title = 'My task list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

 <p><a href="<?php echo $this->url('cosmetic', array('management',
         'action'=>'promotionadd'));?>">添加促销活动</a></p>


 <table class="table">
 <tr>
     <th>Task</th>
     <th>Created</th>
     
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($promotions as $promotion): ?>
 
 <tr>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('management','action'=>'promotionedit','sub'=>$promotion->getPromid()));?>">
             <?php echo $this->escapeHtml($promotion->getPromdetail()); ?></a>
     </td>
     <td><?php echo $this->escapeHtml($promotion->getPromtitle()); ?></td>
     
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('action'=>'promotiondelete','sub'=>$promotion->getPromid()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>

