<?php
$title = 'Add new task';
$this->headTitle($title);
?>
<h5><?php echo $this->escapeHtml($title); ?></h5>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cosmetic', array(
    'action' => 'salonslideadd'
)));
$form->get('submit')->setAttribute('value', 'Add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('ssid'));
echo $this->formhidden($form->get('salnumber'));
echo $this->formRow($form->get('ssphoto1'));
echo $this->formRow($form->get('ssphoto2'));
echo $this->formRow($form->get('ssphoto3'));
echo $this->formRow($form->get('ssphoto1f'));
echo $this->formRow($form->get('ssphoto2f'));
echo $this->formRow($form->get('ssphoto3f'));
echo $this->formRow($form->get('sssrc1'));
echo $this->formRow($form->get('sssrc2'));
echo $this->formRow($form->get('sssrc3'));

?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
var_dump($post);