  <?php
$title = 'My task list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

 <p><a href="<?php echo $this->url('cosmetic', array('management',
         'action'=>'salonlayoutadd'));?>">添加布局活动</a></p>


 <table class="table">
 <tr>
     <th>Task</th>
     <th>Created</th>
     
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($salonlayouts as $salonlayout): ?>
 
 <tr>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('management','action'=>'salonlayoutedit','sub'=>$salonlayout->getSlid()));?>">
             <?php echo $this->escapeHtml($salonlayout->getSlid()); ?></a>
     </td>
     <td><?php echo $this->escapeHtml($salonlayout->getSlphoto1()); ?></td>
     
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('action'=>'salonlayoutdelete','sub'=>$salonlayout->getSlid()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>

