  <?php
$title = 'My task list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

 <p><a href="<?php echo $this->url('cosmetic', array('cosmetic',
         'action'=>'salonbuttonadd'));?>">添加布局活动</a></p>
 <table class="table">
 <tr>
     <th>Task</th>
     <th>Created</th>
     
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($salonbuttons as $salonbutton): ?>
 
 <tr>
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('cosmetic','action'=>'salonbuttonedit','sub'=>$salonbutton->getSbid()));?>">
             <?php echo $this->escapeHtml($salonbutton->getSbid()); ?></a>
     </td>
     <td><?php echo $this->escapeHtml($salonbutton->getSalonbutton()); ?></td>
     
     <td>
         <a href="<?php echo $this->url('cosmetic',
             array('action'=>'salonbuttondelete','sub'=>$salonbutton->getSbid()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>

