<?php
$title = 'Add new task';
$this->headTitle($title);
?>
<h5><?php echo $this->escapeHtml($title); ?></h5>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('cosmetic', array(
    'action' => 'salonlayoutadd'
)));
$form->get('submit')->setAttribute('value', 'Add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('slid'));
echo $this->formhidden($form->get('salnumber'));
echo $this->formRow($form->get('slphoto1'));
echo $this->formRow($form->get('slphoto2'));
echo $this->formRow($form->get('slphoto3'));
echo $this->formRow($form->get('slphoto4'));
echo $this->formRow($form->get('slphoto5'));
echo $this->formRow($form->get('slphoto6'));
echo $this->formRow($form->get('slphoto7'));
echo $this->formRow($form->get('slphoto8'));
echo $this->formRow($form->get('slphoto9'));
echo $this->formRow($form->get('slphoto10'));
echo $this->formRow($form->get('slphoto1f'));
echo $this->formRow($form->get('slphoto2f'));
echo $this->formRow($form->get('slphoto3f'));
echo $this->formRow($form->get('slphoto4f'));
echo $this->formRow($form->get('slphoto5f'));
echo $this->formRow($form->get('slphoto6f'));
echo $this->formRow($form->get('slphoto7f'));
echo $this->formRow($form->get('slphoto8f'));
echo $this->formRow($form->get('slphoto9f'));
echo $this->formRow($form->get('slphoto10f'));
echo $this->formRow($form->get('slsrc1'));
echo $this->formRow($form->get('slsrc2'));
echo $this->formRow($form->get('slsrc3'));
echo $this->formRow($form->get('slsrc4'));
echo $this->formRow($form->get('slsrc5'));
echo $this->formRow($form->get('slsrc6'));
echo $this->formRow($form->get('slsrc7'));
echo $this->formRow($form->get('slsrc8'));
echo $this->formRow($form->get('slsrc9'));
echo $this->formRow($form->get('slsrc10'));

?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
var_dump($post);