<?php
 $title = 'Edit task';
 $this->headTitle($title);
 ?>
 <h5><?php echo $this->escapeHtml($title); ?></h5>

 <?php
 $form = $this->form;
 $url = $this->url('cosmetic', array('action' => 'salonbuttonedit','sub'=>$sub));
 $form->setAttribute('action', $url);
 $form->get('submit')->setAttribute('value', 'Edit');
 $form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('sbid'));
echo $this->formhidden($form->get('salnumber'));
echo $this->formRow($form->get('salonbutton'));

 ?>
 <div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
 <?php
 echo $this->form()->closeTag($form);