<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cosmetologist\Module'                        => __DIR__ . '/Module.php',
    'Cosmetologist\Controller\Cos2Controller' => __DIR__ . '/src/Cosmetologist/Controller/Cos2Controller.php',
    'CosmetologistTest\Framework\TestCase'        => __DIR__ . '/tests/Cosmetologist/Framework/TestCase.php',
    'CosmetologistTest\SampleTest'                => __DIR__ . '/tests/Cosmetologist/SampleTest.php',
);
