<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Salonboss\Module'                        => __DIR__ . '/Module.php',
    'Salonboss\Controller\SalonbossController' => __DIR__ . '/src/Salonboss/Controller/SalonbossController.php',
    'SalonbossTest\Framework\TestCase'        => __DIR__ . '/tests/Salonboss/Framework/TestCase.php',
    'SalonbossTest\SampleTest'                => __DIR__ . '/tests/Salonboss/SampleTest.php',
);
